### ISSUE TITLE
Make `carbon.now.sh` a PWA

### ISSUE THREAD

**Issue by yeskunall** [dawnlabs/carbon#107]
This is something that can start out slow, but if you guys seem interested, I think, IMO, turning [carbon.now.sh](https://carbon.now.sh) into a PWA would be super 👍

The most important think would be to allow caching, and hence enable the site to work offline as well. What do you guys think?

Loving this app so far 😍

**Comment by jakedex** [comment]
[This](https://github.com/ooade/NextSimpleStarter) may be a useful reference

**Comment by itaditya** [comment]
@yeskunall I can also help out with this, do tell if you need help

**Comment by mfix22** [comment]
Running the Chrome PWA-audit in the Dev-tools is helpful.

**Comment by jxshco** [comment]
Is anyone working on this? wouldn't mind submitting a PR

**Comment by mfix22** [comment]
Not at the moment, Josh. We would love to see a PR from you!

**Comment by jxshco** [comment]
@mfix22 Sure I'll take this one
