### ISSUE TITLE
Share button isn't working on https://carbon.now.sh/

### ISSUE THREAD

**Issue by alexfalcucc** [dawnlabs/carbon#110]
![recorded](https://user-images.githubusercontent.com/6964211/31259833-4f5c378c-aa20-11e7-91b8-430e55f05acc.gif)
> when you hit "tweet image" button, nothing happens.

**Comment by jakedex** [comment]
Hmm, It's working just fine on my end. Are you seeing any errors in your console?

**Comment by alexfalcucc** [comment]
Yeh, seems like the URL it's a bad request here.
![selecao_103](https://user-images.githubusercontent.com/6964211/31260158-557c2a58-aa22-11e7-9313-5037a9b02183.png)

**Comment by yeskunall** [comment]
I can confirm the same. 😟

**Comment by mfix22** [comment]
429 is a rate limit status code ☹️ . We will post an update as soon as we have one.

**Comment by mfix22** [comment]
Try now! (:

**Comment by briandennis** [comment]
Closing if this is resolved. Feel free to reopen if the problem persists

**Comment by alexfalcucc** [comment]
sorry my delay of the feedback. it's working fine! thanks!
