### ISSUE TITLE
Support variable export sizes (including higher resolution)

### ISSUE THREAD

**Issue by aulneau** [dawnlabs/carbon#112]
I went through the issues and couldn't find this in there.

It would be fantastic to be able to export and larger sizes 👍 

Love what you've got so far!

**Comment by bfred-it** [comment]
Definitely larger sizes are needed. Twitter won't even fill most of the image's available area for small snippets:

[<img width="726" alt="short snippet example" src="https://user-images.githubusercontent.com/1402241/33480234-fb59bd7e-d6c2-11e7-8d1a-b79fddef2132.png">](https://twitter.com/bfred_it/status/936550547556929538)

**Comment by photonstorm** [comment]
@bfred-it  you sure the twitter issue shown in the picture above wasn't related to #145 ? I was getting loads of excess blank space on the sides of my PNGs, which would absolutely cause the issue you shown in your twitter grab.

**Comment by bfred-it** [comment]
Oh wow you're absolutely right, the image has transparent padding around it. Is that fix not deployed yet? I had this issue 4 hours after the PR was merged.

**Comment by photonstorm** [comment]
No, don't think it's deployed, as it still happens for me when I save a PNG. Hopefully won't be long though :)
