### ISSUE TITLE
No solarized dark theme

### ISSUE THREAD

**Issue by Drarok** [dawnlabs/carbon#113]
## Expected Behavior
I'd like to use the solarized dark theme

## Actual Behavior
Only solarized light is available

**Comment by yeskunall** [comment]
Might be a bit trickier than the usual bit of just adding it to the list of constants, as seen here

https://github.com/dawnlabs/carbon/blob/0303b48928ee4050f8bd1cf00549a1bf35235058/lib/constants.js#L60-L63

as it seems the css for both themes is in one file `solarized.css. :thinking:

**Comment by Drarok** [comment]
Ah, no wonder I couldn't find a solarized-dark file. I'll have a go at looking further into this, though I'm fairly new to React so struggling to follow the architecture and how everything holds together.

**Comment by yeskunall** [comment]
I don't think there's much you can _dig_ into (code-wise), as this is inherently an issue with CodeMirror, not Carbon itself.

You can head over to https://discuss.codemirror.net/ to ping the authors and see their reasoning behind not splitting the light and the dark themes and maybe even request that they move the CSS related to the dark theme into `solarized-dark.css`.

I would do it myself, but I don't want to make an account just for this reason. 😜

If nothing, we could manually add it, but that would be up to the maintainers. 🚶

**Comment by Drarok** [comment]
[Their demo page](https://codemirror.net/demo/theme.html) shows Solarized options for dark and light, I was going to have a go at setting the right options, but so far as I can see, setting the theme to 'solarized dark' should work, expanding to CSS classes `cm-s-solarized` and `cm-s-dark`. It doesn't work, sadly.
