### ISSUE TITLE
Use image as background

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/carbon#122]
I think it'd be really cool to support using user-uploaded images as backgrounds. We'd probably want to make the current color-select dropdown tabbed, with a tab for image background settings ('upload image', 'remove image', 'scale image', etc). 

- Users should be able to scale the background
- Users should be able to reposition the background (I'm thinking we could just make it draggable in the editor?)

**Comment by mfix22** [comment]
I think it would be cool to also add support for drag-n-dropping the images too 😄
