### ISSUE TITLE
Frosted glass terminal style

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/carbon#123]
<img width="613" alt="bbaf728e-c31a-11e6-972f-0995e77a32a0" src="https://user-images.githubusercontent.com/10369094/31911790-ab8c5f6c-b7f6-11e7-9ee9-582752a44dde.png">

![dmgz16nwaaapyj8](https://user-images.githubusercontent.com/10369094/31911846-d279ed42-b7f6-11e7-9db1-9d8b23f5126f.jpg)

- Add terminal transparency slider to settings
- This should be rather trivial to implement with css: https://css-tricks.com/frosting-glass-css-filters/

**Comment by astronomersiva** [comment]
I would love to take a dab at this if @vishesh-dembla is no longer working on this.

On first look, it looks like the background style for the code editor is from CodeMirror and as such we will not be able to directly manipulate its styles.

I was thinking we could add a background property to each theme in [constants.js](https://github.com/dawnlabs/carbon/blob/master/lib/constants.js#L15) in rgb( ) and use this to override the style set by CodeMirror.

**Comment by vernondegoede** [comment]
I opened a PR for a theme which comes with vibrancy support: https://github.com/dawnlabs/carbon/pull/341. It's based on the Verminal, a Hyper theme (which is in the second image) and Framer Syntax.

Hope you like it! 🎉

**Comment by kissu** [comment]
@jakedex super cool idea ! :tada:

**Comment by mfix22** [comment]
Closing since seems Verminal is covering the use case 👍
