### ISSUE TITLE
don't support python 3?

### ISSUE THREAD

**Issue by mangosuch** [dawnlabs/carbon#125]
## Actual Behavior

**Comment by yeskunall** [comment]
Carbon simply uses [CodeMirror](http://codemirror.com/) themes. If Python 3 is not supported out of the box, then you should probably open up an issue over at their [forums](https://discuss.codemirror.net/).

**PS**: Screenshots would help.

**Comment by mfix22** [comment]
Thanks for the issue! Please use `python` mode: 
![carbon](https://user-images.githubusercontent.com/8397708/32410088-1d4976a2-c176-11e7-97e6-6bae04208e94.png)
