### ISSUE TITLE
Should it save the background color to the PNG?

### ISSUE THREAD

**Issue by photonstorm** [dawnlabs/carbon#130]
## Expected Behavior

Not sure, but I think it's supposed to save the background color behind the code snippet block? Currently, it doesn't for me. I've tried in Chrome (latest stable), Canary and Firefox (latest stable), all on Windows 10, and they all save the background as transparent, no matter which color is picked.

![carbon 1](https://user-images.githubusercontent.com/164476/32178170-fdb444fc-bd83-11e7-824d-e2362b05741c.png)

I've tried clearing all site data, dev tools open (cache disabled), etc. But it always saves transparent.

Also, the images are always 1548px wide, no matter if the 'Width adjustment' is ticked or not in the settings. It displays correctly on the website, but when you hit 'Save Image' the png is 1548px wide, with lots of transparent space on either side of the code block.

## Actual Behavior

I'd have thought the color should be included. If it's not meant to be, then no worries!

I see from your https://twitter.com/dawn_noreply twitter feed that none of the images there have background colors either unless you scroll back to October 25th and before.

**Comment by briandennis** [comment]
@photonstorm thanks for catching this! Should be fixed now. Please let me know if you're still having trouble 😀

**Comment by photonstorm** [comment]
Excellent, that fixed both the background color and the width issue :)
