### ISSUE TITLE
Max-width window option

### ISSUE THREAD

**Issue by thmnmlist** [dawnlabs/carbon#135]
A max width option would be pretty useful to prevent extremely wide images for single line and long codes

**Comment by mfix22** [comment]
Thanks for the issue? Do you want the text to wrap, or be truncated?

**Comment by thmnmlist** [comment]
@mfix22 I'm not sure about that, probably wrapped

**Comment by mfix22** [comment]
Sweet thanks @thmnmlist! Got the PR up.

**Comment by thmnmlist** [comment]
@mfix22 oh I wanted to mean an option to set window width manually in settings if possible, like:

-Window controls (on/off)
-Line numbers (on/off)
-Padding vertical
-Padding horizontal
**-"Window width: (600px)" (leave empty to fit automatically)**

"Width adjustment" option is only setting a min-width

Just an idea, I don't know about possibility or ease. I'm very sorry for the misunderstanding and taking your time, didn't make it clear enough

**Comment by mfix22** [comment]
@thmnmlist no don't apologize. I actually wanted the max-width anyways. I am not sure if we should support a customized max-width yet. The number of settings we have is growing quickly, and we want to make sure the UI remains friendly and usable (:

**Comment by drcmda** [comment]
@mfix22 that would be one of the most important settings to imo. Like, if you want to make a series of snippets, for instance like these: https://github.com/drcmda/react-contextual

It is impossible to do with now, it would look garbled as some images blow up and some are small. To do this i had to paste a blank line filled with a long series of spaces in them all. To update this once some code has to change would be a nightmare, basically re-doing everything again.

A width option would allow us to create a series of images with the same constraints.
