### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/carbon#136]
- [x] Background Color Changes
- [x] Download
- [x] Drag and Drop updates code
- [x] Gist endpoints
- [x] Local Storage
- [x] Query Params
~-  [ ] Backspacing, typing works (I know, obvious)~

**Comment by bahmutov** [comment]
Would you be interested in Cypress tests? I can make a PR and it integrates nicely with Now deploys too
- https://github.com/cypress-io/cypress
- https://www.cypress.io/blog/2017/05/30/cypress-and-immutable-deploys/

**Comment by mfix22** [comment]
Yes exactly! Cypress is definitely our best bet!!! That would be absolutely amazing.

**Comment by wuweiweiwu** [comment]
@mfix22 Are there still some tests that still needs to be done? I would love to work on it!

**Comment by mfix22** [comment]
@wuweiweiwu absolutely! We still need integrations tests for confirming the download button succeeds, and also testing Drag and drop. Tests for any of the settings would also be a bonus 😄 

That would help tremendously!

**Comment by wuweiweiwu** [comment]
@mfix22 Awesome! ill get a pr out in the next couple of days!

**Comment by wuweiweiwu** [comment]
@mfix22 Currently working on the download test but its a little weird as it creates an `a` that has the base64 dataurl but clicks and then immediately deletes it. 

I've tried synchronously querying the dom for `a` elements after I click but have been unsuccessful in finding the element since I am trying to check for its existence.

https://docs.cypress.io/guides/core-concepts/conditional-testing.html#Dynamic-Text has been unsuccessful

**Comment by mfix22** [comment]
@wuweiweiwu is there a way to confirm that the download succeeds without checking for the existence of the `a` element? I am pretty sure Cypress has a way to check for something like this.

cc @bahmutov

**Comment by wuweiweiwu** [comment]
@mfix22 I hope so

the cypress [documentation](https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-a-way-to-test-that-a-file-got-downloaded-I-want-to-test-that-a-button-click-triggers-a-download) suggesting testing the mechanism of the actual download. But that doesn't seem to be helpful in this case.

There also seems to be some cypress issues related to this https://github.com/cypress-io/cypress/issues/949

**Comment by Franky82dev** [comment]
Hi I'm new in Cypress and on Github. I am looking for a way to cut out a part of a called URL and save it in a variable that I can use elsewhere in the cypress test code. For example: `"http://something.com/The_Thing_I_need/somthing_else"`
`const needfull ='The_Thing_I_need' ;`

**Comment by mfix22** [comment]
@Franky82dev although this is outside the scope of this repo (: , you could just using normal JS variables like:
```js
const url = "http://something.com/The_Thing_I_need/somthing_else"

const extract = s => {
  const m = /http:\/\/something\.com\/(.+)\/somthing_else/.exec(s)
  return m && m[1]
}

const extracted = extract(url) // "The_Thing_I_need"
```

or 

```js
const url = "http://something.com/The_Thing_I_need/somthing_else"

const extract = s => s.split("//")[1].split('/')[1]

const extracted = extract(url) // "The_Thing_I_need"
```

**Comment by mfix22** [comment]
I'm closing this and will open a new one for a new test of integration tests.
