### ISSUE TITLE
Fix URL encoding issue

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/carbon#137]
This python snippet doesn't save since `%05` represented a URL encoded character which breaks `dom-to-image`

```python
for linenumbercount, filename in loclist: 
    print "%05d lines in %s" % (linenumbercount, filename)
```

Possible solutions: 
- [ ] find a way to escape the encoding for this pattern
- [ ] remove patterns like these from the code before saving

**Comment by bmoeskau** [comment]
Related, the `+` char does not appear to get encoded properly. E.g. the code `a + b` after save becomes `a   b`. The url contains `code=a%20+%20b` but the `+` should have been encoded. Changing the url to `code=a%20%2B%20b` manually works as expected.

**Comment by Androbin** [comment]
Has #230 solved this?
