### ISSUE TITLE
Support Base16 Mocha theme

### ISSUE THREAD

**Issue by lukechilds** [dawnlabs/carbon#152]
Are you interested in supporting this?

If so I'm happy to submit a PR.

**Comment by jakedex** [comment]
Yeah! Looking forward to your PR 👍

**Comment by lukechilds** [comment]
Sweet, very busy atm but will do when I can spare some time.

**Comment by mfix22** [comment]
Hey @lukechilds any updates on this? (: We have a big release coming up and would love to include this. 

If not, one of us can submit a PR.

**Comment by lukechilds** [comment]
I'm still happy to do it but unfortunately I wont have time for at least the next two months.

**Comment by mfix22** [comment]
Hey @lukechilds. As of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon! #181). We are happy to accept your PR when you have the time, though!

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄
