### ISSUE TITLE
Save image with a higher quality for printing

### ISSUE THREAD

**Issue by jamesxv7** [dawnlabs/carbon#158]
I love this project. I just want to know if it is possible to have the option to save the snippet image with a higher dpi, like for example 300, just in case you want to use it in a book or magazine for printing or a high quality pdf?

**Comment by mfix22** [comment]
First of all, thank you. We are honored that you want to use these images outside the web! 

I am not sure how we can increase the dpi at this point, although there might be some fine tuning we can do with `dom-to-image`.

If you want to mess with it, the code that currently does the tweaking to get the images to their current quality is here: https://github.com/dawnlabs/carbon/blob/master/pages/editor.js#L99-L112

**Comment by briandennis** [comment]
This is equivalent to making the image higher resolution, so we'll track it at #112
