### ISSUE TITLE
[Suggestion] Mention about the gist feature on the webpage

### ISSUE THREAD

**Issue by itaditya** [dawnlabs/carbon#160]
As I directly got to website I had no clue that I can directly add gists also. There should be a mention about this on the webpage not only in the README

**Comment by jakedex** [comment]
It's mentioned on the website here, under 'Import': https://carbon.now.sh/about

**Comment by itaditya** [comment]
That's easy to miss, I think such a killer feature should be in the spotlight

**Comment by mfix22** [comment]
Hey @jakedex do you think we should add a little pop-out/up modal/drawer that has all the carbon tips and tricks? Maybe like a little ❔ button? I like Slack's drawer, and maybe we can copy the `Cmd + /` to open it
