### ISSUE TITLE
[Request] Please mention my CLI tool

### ISSUE THREAD

**Issue by itaditya** [dawnlabs/carbon#161]
Hi, thanks for bringing this wonderful utility to life. I wanted to contribute to this. For that I have made a CLI tool to easily generate snippet of a local file.

You can take a look at [npm](https://www.npmjs.com/package/carbon-cli)

Github source code at https://github.com/itaditya/carbon-cli

It would be really great if you could people to my CLI so that they can take full advantage of Carbon. 
Thanks in advance

**Comment by mfix22** [comment]
Hey @itaditya very cool!
I just installed it and ran `carbon --file next.config.js` and nothing happened. I think it is because you need to add a `path.resolve(process.cwd(), file)` 😄

**Comment by mfix22** [comment]
Also if it is alright, I am going to close this issue since I already see your comment over at #52 (:

**Comment by itaditya** [comment]
thanks @mfix22

**Comment by itaditya** [comment]
@mfix22 thanks to you the bug got fixed in time :smile:
