### ISSUE TITLE
Make a single pixel slightly translucent for optimal Twitter image quality

### ISSUE THREAD

**Issue by mathiasbynens** [dawnlabs/carbon#163]
Uploading an image to Twitter decreases the quality. This does not happen for images with transparency.

How about adding an option to save the image, but with a single pixel (e.g. the top-left one) slightly translucent (`0xFE` opacity instead of `0xFF`). @kosamari built a tool for just that: https://github.com/kosamari/translucent But it would be wonderful if this was built-in to Carbon.

**Comment by jakedex** [comment]
Resolved with #104
