### ISSUE TITLE
"Tweet image" is broken for me

### ISSUE THREAD

**Issue by jugmac00** [dawnlabs/carbon#175]
## Expected Behavior
Press "Tweet image" button and either image gets tweeted or a UI pops up to finish process.

## Actual Behavior
Press "Tweet image" button
Some spinner showed up
Nothing happened

**Comment by yeskunall** [comment]
Can you make sure you don't have pop-ups disabled? 😅

**Comment by jugmac00** [comment]
Thanks for getting back to me. Gonna check this next time I use the service. Promised^^

**Comment by jugmac00** [comment]
You were right - popup issue. Works now like a charm!
