### ISSUE TITLE
Add an "Copy image to clipboard" feature?

### ISSUE THREAD

**Issue by samuelpath** [dawnlabs/carbon#177]
My most frequent use case when using carbon is to import the code snippet images in emails.

Currently, a few steps are involved.
I need to export the image on my disk, and then import it to my email.

The "copy to clipboard" feature would allow me do this in far fewer steps.

I would simple copy to clipboard and then paste to my email, and I would save a lot of time.

Would you consider adding this feature to the roadmap?

**Comment by yeskunall** [comment]
Duplicate of #49.

**Comment by mfix22** [comment]
Closing because of duplicate. Please refer to #49
