### ISSUE TITLE
Do not require opening PHP tag in order to highlight PHP code

### ISSUE THREAD

**Issue by mstnorris** [dawnlabs/carbon#184]
## Expected Behaviour
Highlight the code without requiring the opening `<?php` tag

_**The below screenshot has been edited to show desired behaviour**_

<img width="883" alt="screenshot 2018-01-31 13 41 54" src="https://user-images.githubusercontent.com/1919816/35626233-f6fbef64-068c-11e8-9cc1-d36635635b6f.png">

## Actual Behaviour
The code is only highlighted when the opening `<?php` tag is present

<img width="883" alt="screenshot 2018-01-31 13 41 53" src="https://user-images.githubusercontent.com/1919816/35626097-8e6d0f78-068c-11e8-9852-e6c1b44d76b9.png">

If it is omitted, then the code is not highlighted

<img width="889" alt="screenshot 2018-01-31 13 41 40" src="https://user-images.githubusercontent.com/1919816/35626099-8e8e4ee0-068c-11e8-9a91-0fb2babb535e.png">

**Comment by jakedex** [comment]
Hi, @mstnorris! Thanks for bringing this to our attention, I've fixed this issue in #189. It'll be rolled out in our next release 😄

**Comment by mstnorris** [comment]
Thanks @jakedex I just used it again and noticed this was fixed. Great work!
