### ISSUE TITLE
diff language?

### ISSUE THREAD

**Issue by evgenyrodionov** [dawnlabs/carbon#185]
Maybe we can add diff (or git) language? Will be very useful.

**Comment by warborn** [comment]
I can take care of this :)

**Comment by noraj** [comment]
## Diff command support

Currently, the diff format supported is the unified variation cf. https://en.wikipedia.org/wiki/Diff#Unified_format

But the normal output is not supported:

![image](https://user-images.githubusercontent.com/16578570/216089821-20e4ab98-662b-4e4e-bfb6-9c82c594a7c3.png)

![image](https://user-images.githubusercontent.com/16578570/216089889-2a9cd6e7-afe4-40a5-861e-f2e64c633cdf.png)

I suggest renaming the current diff to `Diff (unified)` and to add support for the normal diff format under the name `Diff (normal)`.

## Unified diff output broken for some theme presets

Some themes support it well, like 3024 night

![image](https://user-images.githubusercontent.com/16578570/216095912-7701b06a-f203-4331-be13-565347f4b2cc.png)

But others like One dark shows all on the same color

![image](https://user-images.githubusercontent.com/16578570/216096617-cc2519ae-ef79-4292-946d-a643c0c044f5.png)
