### ISSUE TITLE
Suggest Syntax highlighting Apache

### ISSUE THREAD

**Issue by sumnermic** [dawnlabs/carbon#186]
## Expected Behavior
Apache syntax highlighting... or auto to NGINX highlighting?
## Actual Behavior
Not the right syntax highlighting. Auto just uses the syntax highlighting used before.

**Comment by warborn** [comment]
I found this external CodeMirror mode for Apache syntax, it can be added as a custom mode, what do you think? @jakedex I can make the PR if is approved :)

It will look like this

![carbon](https://user-images.githubusercontent.com/10677789/35763492-2248d8fc-0873-11e8-9158-8dcd4411d04e.png)
