### ISSUE TITLE
Support Tron theme...

### ISSUE THREAD

**Issue by eswat2** [dawnlabs/carbon#188]
https://atom.io/themes/tron-legacy-theme

**Comment by briandennis** [comment]
Currently we only support adding themes that come bundled with Codemirror. You can find their list of available themes [here](https://codemirror.net/theme/) (unfortunately Tron isn't included). If you're able to get Tron into Codemirror, I'll be happy to add it!

**Comment by noudadrichem** [comment]
How can I add a theme to code mirror?
