### ISSUE TITLE
Escape variables before embedding them in html

### ISSUE THREAD

**Issue by ChALkeR** [dawnlabs/carbon#192]
![screenshot_20180203_204801](https://user-images.githubusercontent.com/291301/35769943-2abd7e1e-0924-11e8-945a-baef5a703950.png)

## Expected Behavior
Variables escaped when building html.

## Actual Behavior
Variables not escaped and concatenated with html as-is, allowing script execution.

## Note
Due to the nature of this service, I do not think that this currently poses a security issue — there is no storage, session, or private user data involved. Thus reporting to the publlic tracker.

This is still a bad example, though.

**Comment by ChALkeR** [comment]
Guess that's the code:
https://github.com/dawnlabs/carbon/blob/master/components/BackgroundSelect.js#L77-L119

**Comment by mfix22** [comment]
@ChALkeR thanks so much! That's a little embarrassing (:

**Comment by ChALkeR** [comment]
@mfix22 I don't think it fixes it.

**Comment by ChALkeR** [comment]
![screenshot_20180204_022947](https://user-images.githubusercontent.com/291301/35772575-463f1718-0953-11e8-8002-0e9a8fe4440f.png)

![screenshot_20180204_022751](https://user-images.githubusercontent.com/291301/35772561-014908da-0953-11e8-860a-ce5dbf24d4e3.png)

**Comment by mfix22** [comment]
@ChALkeR we haven't released yet, but i'll reopen so you can verify when we do 😄

**Comment by ChALkeR** [comment]
@mfix22 I expect the lines on the two screenshots above in https://github.com/dawnlabs/carbon/issues/192#issuecomment-362865664 to still work even after 5b89454  will be deployed.

Correct me if I am mistaken.

**Comment by andrewda** [comment]
Can't we just `escape()` the input? And `unescape()` when we receive it in code?

**Comment by mfix22** [comment]
@ChALkeR definitely. Still working on the fix. Just pushed the escape code, and deployed. Can you verify?

**Comment by mfix22** [comment]
I think both of the cases you pointed out are fixed. Do you see any other issues @ChALkeR?
Thanks for the help by the way!

**Comment by ChALkeR** [comment]
@mfix22 The patch b44ecff6eae617ec61fe68cc67e973d1575d9b51 should prevent user-supplied content from evading from `<style>` tag (i.e. closing it and inserting arbitrary html content) in that specific place. I did not perform audit of the remaining code.

Note that this is still not perfect (and isn't a good example), because user content could insert arbitrary styles there (which was not what was intented), and user-supplied being able to style the page could pose security risks (in other setups, though, there is nothing to steal on this specific site :wink:).

![screenshot_20180204_072739](https://user-images.githubusercontent.com/291301/35774316-e36c2584-097c-11e8-9b7c-6da000a19ae9.png)

I suggest validating the user-supplied `bg` parameter before placing it inside `style` tag, i.e. parse it as color and then serialize back to a sanitized string.

**Comment by mfix22** [comment]
@ChALkeR totally aware of this possibility, but for my own curiosity, can you tell me why this poses a problem? Even with sanitation, users could still add arbitrary CSS via the dev-tools, no?

And thanks so much for your help. We definitely don't need a full audit (:

**Comment by ChALkeR** [comment]
@mfix22 On this site, it doesn't pose a problem. Neither does the original XSS pose a direct problem on this specific site to my knowledge (which I mentioned above). If it had — I would have reported this privately instead of opening an issue.

I just outlined some of the bad practices that could become a problem if someone used a similar approach (or directly reused code from this repo) in other projects, that do deal with users data. I estimate the probability of that as non-negligible due to the popularity of this repo :wink:.

Thanks for fixing this! :tada:

**Comment by mfix22** [comment]
@ChALkeR thanks so much for the explanation. I see the distinction between adding the styles in the dev-tools versus via a link now (:

Appreciate your kind words, too 🍺
