### ISSUE TITLE
Accessibility audit and overhaul

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/carbon#194]
- [x] Close #154 
- [x] header role="banner"
- [x] nav role="navigation"
- [x] main role="main"
- [x] footer role="contentinfo"
- [x] html lang="en"
- [x] Highlight settings components on focus

**Comment by jakedex** [comment]
https://a11yproject.com/checklist

**Comment by mfix22** [comment]
Our next release: <img width="668" alt="screenshot 2018-02-05 18 41 53" src="https://user-images.githubusercontent.com/8397708/35839490-876dc0e2-0aa5-11e8-9fa5-55c9db948b65.png">

**Comment by mfix22** [comment]
Closing for now. Will open another one for our next internal audit.
