### ISSUE TITLE
Tweet button not working

### ISSUE THREAD

**Issue by JiDai** [dawnlabs/carbon#197]
Hi,

I am on last version of safari.

## Expected Behavior
The 'tweet  image'  button open a tweet

## Actual Behavior
The 'tweet  image' button do nothing (after a short loading state)
I got an error in JS console

**Comment by mfix22** [comment]
This is a duplicate of #28. Unfortunately our app does not work on Safari yet. It is our highest priority and we are working on it.

Closing.

**Comment by JiDai** [comment]
Ok, thanks
