### ISSUE TITLE
Feature request: Save as Vector / PDF

### ISSUE THREAD

**Issue by martinfrancois** [dawnlabs/carbon#198]
I really like the way the code is rendered, but I'm a bit hesitant to include just a picture, because the code inside the image cannot be copied by others. I think it would be great if there was a possibility to download it as an SVG file or even a PDF.

**Comment by l-marchesi** [comment]
I'm interested in the PDF export too.

**Comment by RationalCoding** [comment]
SVG would allow embedding this in READMEs without sacrificing text selection.

**Comment by mfix22** [comment]
@RationalCoding this is in Progress at #199 😄
