### ISSUE TITLE
"Save Image" option is not working in Firefox

### ISSUE THREAD

**Issue by micnic** [dawnlabs/carbon#20]
As the title says, when click on `Save Image` button in Firefox nothing happens.

**Comment by nozzlegear** [comment]
Also does not work in Edge (neither does the `Tweet Image` button).

**Comment by briandennis** [comment]
@micnic I pushed a fix, it should be working on Firefox now.

@nozzlegear Is the `Save Image` button working on Edge now? I can check myself later today, but don't have access to Edge at the moment...

**Comment by micnic** [comment]
@briandennis, thanks it works fine, you are awesome !

**Comment by briandennis** [comment]
@micnic glad I could help!

**Comment by briandennis** [comment]
Going to close this. Will reopen another issue if the problem on Edge persists

**Comment by nozzlegear** [comment]
@briandennis I've done some investigating with Edge and it looks like the `dom-to-image` package isn't tested in and doesn't support Edge (or Safari I guess): https://github.com/tsayen/dom-to-image/issues/78. Specifically the `.toPng` function fails with Edge complaining that the canvas is dirty. 

I switched out `.toPng()` with `.toSvg()` which got me further, the browser was able to create the data URL. However I was unable to actually navigate to that data URL, download it or even just copy it to my clipboard to navigate there manually. It would just crash Edge instead. 

Not sure how much work you want to put into this issue, it's probably just easier to add a note that Carbon doesn't support Edge!

**Comment by mfix22** [comment]
@nozzlegear thanks so much for investigating. We plan to replace `dom-to-image` with a cross-browser solution. We really appreciate the work you did.

**Comment by nozzlegear** [comment]
No problem! Looking forward to a cross browser Carbon.

**Comment by mfix22** [comment]
@nozzlegear opened #28 so you can track it (:
