### ISSUE TITLE
Unhandled Promise rejection while saving image

### ISSUE THREAD

**Issue by sbimochan** [dawnlabs/carbon#201]
## Expected Behavior
save image

## Actual Behavior
![screen shot 2018-02-05 at 12 31 05 pm](https://user-images.githubusercontent.com/11685953/35791518-8f0ee612-0a70-11e8-9b58-c5944446db4d.jpg)

**Comment by mfix22** [comment]
This occurs in Safari. Closing as it is a duplicate of #28.
