### ISSUE TITLE
Update material synstax

### ISSUE THREAD

**Issue by equinusocio** [dawnlabs/carbon#202]
Hi, i'm the author of the material color scheme. The scheme was updated time ago and the current one is totally differents from the carbon one. You can find the new material syntax here https://github.com/equinusocio/vsc-material-theme since the sublime text version is deprecated.

## Expected Behavior
![screen shot 2018-02-05 at 14 15 06](https://user-images.githubusercontent.com/10454741/35806231-175bdd32-0a7f-11e8-9d95-d07134b67586.png)

## Actual Behavior
![screen shot 2018-02-05 at 14 15 37](https://user-images.githubusercontent.com/10454741/35806234-1a8d328a-0a7f-11e8-9151-833c67e27d35.png)

**Comment by mfix22** [comment]
- [ ] We most likely need to bump the version we are getting from the CDN

**Comment by mfix22** [comment]
@equinusocio is the Material theme updated in Codemirror? We depend on the CodeMirror cloudflare CDN (cdnjs.cloudflare.com/ajax/libs/codemirror) and we are on the latest version for these themes (I believe)?

Let me know if Material has a newer Codemirror version than `5.34.0` that we should use.

**Comment by equinusocio** [comment]
Mmm It was not me who put it on codemirror. You can check the latest versions (both darker, likghter and default) here if you want to update it.
https://tmtheme-editor.herokuapp.com/#!/editor/theme/Material%20Theme

**Comment by mfix22** [comment]
@equinusocio, if you want to update the version CodeMirror to the latest Material theme, we would happily accept a PR to add it into Carbon.

**Comment by equinusocio** [comment]
@mfix22 I made a PR to update the material theme colors and add the new variants.
https://github.com/codemirror/CodeMirror/pull/5980

PS: It took just one year. 😂

**Comment by mfix22** [comment]
@equinusocio epic! 🤣 Thanks for the persistence 👍
