### ISSUE TITLE
Gist loading not working

### ISSUE THREAD

**Issue by bclinkinbeard** [dawnlabs/carbon#205]
## Expected Behavior
When loading https://carbon.now.sh/dc59a390eac41af13f1da0b68a43b9d2 it should display the code from https://gist.github.com/bclinkinbeard/dc59a390eac41af13f1da0b68a43b9d2

## Actual Behavior
It displays the same default code as https://carbon.now.sh

**Comment by mfix22** [comment]
@bclinkinbeard  I was examining the same issue last night, and it is resolved this morning. I think it is due to us being rate limited by GitHub (which we currently don't have the 💸 to resolve right now 😄)

I just hit this URL and it's currently working.

**Comment by mfix22** [comment]
@bclinkinbeard This is the only check we do: https://github.com/dawnlabs/carbon/blob/master/pages/editor.js#L47-L51

If you have ideas, we would love to accept a PR 😄  (as you can see it's not the most robust method hahah)

**Comment by bclinkinbeard** [comment]
Gotcha. :) It would require some kind of persistence layer but, basically, you can make a call to the GitHub API and provide an [If-None-Matched](https://github.com/Literasee/literasee/blob/master/routes/api/requestFactory.js#L16) or Modified-Since header (-ish, from memory), and if it [hasn't changed since you last checked it](https://github.com/Literasee/literasee/blob/master/routes/api/get-project.js#L72), the request doesn't count against your quota and you just use the data you have stored. I don't realistically have time to implement that here but I implemented it in those last couple of links if anyone is interested in having a look.

Also interesting: https://express-puppeteer-starter.herokuapp.com/images/el?url=https://carbon.now.sh/cd8e815d5850be350f349ff32c9dd1f9

Update the URL in the url parameter in the URL 😂 to any Carbon URL. It's not fast (though it could be made to be), but it's fun. It returns the image itself, so you can even use it as an `img`'s `src` value. That's what [this CodePen](https://codepen.io/bclinkinbeard/pen/XZKPNP) shows.

We can even show it here: (be patient) ![](https://express-puppeteer-starter.herokuapp.com/images/el?url=https://carbon.now.sh/cd8e815d5850be350f349ff32c9dd1f9)

**Comment by mfix22** [comment]
@bclinkinbeard lol that is so awesome 🤣 

At this point, we probably won't add a persistence layer, but you are totally right. We will keep it in mind for the future.
