### ISSUE TITLE
Easy integration with remark.js

### ISSUE THREAD

**Issue by daixtrose** [dawnlabs/carbon#209]
## Idea

It would be nice, if the features of [remark.js](https://remarkjs.com/#1) and carbon could be combined, sucht that code portions are rendered by carbon instead the builtin markdown code renderer.

**Comment by mfix22** [comment]
@MadeByMike mentioned that he was working on something like this here: https://twitter.com/MikeRiethmuller/status/957770490612871168

**Comment by briandennis** [comment]
That's a cool idea! This isn't something we're going to add here, but if you get a chance to build it, we can definitely link to it in the README.

**Comment by mfix22** [comment]
Hey @daixtrose, issues marked "Integrations" are being closed and theirs discussions moved to https://github.com/dawnlabs/carbon/issues/358. With many requests for new features, this allows the Carbon team to prioritize which to support first 👍
