### ISSUE TITLE
Sublime Text Extension

### ISSUE THREAD

**Issue by valimero** [dawnlabs/carbon#212]
Is there an extension for Sublime Text ?

**Comment by mfix22** [comment]
At the moment no. There are community plugins for Atom and VS Code. If someone created one, we would happily add it to our Community section in our README.

**Comment by molnarmark** [comment]
I quickly put together this. I'll update it if people find it useful. :smile: [carbonSublime](https://github.com/molnarmark/carbonSublime)

**Comment by mfix22** [comment]
@molnarmark that's incredible! Can you make a PR to add a link to our README? Follow the same pattern VS Code and Atom are currently using (:
