### ISSUE TITLE
Chrome extention to change the code into image.

### ISSUE THREAD

**Issue by as-ajitsingh** [dawnlabs/carbon#219]
Actually, It's a feature that just came into my mind. As I write tech blogs so whenever I have to give a code snippet, I always have to go to VS Code/Atom etc to paste the code, take a snapshot and then add that snapshot to blog editor. 
It will be better If there is a chrome extension (when enabled) can detect the code in the input/text area field and replace it with a formatted image of that code.

I am also willing to work on this feature If this feature is usable.

**Comment by briandennis** [comment]
That's interesting, I could see that being useful for also just quickly creating Carbon images for code you come across when browsing the web (even if you're not writing a blog). This would probably be dependent on #210? A chrome extension isn't something we'll incorporate into the project here, but if you or anyone else gets a chance to make it, we can certainly document it in the README!

**Comment by jakedex** [comment]
I agree this would be useful - especially if you could select a bit of code on the web, and right click to create a carbon image

**Comment by mfix22** [comment]
Hey all, issues marked "Integrations" are being closed and theirs discussions moved to https://github.com/dawnlabs/carbon/issues/358. With many requests for new features, this allows the Carbon team to prioritize which to support first 👍

**Comment by mittalyashu** [comment]
@as-ajitsingh are you working on the chrome extension?
