### ISSUE TITLE
Now can not automatically get the file type

### ISSUE THREAD

**Issue by zhaoqize** [dawnlabs/carbon#223]
<img src="https://user-images.githubusercontent.com/17929687/35964158-d60eeae8-0cf1-11e8-9919-f43a933975fb.png" height="200">

> carbon version: 2.0.0

when I drop file to carbon,the editor can not get the file type.
so, change the type every time.
this may be an improve point 😄

**Comment by mfix22** [comment]
@briandennis this should only get auto-updated if they are in `Auto` syntax mode right? 

What do you think about overriding this behavior on "Drop"?

**Comment by briandennis** [comment]
Correct, that's how it's working now. But yeah, let's set the mode to `auto` if they drop in code from a file.
