### ISSUE TITLE
Upload your own code font

### ISSUE THREAD

**Issue by jameslittle230** [dawnlabs/carbon#232]
Could be cool to upload your own monospace font to be used in the output, for those who have monospace fonts that aren't available for free.

**Comment by GavinRay97** [comment]
@mfix22 
Something like this maybe? :smile: 

Video:
https://i.imgur.com/Uw3Jsj4.gifv

![](http://i.imgur.com/kpfO8P3.png)

**Comment by mfix22** [comment]
@GavinRay97 that looks great too! Can you push that up as a second PR to your custom theme's one? Also can you open up a PR for that too so that the community can see both?

**Comment by GavinRay97** [comment]
@mfix22 Awesome. I uploaded both, but I'm not sure what branch to base the PR off of.

https://github.com/GavinRay97/carbon/tree/custom-fonts
https://github.com/GavinRay97/carbon/tree/custom-themes

**Comment by mfix22** [comment]
Just released the ability to upload your own font! Will add the ability to save them to reuse later.
