### ISSUE TITLE
Add Iosevka font

### ISSUE THREAD

**Issue by wezm** [dawnlabs/carbon#233]
> Iosevka is a slender monospace sans-serif and slab-serif typeface inspired by Pragmata Pro, M+ and PF DIN Mono, designed to be the ideal font for programming.

— https://be5invis.github.io/Iosevka/

Iosevka is licensed under the SIL Open Font License v1.1

**Comment by mfix22** [comment]
@wezm is Iosevka published to a CDN? We are pulling all our other typefaces from different CDNs.

**Comment by wezm** [comment]
Maybe you can use the one on jsDelivr: https://www.jsdelivr.com/package/npm/@typopro/web-iosevka

**Comment by wezm** [comment]
Wonderful, thank you.
