### ISSUE TITLE
Support for Nord Color Scheme

### ISSUE THREAD

**Issue by TimoSta** [dawnlabs/carbon#235]
Is there any interest in adding support for the [Nord](https://github.com/arcticicestudio/nord) color scheme?

If so, I might be able to send a PR over the next few days.

**Comment by SirivanSuwamnawong** [comment]
Yes

**Comment by mfix22** [comment]
@TimoSta looking forward to your PR.

**Comment by mfix22** [comment]
Hey, @TimoSta, as of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon, see #181)! We are still happy to accept your PR though!

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄
