### ISSUE TITLE
Enhanced Carbon CLI

### ISSUE THREAD

**Issue by molnarmark** [dawnlabs/carbon#240]
I've seen the CLI over at [npm](https://www.npmjs.com/package/carbon-cli) and at [#161](https://github.com/dawnlabs/carbon/issues/161), and I was thinking about making a bit enhanced version of it that would support more than 500 characters by combining multiple images together. 

It would also use the proposal mentioned over at [#52](https://github.com/dawnlabs/carbon/issues/52).

If people are interested in this I'd be more than welcome to create this.

**Comment by molnarmark** [comment]
Can we somehow overcome the issue with the 500 character limit? I understand that its due to the parameters and the code going in as a query string, it was probably mentioned before and I'm late in the party, but would it be possible to have a POST request *also* handing this? 

The CLI will be able to combine multiple Carbon images together, thus making more requests to the server, so I guess it would be worth it for the long run.

@mfix22 @jakedex @briandennis

**Comment by mfix22** [comment]
Hey @molnarmark sorry about getting to this so late. What limit do you see as appropriate? There is definitely room to increase it.

As for creating a CLI, we would be happy to add it to our **Community* section of our README if you created one 😄

**Comment by molnarmark** [comment]
Since Carbon currently has the 500 character limit, it pretty much renders it useless when used with an external call to the website. My proposal would definitely involve the average lines of code per file, which would be < 500. I believe that getting anywhere close to 500 lines in a file should not happen (except for HTML and CSS).

This would definitely adjust the experience when Carbon is used via a plugin.

One thing I'd definitely be happy to implement is an API for this, that works via POST requests and keeps track of N requests per day tied to the IP address, or an API key.

**Comment by mfix22** [comment]
> Since Carbon currently has the 500 character limit, it pretty much renders it useless when used with an external call to the website

What does seem like a more reasonable limit for you?

**Comment by molnarmark** [comment]
The Carbon.js component file contains 8415 characters. Somewhere around ~10.000 opens up a whole new dimension of usability with source code containing ~400 lines. I'm not sure if the query parameters have any sort of limitation though.

**Comment by mfix22** [comment]
@molnarmark where do you find these limitations? If you build a better CLI implementation, we would be happy to endorse it on our README and such, and also if you run into constraints we can also accept PRs to enable these integrations.

**Comment by mfix22** [comment]
@molnarmark we are going to close this just because we already have #52 and we are going to be moving integration requests to their own place soon 😄 

Still would love to see someone contribute a robust CLI tool
