### ISSUE TITLE
Square background

### ISSUE THREAD

**Issue by besasam** [dawnlabs/carbon#241]
It would be great if there was a setting to give the editor a square background, for sharing on Instagram.
Could probably be done by adjusting the paddings upon resizing so that a square aspect ratio is maintained.

~~Tried doing it myself but I suck at React so I gave up lol~~

**Comment by molnarmark** [comment]
I've just implemented this, if @briandennis or any other core maintainer thinks its a good idea to have this as an option, I'll open a PR.

**Comment by briandennis** [comment]
Sounds good to me! @molnarmark your solution looks good, though we'd probably want this in the advanced section of the menu. Would happily accept a PR for this 👍

**Comment by molnarmark** [comment]
#250 Opened.
