### ISSUE TITLE
Does not accept any files or text in Palemoon browser

### ISSUE THREAD

**Issue by tytower** [dawnlabs/carbon#245]
## Actual Behavior

**Comment by mfix22** [comment]
Duplicate of #28

**Comment by tytower** [comment]
Running through closing issues all over the place but not actually fixing anything . What the heck do you think you are doing ?
The questions are placed looking for fixes not closed stamps . Did they give you that stamp in Kindergarten?

**Comment by tytower** [comment]
"Does not accept any files or text in Palemoon browser"

**Comment by mfix22** [comment]
Hey @tytower thanks for you comments. We haven't released our fix for Safari support, but I will test if on Palemoon and try and mimick that support there.
