### ISSUE TITLE
Importing from GET/POST

### ISSUE THREAD

**Issue by oskarkrawczyk** [dawnlabs/carbon#249]
Was looking into integrating Carbon inside of @jsfiddle in some form, but I'd need to be able to pass code in a `GET` (base64-ed, just in case) or `POST` param.

Any chance this could be integrated?

Also, congrats on the great little tool!

**Comment by mfix22** [comment]
Thanks for the issue and the kind words! I am going to lump this issue in with #210 (Carbon as an API) since that is basically what you are asking for 😄
