### ISSUE TITLE
Add Windows theme

### ISSUE THREAD

**Issue by gregwhitworth** [dawnlabs/carbon#25]
I know many devs don't think of Windows but it would be nice to have Windows represented here rather than the assumption that the UI will be OSX.

**Comment by noformnocontent** [comment]
general choice of window-borders:

- Win 10
- Win 95
- Win 3.1
- MacOS X (every release?)
- MacOS Classic
- AmigaOS
- Gnome
- KDE
- DOS / ASCII
- ChromeOS / Chrome tab

**Comment by pa7ryk** [comment]
I will make a few of them but I don't know how to show available options in settings.
At the moment theme section is already big enough. How should it looks like with more than 3 themes?

**Comment by netoguimaraes** [comment]
up.

@pa7ryk, what themes are you implementing? I want to implement some of these.

**Comment by pa7ryk** [comment]
@noformnocontent 
I have already done Win10. Now I'm working on Gnome and trying to solve settings problem.

**Comment by jakedex** [comment]
![screen shot 2017-10-23 at 1 41 49 pm](https://user-images.githubusercontent.com/10369094/31912305-47fa1be0-b7f8-11e7-803e-0517d095a862.png)

I think we could either add a horizontal scroll to the current window settings (see above image) or add a 'see more' button that expands to a grid of window theme thumbnails.

Either way, I'm happy to create the thumbnail SVGs and help with any design/UX work.

**Comment by gregwhitworth** [comment]
Do you have any telemetry regarding the buttons? Because I'm curious if showing three separate MacOS themes by default is necessary. You could have MacOS, Windows10, Next popular theme then the show more option denoted above?

**Comment by MaxInertia** [comment]
Just came across this project, love it! 

The first two window themes on the [currently hosted version](https://carbon.now.sh/?bg=rgba(139,29,29,1)&t=base16-dark&wt=none&l=text&#x2F;apache&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Monoid&fs=14px&si=false&es=2x&wm=false) are identical. Couldn't one of them be replaced with the windows theme?

![image](https://user-images.githubusercontent.com/12981415/38910910-74430a62-4291-11e8-8ad0-465397806468.png)

Extra space would allow greater flexibility in the number of themes you have available, what about adding a new drop-down specifically for these themes?  

**BG** | **W** | **⚙**

**Comment by evaryont** [comment]
I'd very much appreciate a Gnome 3/Adwaita theme for the borders!

**Comment by mittalyashu** [comment]
I prefer to use OSX only.
