### ISSUE TITLE
Add Title

### ISSUE THREAD

**Issue by BLamy** [dawnlabs/carbon#254]
It would be nice if there was an ability to add a title to your code similar to this.

![image](https://user-images.githubusercontent.com/324928/36494156-47b6226c-16ff-11e8-996f-a78713ef0523.png)

**Comment by molnarmark** [comment]
I'd be happy to implement this if needed!

**Comment by KINGSABRI** [comment]
A title, or file name

**Comment by jakedex** [comment]
I really like this idea! If you could implement @molnarmark, that'd be awesome. Maybe make the font-size a bit smaller, like the example below. 

![example](https://user-images.githubusercontent.com/10369094/36510867-27d79612-172a-11e8-9ebb-86df8cdd8617.png)

**Comment by molnarmark** [comment]
What would be a good way to do this? Have an invisible input box at the top? I was thinking about adding it to the settings dropdown but it really doesn't belong there.

**Comment by jakedex** [comment]
Yeah, let's throw an invisible input box at the top for now. We'll have to add some more UX cues down the road.

**Comment by molnarmark** [comment]
I'm gonna add this and submit a PR soon in the next couple of days. 👍

**Comment by molnarmark** [comment]
#257 was merged. 😄

**Comment by mallamzamaani1** [comment]
This is Mallam I am a powerful spritual man who help people  u can whatsapp me now or call me now (+233546805897) ,for help like, 
1.Schooling
2.Riches
3.Instant money 
4.business improvement 
5.Child birth
6.Lotto numbers 
7.Scam powers 
8.protection 
All problems can be solve
