### ISSUE TITLE
Problem of Padding(vertical) setting

### ISSUE THREAD

**Issue by neo1949** [dawnlabs/carbon#267]
## Expected Behavior
I have set the vertical padding to minimum value to make the whole page can be filled with the foreground color.

## Actual Behavior
But the saved picture still have a small area filled with bg color in the top like below.
![carbon 2](https://user-images.githubusercontent.com/20341087/36824302-92313654-1d3c-11e8-8a69-32fc91cf86bb.png)

**Comment by jakedex** [comment]
Hmm, I'm not able to reproduce this on my end. Do you mind sending me the settings you were using, @neo1949? 

![carbon 3](https://user-images.githubusercontent.com/10369094/37010954-94d99872-20b3-11e8-9274-1e38b269f1e8.png)

**Comment by neo1949** [comment]
@jakedex I have figure out why, because I did not unselect "Window controls" setting. Sorry for troubling you, please close this issue.
