### ISSUE TITLE
Add Lucario theme

### ISSUE THREAD

**Issue by raphamorim** [dawnlabs/carbon#273]
Hi everyone,

I humbly want to suggest adding [Lucario](https://github.com/raphamorim/lucario) as an optional theme. If it's interesting for you guys, I can send a PR.

Also: I love the project! :octocat:

**Comment by mfix22** [comment]
Looking forward to your PR!

**Comment by mfix22** [comment]
Hey @raphamorim any updates on this? We have a big release coming up and would love to include this 😄. If not, maybe one the the maintainers can submit a PR instead.

**Comment by raphamorim** [comment]
Hi @mfix22! happy to hear it :)
I already sent the PR, but it's still missing review: https://github.com/codemirror/CodeMirror/pull/5294

**Comment by raphamorim** [comment]
Just merged! Codemirror now have Lucario as theme option 🥂 -> https://github.com/codemirror/CodeMirror/blob/master/theme/lucario.css

I'll send the PR to Carbon til' end of the day.
