### ISSUE TITLE
Some sort of runtime and/or static type checking 

### ISSUE THREAD

**Issue by wuweiweiwu** [dawnlabs/carbon#275]
via `prop-types` and/or `flow`

I think this would make development a lot easier :)

**Comment by mfix22** [comment]
@wuweiweiwu `prop-types` would definitely be beneficial, but we don't want to add TypeScript or Flow at this point.

Are you interested in submitting a PR for this?

**Comment by wuweiweiwu** [comment]
@mfix22 Yep! I'll get started on that:)

**Comment by wuweiweiwu** [comment]
@mfix22 sounds good! Thanks for letting me know!

**Comment by mfix22** [comment]
At this state, with component APIs in flux, we want to avoid prop-types for now. We did just add legit linting though, so I hope that helps
