### ISSUE TITLE
Making save image work in all browsers

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/carbon#28]
To start:
- [ ] Safari
- [x] Edge

**Comment by mfix22** [comment]
> @elrumordelaluz: Probably related on #28. 
Investigating, seems that the problem is that [`dom-to-image`](https://github.com/tsayen/dom-to-image) doesn't [support Safari](https://github.com/tsayen/dom-to-image#browsers) because:

>it uses a stricter security model on <foreignObject> tag. Suggested workaround is to use toSvg and render on the server.`

**Comment by blazeu** [comment]
https://github.com/niklasvh/html2canvas works in Edge.

**Comment by mergesort** [comment]
I'd like to make a request for Safari support. I just stumbled upon your wonderful tool, plan on using it quite a bit, and use Safari as my primary browser.

Thank you so much!

**Comment by tytower** [comment]
https://github.com/dawnlabs/carbon/issues/245
OK thats closed that issue so what is the fix?
How can i use this editor ?

**Comment by elrumordelaluz** [comment]
@tytower meanwhile this _Issue_ is open, could you please use the _App_ with _Chrome_ or _Firefox_ browsers?

**Comment by alvaropinot** [comment]
![screen shot 2018-03-02 at 13 56 22](https://user-images.githubusercontent.com/6654199/36916389-bcd1f84a-1e21-11e8-91cf-4de664934d01.png)

Looks like is still not possible to type

**Comment by tytower** [comment]
"Does not accept any files or text in Palemoon browser"

I use Palemoon . I don't want to use other browsers Why is it doing this in Palemoon?

**Comment by alvaropinot** [comment]
@tytower can you please share the user agent for "Pale Moon"?

**Comment by SirWindfield** [comment]
It's not the world to download another browser and use it for just this site if you really want that image. You can even run it on localhost instead of pinging the deploy site.

**Comment by briandennis** [comment]
@tytower The purpose of this issue was to track progress on browser support that the core team is working on and we're limiting our support commitment to major browsers. Sorry for the confusion here, I updated the issue title to better reflect this.

While we don't have the resources to support all alternative browsers, if you or anyone else are able to solve the problem I'd be happy to review a PR that fixes the app in Pale Moon!

**Comment by alvaropinot** [comment]
I'm still having issues in Safari, the colours are not preserved and the text is just white, probably a problem inside the backend fallback for Safari. 😅

**Comment by dbalabka** [comment]
Problem still here. Cursor isn’t visible

**Comment by dbalabka** [comment]
It is strange because everything works using the same CodeMirror editor on following demo page:
https://codemirror.net/

**Comment by dbalabka** [comment]
> Problem still here. Cursor isn’t visible in iOS Safari

It was incorrect. Carbon works on iOS safari, but cursor isn’t visible on iOS Chrome.
