### ISSUE TITLE
Some queries are not used.

### ISSUE THREAD

**Issue by SirWindfield** [dawnlabs/carbon#284]
I just noticed that some query parameters are not working, even though they are defined [here](https://github.com/dawnlabs/carbon/blob/7fce4060f04728630cc3dde5ed5627f4c0edd1ee/lib/routing.js#L20).
## Expected Behavior
Queries like `fs`, `fm`, `wt` `es` and `si` should alter the result.

## Actual Behavior
They do not.

**Comment by DeepSpace2** [comment]
Hi.
I'm not sure that "bug" is the correct term. I believe that the master branch has not been deployed since these changes were made. When running carbon locally these parameters are working.

**Comment by SirWindfield** [comment]
I didn't check locally. I was just assuming that the guys from dawnlabs would actually deploy on every change :smile:

**Comment by mfix22** [comment]
Right, we haven't deployed in quite awhile. New major release is coming soon, so that is why there is delay. 

Thanks for checking that out @SirWindfield
