### ISSUE TITLE
Deploying using the now button does not work

### ISSUE THREAD

**Issue by SirWindfield** [dawnlabs/carbon#286]
I just tried it out. I created a new token and pasted it into the field, htting deploy afterwards. The webpage tells me `Deploy failed, please check the repo and try again.`. It worked for the test repository `https://deploy.now.sh/?repo=https://github.com/zpnk/hello-world` that was linked on the same page with the same token I tried out earlier.

Deploying using Docker didn't work either.

**Comment by mfix22** [comment]
Hey @SirWindfield 

Be sure to specify all of these environment variables as part of the deploy:
```
    "env": {
      "TWITTER_CONSUMER_KEY": "@twitter-consumer-key",
      "TWITTER_CONSUMER_SECRET": "@twitter-consumer-secret",
      "TWITTER_ACCESS_TOKEN_KEY": "@twitter-access-token-key",
      "TWITTER_ACCESS_TOKEN_SECRET": "@twitter-access-token-secret",
      "LOGS_SECRET_PREFIX": "@logs_secret_prefix"
    }
```

I just updated the button such that you are now required to enter them during the deployment. 

Also be sure to check the `[ ] Build using Docker` button.

I am going to close this for now. Please let me know if you run into other issues. 😄
