### ISSUE TITLE
Feature Request - File Title

### ISSUE THREAD

**Issue by cgathergood** [dawnlabs/carbon#288]
It'd be great to have an optional file title horizontally aligned with the buttons at the top of the screen.
Love the product, thanks!

**Comment by molnarmark** [comment]
This is done by #257.

**Comment by SirWindfield** [comment]
@molnarmark How does the deploy cycle of carbon work? I saw that the update for Safari has been pushed to master but the website has not been updated. Do you have some sort of milestone system or anything in particular?

**Comment by molnarmark** [comment]
I've made some contributons that are not yet live as of now aswell, i think they collect quite a few updates before pushing to production.

@briandennis will be able to answer you clearly though.

**Comment by mfix22** [comment]
Hey @molnarmark and @SirWindfield. We are having a slower release cycle this time since we have a lot of new features going in. We don't really have a standard practice, and usually will redeploy on every PR merged
