### ISSUE TITLE
wrong monokai?

### ISSUE THREAD

**Issue by noformnocontent** [dawnlabs/carbon#29]
![wrong-monokai](https://user-images.githubusercontent.com/23745012/30832040-fdbb55ee-a249-11e7-956b-d7597ec401a8.jpg)

**Comment by mfix22** [comment]
Haha, it  is the right monokai, [the CDN that our themes are deployed to](https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.30.0/theme/monokai.min.css) just uses a theme that highlights different parts for each color. 

You can add themes to `lib/constants` that are available in [CodeMirror](https://codemirror.net/).

For now, we will leave the current Monokai. Closing
