### ISSUE TITLE
Cannot tweet or save

### ISSUE THREAD

**Issue by marcpalmer** [dawnlabs/carbon#296]
## Expected Behavior

Save Image or Tweet Image should work

## Actual Behavior

JS console shows errors about promises.

I'm using Safari 11.0.2
<img width="1282" alt="screen shot 2018-03-22 at 12 22 41" src="https://user-images.githubusercontent.com/40849/37770268-c02d836a-2dcb-11e8-88be-291b1ecddee6.png">

**Comment by SirWindfield** [comment]
Pretty sure Safari (OS X) isn't supported for now. They pushed some code changes for making it work some days ago. I tested them by running on localhost and got it working. Just wait a bit till it gets deployed to production :)

**Comment by mfix22** [comment]
Next release Safari will be good to go! Shouldn't have to wait too much longer!
