### ISSUE TITLE
Feature request: add nova theme

### ISSUE THREAD

**Issue by trevordmiller** [dawnlabs/carbon#297]
It would be sweet if Nova was added:
https://trevordmiller.com/projects/nova

There is an npm module with the colors:
https://www.npmjs.com/package/nova-colors

**Comment by mfix22** [comment]
Hey @trevordmiller the core Carbon team won't be implementing new themes ourselves at the moment, but we would happily accept PRs for new themes from contributors! 👍

**Comment by trevordmiller** [comment]
Ok cool, I’ll see if I can put together a PR :)

**Comment by trevordmiller** [comment]
I started adding Nova to a fork, then realized the themes are an alias to Code Mirror themes:

`//cdnjs.cloudflare.com/ajax/libs/codemirror/5.36.0/theme/${theme.id}.min.css`

So looks like Code Mirror needs support first. Closing for now.

**Comment by briandennis** [comment]
Hey @trevordmiller, if you're able to port Nova to the Code Mirror theme format (which just requires setting a bunch of Code Mirror specific CSS classes), we can definitely add in a custom file and load that without waiting for it to be pulled into Code Mirror proper. We're already doing this for a few syntax modes that Code Mirror doesn't directly support.  Happy to help set that up if/when you have the theme file

**Comment by trevordmiller** [comment]
@briandennis Nova has an npm module for color values: https://www.npmjs.com/package/nova-colors

Here is an example of it being used: https://github.com/trevordmiller/nova-hyperterm/blob/master/src/index.js

**Comment by briandennis** [comment]
Perfect! If there's a version that conforms to [this](https://github.com/codemirror/CodeMirror/blob/master/theme/dracula.css) format, we can load it in 👍
