### ISSUE TITLE
Support for Spacegray color scheme

### ISSUE THREAD

**Issue by kjbrum** [dawnlabs/carbon#298]
Any possibility of getting added support for the Spacegray color scheme? http://kkga.github.io/spacegray/

**Comment by briandennis** [comment]
Looks like this theme isn't supported in Codemirror but if you want add a [custom file](https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages) for it, we'd happily pull it in!

**Comment by kjbrum** [comment]
Ahh sorry, somehow missed that section of the readme. I'll see if I can get around to it. Thanks!

**Comment by briandennis** [comment]
Sure thing, let me know if there's anything I can do to help! Also no worries, I literally just added that section to the README a few minutes ago which is why you didn't see it haha

**Comment by mfix22** [comment]
Like @briandennis mentioned, as of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon: see #181.

Still happy to accept your PR @kjbrum, but I'm going to close this issue.

**Comment by kjbrum** [comment]
Sounds good, thanks for the heads up!
