### ISSUE TITLE
Does not accept any files or text in Palemoon browser but pleased to say it does work fine in Seamonkey browser.

### ISSUE THREAD

**Issue by tytower** [dawnlabs/carbon#308]
Must be something fairly easy then! Oh and there is nothing heated about this . If an issue is not fixed leave it open so others searching will post there too and not start new issues.

The page looks good and it is definitely usable for me.

**Comment by mfix22** [comment]
Thanks for posting this, but at this time, the consensus the core team reached is that we only have the bandwidth to support major browsers. We would be happy to accept a PR if it resolves your issue.
