### ISSUE TITLE
Missing Mobile Support

### ISSUE THREAD

**Issue by ChrisBrownie55** [dawnlabs/carbon#31]
Your website is broken when used on a mobile device. By broken I am referring to the issue that when your website is viewed on a screen less than _893px_ wide, your website **does not allow horizontal scrolling** to view parts of the screen that become hidden. A simple way to fix this would be to just allow horizontal scrolling. Another fix would be to use `@media` queries to adjust for screens smaller than 893px and then again for even smaller screens. And yet another idea would be to use _percentages_ `%` or _viewport width_ `vw`

![carbon now sh-](https://user-images.githubusercontent.com/19195374/30834488-877031d6-a210-11e7-8b2a-20c6e246723c.png)

**Comment by eclecticexistential** [comment]
I found a [Github Repo](https://github.com/contra/react-responsive) that may be useful. It outlines how to add Media Queries to React.

**Comment by jakedex** [comment]
The Horizontal scrolling issue is fixed with #41. Opened new issue for responsive changes in #42

**Comment by jakedex** [comment]
Thanks for the help, @eclecticexistential @ChrisBrownie55 💫
