### ISSUE TITLE
Integration: Gatsby plugin

### ISSUE THREAD

**Issue by blackxored** [dawnlabs/carbon#312]
Hi, 
It would be great to see the components in this project to render code snippets in a Gatsby site. 
Since this is React after all I can't see why we wouldn't be able to just render these instead of prism or whatever. 👯‍♂️

**Comment by GavinRay97** [comment]
@mfix22 This would essentially be exporting just the editor as a component and then passing in a syntax theme and language correct?

**Comment by mfix22** [comment]
Right. We have published a stand-alone editor component here: https://github.com/dawnlabs/carbon-editor however it is vastly out of date. The core team is currently refactoring the editor out (#307), and once we do we will try and publish a new version of `carbon-editor`

**Comment by mfix22** [comment]
Hey all, issues marked "Integrations" are being closed and theirs discussions moved to https://github.com/dawnlabs/carbon/issues/358. With many requests for new features, this allows the Carbon team to prioritize which to support first 👍

**Comment by blackxored** [comment]
I haven’t tried that. Wasn’t even aware it existed. Thanks. 
—
Best Regards,

Adrian Perez
https://adrianperez.codes
