### ISSUE TITLE
It is a nice tool, but it doesn't work in Safari

### ISSUE THREAD

**Issue by hcontreras** [dawnlabs/carbon#32]
I tried to use _Carbon_ in Safari, but it doesn't work.

I copied and paste some code to the window, but when I press the _Save Image_ button, nothing happen.

When I tried in Chrome, worked fine!

**Comment by elrumordelaluz** [comment]
probably related on #28

**Comment by mfix22** [comment]
Thanks so much for filing an issue, and you are right, it is related to #28. Lets move the discussion to #28. Closing.
