### ISSUE TITLE
localStorage config is ignored when url contains only language and code

### ISSUE THREAD

**Issue by stevensacks** [dawnlabs/carbon#321]
I'm using 3rd party plugins in my various IDEs and they all use the above url with just language and code and they all end up causing this bug.

## Expected Behavior
http://carbon.now.sh/?l=javascript&code=const%20foo%20%3D%20%27bar%27%3B

Should open Carbon with my localStorage config for styling filled in.

## Actual Behavior
Opens the code with Carbon's default config instead of the saved config, and, as a result, overwrites the localStorage config with Carbon's default, meaning I have to manually set all my config back again.

**Comment by mfix22** [comment]
Currently if you pass a query param, localStorage will be ignored. That is operating as it is intended. 

Are you suggesting that you want parts to be loaded from that query param and others from `localStorage`?

**Comment by stevensacks** [comment]
IDE plug-ins that allow you to select code and then open in Carbon (very convenient) will only pass language and code in the URL.

I think that if you _only_ pass language and code then you should look at localStorage for the rest.

**Comment by stevensacks** [comment]
I was looking through the code to try and find the place that handles this to make a pull request, but I haven’t been able to find it yet.

**Comment by mfix22** [comment]
Although we don't want to override fields that were set by URL with `localStorage`. In your example, those fields would be overridden. 

You have to calculate the difference between `urlConfig` and `localStorageConfig` and pass that to `setState`

**Comment by stevensacks** [comment]
So that's just an order change

```javascript
{
    ...defaultConfig,
    ...localStorageConfig,
    ...urlConfig,
}
```

**Comment by stevensacks** [comment]
It could be as simple as this

```
    this.state = Object.assign(
      {
        ...DEFAULT_SETTINGS,
        uploading: false,
        code: props.content,
        ...getState(localStorage),
      },
      this.props.initialState
    )
```

And erase componentDidMount.

**Comment by mfix22** [comment]
You can't access localStorage in `getInitialProps()`

**Comment by stevensacks** [comment]
Yeah I figured it out. Really simple fix. Check my fix.

**Comment by stevensacks** [comment]
I'm not sure if there are any issues from delaying the initialState being set until mount, but it seems ok based on what I can see.

**Comment by stevensacks** [comment]
Submitted a PR.
