### ISSUE TITLE
Add support for IBM Plex Mono font

### ISSUE THREAD

**Issue by ericadamski** [dawnlabs/carbon#323]
PR is here →https://github.com/dawnlabs/carbon/pull/324

## Expected Behavior

Want to be able to choose the IBM Plex Mono font as a default in the `font selection` dropdown

## Actual Behavior

See above ⬆️ 

Here is the dev image ⬇️ 
![carbon 49](https://user-images.githubusercontent.com/6516758/38555495-546f7e1c-3c94-11e8-8ca3-31b262d6100b.png)

**Comment by briandennis** [comment]
Closing as this was added in #324
