### ISSUE TITLE
Text in generated SVG is not selectable in Chrome 65.0.3325.181

### ISSUE THREAD

**Issue by DeepSpace2** [dawnlabs/carbon#325]
I can select text in other SVGs in Chrome but not in SVGs generated by Carbon. I guess that some `-webkit` properties are missing/wrong in some/all elements (selecting text in the generated SVG is possible in Edge).

**Comment by mfix22** [comment]
We are not going to support this as of now, and is out of scope for what we are solving for. We do want to support a copyable embedded iframe of Carbon soon, which should cover this.

**Comment by DeepSpace2** [comment]
So, I took another stab at it today. The culprits are multiple `user-select` (with `auto` and `none` values) properties in inline CSS of several `<svg>` tags in the generated document. Will you be interested in a PR that remove these?

**Comment by mfix22** [comment]
@DeepSpace2 yup! As long as nothing else breaks 👍
