### ISSUE TITLE
is there a "clear" button? 

### ISSUE THREAD

**Issue by omidfi** [dawnlabs/carbon#327]
## Expected Behavior
Having a clear button to get a clean page
## Actual Behavior
I have to clear the previous code by holding back space on my phone and it crashes

**Comment by mfix22** [comment]
Are you able to select all and delete? We would rather support that behavior than to add a clear button.

**Comment by omidfi** [comment]
Thanks.

Yes that works. Even though I ended up using a desktop browser anyway as I hit another problem on my phone.
