### ISSUE TITLE
Feature request: Customizable dimensions

### ISSUE THREAD

**Issue by Math3v** [dawnlabs/carbon#33]
First of all, great idea!

I'd like to share some code on Instagram, but it requires me to share only square images.

A greate feature would be the ability to set/change dimensions of the image.

Cheers!

**Comment by mfix22** [comment]
Sweet! see issue #1 for updates on this issue

**Comment by mfix22** [comment]
We are going to track future progress for this issue at #1. In the mean time you have full control of the width and length of your code with the "Width Adjustment" setting. See PR #102
