### ISSUE TITLE
Can't save SVG when using image as background

### ISSUE THREAD

**Issue by sjfricke** [dawnlabs/carbon#330]
## Expected Behavior

I feel it shouldn't allow me to select the SVG since I am using a non-vector as my background. Edge case that needs to be taken care of

## Actual Behavior

I just get the [about:blank](about:blank) url on the page

**Comment by briandennis** [comment]
@sjfricke good catch. Wanna take care of it at your next hackathon?

**Comment by mfix22** [comment]
@briandennis this might still be the size issue . . .

**Comment by mfix22** [comment]
@sjfricke was this a random image or do you have the image to recreate the issue? We definitely want to fix this (:

**Comment by sjfricke** [comment]
@mfix22 @briandennis 
Just got dev up to poke around, first I need to quick brute force learn some react.js lol. Also are you guys currently having issues with uploading your own image? I can't seem to get my own images to load

**Comment by mfix22** [comment]
@sjfricke you're right that is a separate bug. I just fixed that with 517aca7c8f31ed098578ca2cc6c5b0710e37e7af and am deploying now. Then we can look into the `about:blank` issue

**Comment by mfix22** [comment]
Just confirmed that this is a `dataurl` overflow (the URL itself is too long to set as a valid `href`) issue,  caused it to link to `about:blank` instead.

Does anyone know a better way to download images than this: https://github.com/dawnlabs/carbon/blob/master/components/Editor.js#L136-L138

**Comment by mfix22** [comment]
@sjfricke think we could stream the `dataurl` to our server, temporarily store it as a file using `tmp`, and stream that file back to the browser? I think that is the only way to get past the `dataurl` length issue.

**Comment by sjfricke** [comment]
@mfix22 after doing some more trials I think the solution isn't using a server. The SVG actually works for images under a certain size. I think the smart solution is to make drop the resolution on large images like those in Upsplash
