### ISSUE TITLE
line overflowing not like preview in safari

### ISSUE THREAD

**Issue by LLJE** [dawnlabs/carbon#331]
## Expected Behavior
![image](https://user-images.githubusercontent.com/26544013/38766996-7c54e5fa-4015-11e8-8770-4c746d95a5c5.png)
I expected that the content is not overflowing the line.

## Actual Behavior
But, in Safari
![carbon-36](https://user-images.githubusercontent.com/26544013/38767007-990ea4d8-4015-11e8-8ec3-9396bcbb7532.png)
But, like above, it exceeds the line.
To avoid this problem, I unchecked 'auto-adjust width' option.
It works, but it cuts right side of padding.
![carbon-35](https://user-images.githubusercontent.com/26544013/38767026-d75cd5de-4015-11e8-918c-7d63e1cb566b.png)
I wish to solve this problem. 

Thank you. :)

**Comment by mfix22** [comment]
@LLJE can you post a snippet of code that reproduces this bug so I can fix it? 🙂 Thanks!
