### ISSUE TITLE
Some themes doesn't support React code

### ISSUE THREAD

**Issue by alexdevero** [dawnlabs/carbon#333]
Some parts of React code are not colored properly. Some closing tags have different color than opening tags.

## Expected Behavior
Example - Panda:
![carbon 2](https://user-images.githubusercontent.com/4237724/38811256-6112ab2c-4189-11e8-8dd1-22430d25fcab.png)

## Actual Behavior
Example - 3024 Night:
![carbon 1](https://user-images.githubusercontent.com/4237724/38811262-63d6d946-4189-11e8-995e-751ed349866c.png)

**Comment by mfix22** [comment]
Have you tried `JSX` mode?

**Comment by alexdevero** [comment]
@mfix22 Actually, no. Thanks.
