### ISSUE TITLE
Setting the resolution

### ISSUE THREAD

**Issue by IsmAbd** [dawnlabs/carbon#334]
Hey, I just found this awesome application, thanks for doing that to all!
Because some pages to have restrictions on the resolution of uploaded pictures, it would be awesome to choose the resolution of an image before downloading it.
Thanks to all!

**Comment by mfix22** [comment]
@IsmAbd we already have a feature that adjusts the size of the screenshot (1, 2, and 4 times export size). Will that work for you? 

We feel that that feature is enough for configuring the export size. You can also just edit the photos after you download them 😄
