### ISSUE TITLE
Add ReasonML syntax

### ISSUE THREAD

**Issue by blackxored** [dawnlabs/carbon#335]
I would be really nice if we could support [ReasonML](https://reasonml.github.io) syntax.

**Comment by mfix22** [comment]
Hey @blackxored, thanks for the suggestion!. As of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon!), but we are happy to accept PRs to add new ones.

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄
