### ISSUE TITLE
Box shadow size

### ISSUE THREAD

**Issue by dnlml** [dawnlabs/carbon#34]
Hello!

Thank you guys for this useful tool!
I would suggest to add an option to set the size of the box shadow.
(I will try to find the time to create the PR)

**Comment by rafaelcamaram** [comment]
I just opened a PR for it. 

If you find something that could be improved, please let me know :)

PR: [https://github.com/dawnlabs/carbon/pull/143](https://github.com/dawnlabs/carbon/pull/143)
