### ISSUE TITLE
Setting language from a gist

### ISSUE THREAD

**Issue by tdeschryver** [dawnlabs/carbon#342]
## Expected Behavior
When importing a gist, I would expect the language to be set to the gist language (which is provided in the api call as `language`).

## Actual Behavior
The language is auto detected. 
For example, the example on the website is set to `HTML` which is wrong.

If agree with this, and if you'd like I can create PR :smile:

**Comment by mfix22** [comment]
@tdeschryver if i understand correctly, currently the language is not being auto-set according to the Gist. That is definitely expected behavior. Not sure what you are referring to by API call 😄

**Comment by mfix22** [comment]
@tdeschryver also do you have an example gist link? 😀

**Comment by mfix22** [comment]
@tdeschryver whoa cool! Thanks for pointing that out. Just pushed up a PR (#343). Can you verify it works for you?

**Comment by tdeschryver** [comment]
Can't test right now, I will update tomorrow. Seems like it would work tho!

**Comment by tdeschryver** [comment]
I believe there was still a problem, see #344
