### ISSUE TITLE
Feature request: Support for terraform

### ISSUE THREAD

**Issue by fgrehm** [dawnlabs/carbon#346]
This project is great! 😃

I think a nice addition would be to support [Terraform](https://www.terraform.io/) code as well. LMK if I can help with anything.

**Comment by briandennis** [comment]
Hey @fgrehm, glad you're liking it! As of Carbon 3.0.0, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon!), but we are happy to accept PRs to add new ones!

Checkout [here](https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages) for notes on how to do so  🙂

**Comment by fgrehm** [comment]
Damn, I had a look around it seems that codemirror does not have support for it :( https://codemirror.net/mode/index.html

Unfortunately I don't have the time to work on this now so feel free to close the issue if no one signs up for giving it a shot. Thanks for the info!
