### ISSUE TITLE
Twitter not working

### ISSUE THREAD

**Issue by raphaelkieling** [dawnlabs/carbon#347]
![image](https://user-images.githubusercontent.com/16259523/39243316-6a981dcc-4863-11e8-9fe5-e27efd322f90.png)

## Expected Behavior
I clicked in the button _Twitter_ and should send an image to share in _Twitter_
## Actual Behavior
I clicked and it shows the loading... but an error appear in the console. (Screenshot show this).

**Comment by briandennis** [comment]
Thanks @raphaelkieling, can verify I'm experiencing this on my end as well. Looking into the problem now
