### ISSUE TITLE
Add line number vertical line

### ISSUE THREAD

**Issue by pakLebah** [dawnlabs/carbon#351]
## Actual Behavior

![carbon](https://user-images.githubusercontent.com/11470932/39438521-a577ebba-4cce-11e8-8412-ac1de276357f.png)

Complaint: The space between line number and the actual code is too close. On some themes, the color similarity of line number and the code is confusing.

## Expected Behavior

![carbon](https://user-images.githubusercontent.com/11470932/39438989-38326920-4cd0-11e8-990b-afb12c46d87e.png)

Suggestions: 
1. The space between line number and the code should be a little bit wider.
2. Add a vertical line to clearly distinguish line number and the code.

**Comment by DeepSpace2** [comment]
While at it, maybe make have the line optional and the padding configurable?

**Comment by mfix22** [comment]
@DeepSpace2 the line numbers are optional and the padding is currently configurable in the settings. Just click "Advanced" in the dropdown.

@jakedex what do you think about having this line next to the line numbers?

**Comment by adrianhartanto0** [comment]
can I work on adding the line next to the line numbers?

**Comment by mfix22** [comment]
Sure @adrianhartanto0! Could you add it as an option to start though, under the "Advanced Settings" menu?

**Comment by adrianhartanto0** [comment]
@mfix22 no problem. will update any progress

**Comment by adrianhartanto0** [comment]
@mfix22 Shall the vertical line be fixed to a particular color?

**Comment by mfix22** [comment]
They should be the same color as the line numbers. I am not sure if those
colors are set by the theme, or just by Codemirror itself. Either way that
is managed by Codemirror, not Carbon at the moment, so that would be the
first place to look (:

**Comment by jakedex** [comment]
Closing as stale. See #384
