### ISSUE TITLE
Add VS Code's default Dark+ and Light+ color theme

### ISSUE THREAD

**Issue by pakLebah** [dawnlabs/carbon#352]
### Expected Behavior

VS Code's default Dark+ and Light+ color theme are available on color theme option. Here's an example (with custom font setting):

![jepretan layar 2018-04-30 pada 23 49 23](https://user-images.githubusercontent.com/11470932/39439451-d1120b5e-4cd1-11e8-82b7-8f6e3a2dfcb4.png)

### Actual Behavior

There's no color themes from VS Code.

**Comment by mfix22** [comment]
Hey, thanks for the suggestion!. As of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon!), but we are happy to accept PRs to add new ones.

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄
