### ISSUE TITLE
Better(?) / seamless integration with Google Slides

### ISSUE THREAD

**Issue by pvdb** [dawnlabs/carbon#353]
I do a lot of coding challenges and level-ups for our tech team, and have used `carbon.now.sh` extensively now for adding code samples to my Google Slides presos _(I :heart: Carbon!!!)_

My workflow seems unnecessarily cumbersome, though: 

1. add code snippet to `carbon.now.sh`
1. "Save Image" > "PNG"
1. navigate to "Downloads" folder
1. drag-n-drop `carbon.png` to Google Slides

It seems like it should be possible to have a more seamless workflow in Google Slides by using "Insert" → "Image"  → "By URL", and copy-n-paste the full `carbon.now.sh` URL into the modal window, possibly by munging the URL a bit _(e.g. adding a `Content-Type` parameter somehow, or a PNG/SVG extension)_?

Is this possible already, but am I missing something totally obvious completely?

**Comment by mfix22** [comment]
Hey @pvdb thanks for the encouraging words! 😄 We appreciate you using and sharing Carbon.

Issues marked "Integrations" are being closed and theirs discussions moved to https://github.com/dawnlabs/carbon/issues/358. With many requests for new features, this allows the Carbon team to prioritize which to support first 👍

We cannot support _every_ integration, but if you were to build out this integration we would happily promote it in our README and elsewhere 🎉
