### ISSUE TITLE
Add support for GNU Make's Makefile

### ISSUE THREAD

**Issue by kaovilai** [dawnlabs/carbon#354]
👍  https://www.gnu.org/software/make/

**Comment by mfix22** [comment]
Hey, thanks for the suggestion!. As of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon!), but we are happy to accept PRs to add new ones.

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄
