### ISSUE TITLE
Exporting syntax/color themes to be used in actual editors

### ISSUE THREAD

**Issue by dimitrieh** [dawnlabs/carbon#355]
Is there a source for the themes displayed in carbon? :) 

Or might it be an idea to support directly applying the selected theme in your own editor? (atom/vscode etc)

For example would love to know about the "cobalt" theme

**Comment by mfix22** [comment]
Here https://github.com/codemirror/CodeMirror/tree/master/theme is the source for all the themes found in Carbon. A lot of these are based around real Atom/VSCode themes that are typically open source, such as this [Cobalt theme for Atom](https://github.com/wesbos/cobalt2-atom) and for [VSCode](https://github.com/wesbos/cobalt2-vscode) by @wesbos
