### ISSUE TITLE
Don't upload to Twitter without confirmation

### ISSUE THREAD

**Issue by paulmwatson** [dawnlabs/carbon#356]
## Expected Behavior
After pasting in code and clicking Tweet Image I expect to be shown a preview of the image to be added to a Tweet before it is sent to Twitter.

## Actual Behavior
After pasting in code and clicking Tweet Image the image of the code is uploaded and Tweeted out with the public @dawn_noreply account.

**Comment by mfix22** [comment]
@paulmwatson thanks for the feedback. Currently that is the only way to reliably upload an image to be tweeted on behalf of a user. If you want to circumvent this behavior, please go ahead and download the image using the "Save" button, preview it locally, and tweet it using your regular Twitter App (: 

We will add a note to our "Help Module" (#170) to help notify users in the future
