### ISSUE TITLE
Comment string goes to new line unlike the preview displays

### ISSUE THREAD

**Issue by manniL** [dawnlabs/carbon#365]
## Preview image
![oh](https://user-images.githubusercontent.com/640208/39994364-53701ab2-5779-11e8-9488-906797215da2.png)
[Link to Carbon setup](https://carbon.now.sh/?bg=rgba(155,155,155,1)&t=material&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Hack&fs=18px&si=false&code=%250A%252F*%2520Passing%2520Boolean%2520as%2520method%2520to%2520find%2520returns%2520the%250A%2520*%2520first%2520truthy%2520value%2520in%2520the%2520array!%250A%2520*%252F%250A%255Bfalse%252C%2520false%252C%2520%27%27%252C%2520undefined%252C%2520%27qwijo%27%252C%25200%255D.find(Boolean)%2520%252F%252F%2520%27qwijo%27&es=2x&wm=false)

## Outcome
![Screenshot](https://pbs.twimg.com/media/DdJz02dV4AE2FeU.png:small)

## Expected Behavior

Comment string should stay on the same line as shwon in the preview image.

## Actual Behavior

Comment string drops one line below

**Comment by briandennis** [comment]
@manniL was this on Safari?

**Comment by manniL** [comment]
@briandennis Nope, newest Firefox (59) :relaxed:

**Comment by mfix22** [comment]
@manniL can you post an example text for me to copy here? 🙂

**Comment by manniL** [comment]
@mfix22 I've linked the carbon setup in the issue :relaxed: 

```
/* Passing Boolean as method to find returns the
 * first truthy value in the array!
 */
[false, false, '', undefined, 'qwijo', 0].find(Boolean) // 'qwijo'
```

**Comment by manniL** [comment]
@mfix22 The linked config preview looks great, but when I save the image as `PNG`, it shows the same issue as before :|

Please reopen :see_no_evil: 

![carbon](https://user-images.githubusercontent.com/640208/43685041-0cd9316e-98ac-11e8-96b9-87706fb76188.png)

**Comment by mfix22** [comment]
I just opened that config in Firefox and saved it and this is the image it created: 
![carbon 2](https://user-images.githubusercontent.com/8397708/43690992-35cf2660-98c9-11e8-8ee7-d6d5661cec93.png)

Do you have you screen zoomed in/out at all? Have you tried upgrading your Firefox?

**Comment by manniL** [comment]
Still can reproduce it :sweat_smile: 

Haven't zoomed in/out. The preview is showing it right but the saved image is whyever wrong.
Using the latest firefox and `Ubuntu 18.04.1 LTS x86_64`

**Comment by mfix22** [comment]
@manniL can do me a favor? What does `navigator.userAgent` equal in your browser's console?

**Comment by mfix22** [comment]
@manniL do you think this is an issue with Firefox for Ubuntu/Linux? If so, that is outside of the scope of this projects concern 😅Please close.

**Comment by manniL** [comment]
@mfix22 Not sure if it is :thinking: 
I can't test it on FF on other devices currently :see_no_evil: It works on Chrome for Linux though.

User agent is `"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"`

**Comment by mfix22** [comment]
It's my opinion that we should close this as outside of the scope of this project 🙂It works on Firefox for Mac, and Chrome for Linux.

**Comment by manniL** [comment]
Agreed!
