### ISSUE TITLE
Add a watermark with carbon's domain

### ISSUE THREAD

**Issue by fideloper** [dawnlabs/carbon#368]
Hi!

Just a suggestion (do whatever you want with it!)

Perhaps add a watermark or text in the created image/svg of your own that just says "carbon.now.sh" (or whatever makes sense to you!)

1. Could be good marketing to help people discover what's making the amazing screenshots
2. For every tweet I make including a screenshot, I end up answering the question multiple times, all day!

**Comment by briandennis** [comment]
We currently do have [a watermark](http://carbon.now.sh/?wm=true) option available in the settings, though we could probably make that more discoverable. If I recall correctly, your use case was actually why it was added originally! 😄

**Comment by fideloper** [comment]
Haha great - thanks, I’ll use that.

Maybe add it by default! (I’m sure there are opinions both ways on that :D).
