### ISSUE TITLE
can't reach the site with 160 lines of code selected

### ISSUE THREAD

**Issue by x4m3** [dawnlabs/carbon#370]
i use the vim plugin, if that helps: <https://github.com/kristijanhusak/vim-carbon-now-sh>

## Expected Behavior

to have the site load up with the code selected.

## Actual Behavior

![screenshot from 2018-05-20 10-39-49](https://user-images.githubusercontent.com/8809909/40277125-46ccd91c-5c1a-11e8-9d0b-93a1190de2cb.png)

**Comment by mfix22** [comment]
@x4m3 can you post the exact URL here and I'll get it fixed right away!

**Comment by x4m3** [comment]
sure! there you go: <https://carbon.now.sh/?t=material&code=%252f%252a%250a%20%20%20wifi.ino%20%253a%20gestion%20du%20wifi%250a%250a%20%20%20http%253a%252f%252fpoubelle.online%250a%250a%252a%252f%250a%250a%2523include%20%253cWiFi.h%253e%250a%250avoid%20connect_wifi%2528%2529%20%257b%250a%20%20%252f%252a%20started%20wifi%20%252a%252f%250a%20%20Serial.println%2528%2522wifi%253a%20started%2522%2529%253b%250a%250a%20%20%252f%252a%20disconnect%20from%20wifi%20first%20%252a%252f%250a%20%20WiFi.disconnect%2528%2529%253b%250a%20%20Serial.println%2528%2522wifi%253a%20disconnected%2522%2529%253b%250a%250a%20%20%252f%252a%20connecting%20to%20wifi%20%252a%252f%250a%20%20WiFi.begin%2528wifi_network%252c%20wifi_password%2529%253b%250a%250a%20%20%252f%252a%20waiting%20for%20wifi%20to%20connect%20%252a%252f%250a%20%20Serial.println%2528%2522wifi%253a%20if%20you%20can%2527t%20connect%252c%20make%20sure%20the%20ssid%20and%20password%20are%20correct%252c%20the%20wifi%20router%20is%20on%252c%20and%20reboot%20the%20device%2522%2529%253b%250a%20%20Serial.print%2528%2522wifi%253a%20connecting%20to%20network%2522%2529%253b%250a%20%20while%20%2528WiFi.status%2528%2529%20%2521%253d%20WL_CONNECTED%2529%20%257b%250a%20%20%20%20delay%2528500%2529%253b%250a%20%20%20%20Serial.print%2528%2522.%2522%2529%253b%250a%20%20%257d%250a%250a%20%20%252f%252a%20success%20in%20console%20and%20display%20%252a%252f%250a%20%20Serial.println%2528%2522%20connected%2521%2522%2529%253b%250a%20%20splash_wifi_connected_text%2528%2529%253b%250a%250a%20%20%252f%252a%20display%20ip%20and%20ssid%20of%20current%20network%20%252a%252f%250a%20%20Serial.print%2528%2522wifi%253a%20ip%20address%253a%20%2522%2529%253b%250a%20%20Serial.println%2528WiFi.localIP%2528%2529%2529%253b%250a%250a%20%20Serial.print%2528%2522wifi%253a%20network%20ssid%253a%20%2522%2529%253b%250a%20%20Serial.println%2528wifi_network%2529%253b%250a%257d%250a%250avoid%20connect_server%2528%2529%20%257b%250a%20%20%252f%252a%20connection%20to%20the%20server%20%252a%252f%250a%20%20WiFiClient%20client%253b%250a%20%20if%20%2528client.connect%2528host%252c%20port%2529%2529%20%257b%250a%20%20%20%20%252f%252a%20message%20in%20console%20and%20display%20%252a%252f%250a%20%20%20%20Serial.println%2528%2522wifi%253a%20the%20following%20data%20will%20be%20sent%253a%2522%2529%253b%250a%20%20%20%20Serial.println%2528%2522%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%2522%2529%253b%250a%250a%20%20%20%20Serial.print%2528%2522masse%253a%20%2522%2529%253b%250a%20%20%20%20Serial.println%2528masse%2529%253b%250a%250a%20%20%20%20Serial.print%2528%2522matiere%253a%20%2522%2529%253b%250a%20%20%20%20Serial.println%2528matiere%2529%253b%250a%20%20%20%20Serial.println%2528%2522%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%252a%2522%2529%253b%250a%250a%20%20%20%20splash_wifi_send_text%2528%2529%253b%250a%250a%20%20%20%20%252f%252a%20start%20the%20http%20get%20request%20%252a%252f%250a%20%20%20%20client.print%2528%2522GET%20%252fphp%252fadd.php%253f%2522%2529%253b%250a%250a%20%20%20%20%252f%252a%20send%20the%20value%20of%20%2527masse%2527%20%252a%252f%250a%20%20%20%20client.print%2528%2522masse%253d%2522%2529%253b%250a%20%20%20%20client.print%2528masse%2529%253b%250a%250a%20%20%20%20%252f%252a%20separation%20for%20other%20variables%20%252a%252f%250a%20%20%20%20client.print%2528%2522%2526%2522%2529%253b%250a%250a%20%20%20%20%252f%252a%20send%20the%20value%20of%20%2522matiere%2522%250a%20%20%20%20%20%252a%201%253a%20metal%250a%20%20%20%20%20%252a%202%253a%20verre%250a%20%20%20%20%20%252a%203%253a%20plastique%250a%20%20%20%20%20%252a%204%253a%20autre%250a%20%20%20%20%20%252a%252f%250a%20%20%20%20client.print%2528%2522matiere%253d%2522%2529%253b%250a%20%20%20%20client.print%2528matiere%2529%253b%250a%250a%20%20%20%20%252f%252a%20specify%20http%20spec%20version%20%252a%252f%250a%20%20%20%20client.println%2528%2522%20HTTP%252f1.1%2522%2529%253b%250a%250a%20%20%20%20%252f%252a%20put%20the%20host%20and%20the%20port%20%252a%252f%250a%20%20%20%20client.print%2528%2522Host%253a%2522%2529%253b%250a%20%20%20%20client.print%2528host%2529%253b%250a%20%20%20%20client.print%2528%2522%253a%2522%2529%253b%250a%20%20%20%20client.println%2528port%2529%253b%250a%250a%20%20%20%20%252f%252a%20finish%20the%20http%20request%20%252a%252f%250a%20%20%20%20client.println%2528%2522User-Agent%253a%20esp32-poubelle%2522%2529%253b%250a%20%20%20%20client.println%2528%2522Connection%253a%20close%2522%2529%253b%250a%20%20%20%20client.println%2528%2529%253b%250a%250a%20%20%20%20%252f%252a%20message%20to%20say%20success%2521%20%252a%252f%250a%20%20%20%20Serial.println%2528%2522wifi%253a%20information%20sent%20to%20the%20server%20%2521%2522%2529%253b%250a%20%20%20%20splash_wifi_send_success_text%2528%2529%253b%250a%250a%20%20%257d%20else%20%257b%250a%20%20%20%20%252f%252a%20if%20the%20conneciton%20failed%20%252a%252f%250a%20%20%20%20Serial.println%2528%2522wifi%253a%20connection%20failed%20to%20the%20server%2522%2529%253b%250a%20%20%20%20Serial.println%2528%2522wifi%253a%20if%20you%20lost%20your%20wifi%20network%252c%20please%20reboot%20the%20device%2522%2529%253b%250a%20%20%20%20Serial.println%2528%2522wifi%253a%20you%20also%20may%20wanna%20check%20if%20the%20server%20is%20not%20offline%2522%2529%253b%250a%20%20%20%20Serial.println%2528%2522%2522%2529%253b%250a%20%20%20%20client.stop%2528%2529%253b%250a%20%20%257d%250a%250a%20%20%252f%252a%20debug%253a%20get%20reply%20from%20the%20server%250a%20%20%20%20while%2528client.available%2528%2529%2529%20%257b%250a%20%20%20%20char%20c%20%253d%20client.read%2528%2529%253b%250a%20%20%20%20Serial.print%2528c%2529%253b%250a%20%20%20%20%257d%250a%20%20%252a%252f%250a%250a%20%20%252f%252a%20once%20data%20has%20been%20sent%252c%20stop%20the%20wifi%20client%20%252a%252f%250a%20%20if%20%2528client.connected%2528%2529%2529%20%257b%250a%20%20%20%20client.stop%2528%2529%253b%250a%20%20%20%20Serial.println%2528%2522wifi%253a%20client%20stopped%2522%2529%253b%250a%20%20%20%20Serial.println%2528%2522%2522%2529%253b%250a%20%20%257d%250a%257d>

**Comment by mfix22** [comment]
Cool! Yeah so the maximum URL is [~2000](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers) and that URL is `> 6000`. The browser won't even open Carbon if the URL is that long, so it is the job of the plugin to truncate the code if you want it to work 👍

**Comment by x4m3** [comment]
yeah, i figured that out, i saw that i selected around 50 lines of code, whoops....

thanks for the help!
