### ISSUE TITLE
Copyable text

### ISSUE THREAD

**Issue by TheDevKiller** [dawnlabs/carbon#374]
Hello !

First, you service is very cool and useful but there is a problem: when I send the code with my friends, they can't copy the text and it's logic but can you, for example with a html page, render selectable text

Maybe you can put our code on a html page and put the image with the window in background of the page. It's just a proposition.

Sorry for my english because I'm french :p 

Good luck if you want to do this or good continuation and have a good life ^^

**Comment by mfix22** [comment]
This is an often requested feature, and we are working on it in the form of embedded iframes (see #358 for other possible integrations and cast your vote). 

Currently our tool creates images, so copying is not possible. Coming soon!
