### ISSUE TITLE
Same for "screenshot" ? :D

### ISSUE THREAD

**Issue by cyrilchapon** [dawnlabs/carbon#375]
In here, we usually create images of "fake screenshot", you know, to show a feature or something.

Is there any tool like carbon, or maybe a way to use carbon, to show an image instead of code ? :)

**Comment by mfix22** [comment]
This is a really awesome tool for screenshots: https://getkap.co/

I also just recently saw a tool on Twitter that lets you screenshot your desktop, automatically temporarily removing all the files from it, but I can't seem to find it anymore. Once i do i'll post it here. 

Other options:
- https://monosnap.com/welcome

**Comment by cyrilchapon** [comment]
Oh my point was not realy to "capture the screen" (the aformentionned "screenshots" are often not real ones); this was more like adding a mac-os-like browser frame to the image.

**Comment by cyrilchapon** [comment]
You know, just like carbon is not realy about "capturing" the code (even if you provide neat plugins), but more about presentation, adding some style, a fake window and fake controls

**Comment by mfix22** [comment]
Yeah the tool i was mentioning on tool would do that, but I can't seem to find it 😝

**Comment by cyrilchapon** [comment]
Yeah I've been facing search issues when trying to find this.. 😅 by nature when you go for "browser" "screenshot" "frame" etc. In Google, that does'nt work 😬
