### ISSUE TITLE
Unable to generate image with default settings when input is too large

### ISSUE THREAD

**Issue by serkankazak** [dawnlabs/carbon#389]
Hi,

First of all thanks for this great project, it really works well.

But I encountered a problem when using the following file:

https://gist.githubusercontent.com/serkankazak/6864159237ad0d6fb77cc512824eef65/raw/29969a6f42ab58698310925723c7972239b33edb/gistfile1.txt

Default settings was used with export size 2x. (It works when 1x but not when 2x.)

The reason of using this large file is generating single page colored pdf with the created png.

Thanks.

**Comment by mfix22** [comment]
This is a known issue. The URL is just too large for even a browser to handle (see https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers). Unfortunately we cannot support files that large 🙂

**Comment by serkankazak** [comment]
Oh I see thanks. But is it really about the url length? Since it works when 1x but not when 2x. Just tried at https://carbon.now.sh

**Comment by mfix22** [comment]
You can try looking at the URL length locally and confirm, but we have seen this issue many times and I know it to be the case.
