### ISSUE TITLE
Feature request: create gist?

### ISSUE THREAD

**Issue by jpnelson** [dawnlabs/carbon#393]
It'd be nice to create a gist from a code snippet, so that while tweeting, we'd have an accessible, screen readable version.

Would a PR that added this feature be accepted?

**Comment by mfix22** [comment]
I would accept this PR, maybe as a dropdown under Tweet? What do you think @jakedex @briandennis ?

**Comment by alvaropinot** [comment]
Having short urls and storing the snippets (#362) inside Carbon might be part of the solution. As for now I just add the code as the alt text to the image when tweeting it 😁 so people can copy paste it and screen readers can read the image for accessibility purposes.

**Comment by mfix22** [comment]
@alvaropinot we not automatically add the alt Text when you click the tweet button now, just FYI 👍

I think these are separate features though. There are tons of requests for integrations, and we can't support them all, but we can accept PRs that implement any of them. The issue for tracking integration requests is here: #358.

First and foremost though we want to support an embeddable Carbon window where the text is copy-able, and therefore also screen-readable (#179)

👌

**Comment by mfix22** [comment]
Moving to #358
