### ISSUE TITLE
How change watermark?

### ISSUE THREAD

**Issue by hamedmoody** [dawnlabs/carbon#395]
HI
How can i change watermark?

**Comment by kaicianflone** [comment]
@mfix22 I have noticed you are using `dropperx` I will go ahead and implement custom watermark upload using it. I might have some questions though :)

**Comment by mfix22** [comment]
Yeah go for it! I am pretty sure it will be fairly easy, but we might need to adjust the DropTarget box because the Watermark one will be _inside_ the other . . .

**Comment by mfix22** [comment]
Closing this since the question was answered!
