### ISSUE TITLE
Need more print-friendly "light" themes

### ISSUE THREAD

**Issue by sarahsga** [dawnlabs/carbon#402]
## Expected Behavior
This is using Base 16 (Light)
![1](https://user-images.githubusercontent.com/10798986/41657172-ee55ae6c-74ab-11e8-8ec7-57fcb0809781.png)

And this is how it appears on a black-and-white print-preview:
![screen shot 2018-06-20 at 5 10 18 pm](https://user-images.githubusercontent.com/10798986/41657573-40b07614-74ad-11e8-9f59-7d6b43d7a7d2.png)

## Actual Behavior
This is the only Light theme available. I cannot use a dark theme for printing. Can we have a light theme with white background and darker blackish foreground so it is print-friendly?

**Comment by mfix22** [comment]
Hey, thanks for the suggestion!. As of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon!), but we are happy to accept PRs to add new ones.

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄
