### ISSUE TITLE
Feature request: split screen/side-by-side editor

### ISSUE THREAD

**Issue by mddanishansari** [dawnlabs/carbon#403]
It would be really nice if we can have the feature of split screen(side-by-side or top-bottom) like most of the modern editors do.

It can be useful when you have to compare 2 codes, show difference, good code/bad code etc

I have absolutely no idea how this can be done. Otherwise I would have created a PR

**Comment by mfix22** [comment]
Hi @mddanishansari thanks for opening an issue. This is a duplicate of https://github.com/dawnlabs/carbon/issues/337 which we are not supporting as of now. We will reopen #337 if we decide to go that direction 😄

**Comment by mddanishansari** [comment]
Ok

**Comment by kievsash** [comment]
+1
Example of possible usage:
https://twitter.com/thekiba_io/status/1136908291366408192?s=20
