### ISSUE TITLE
Hashtag is not correctly displayed in svg format

### ISSUE THREAD

**Issue by KingsleyXie** [dawnlabs/carbon#405]
The hashtag `#` is displayed as `%23`  if the image was saved as SVG format, and conversely in PNG format.

I don't know if this is a feature...but it is more likely to be the URL encoding or similar character escape problem.

You can try the demo [here](https://carbon.now.sh/?bg=rgba(171,%20184,%20195,%201)&t=seti&wt=none&l=python&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Hack&fs=14px&si=false&code=%2523%2520%253C-%2520hashtag%2520is%2520displayed%2520as%2520%2560%252523%2560%2520in%2520svg%2520format&es=2x&wm=false).

### Code:

```python
# <- hashtag is displayed as `%23` in SVG format
```

### PNG Result:
![carbon](https://user-images.githubusercontent.com/20147971/41714193-171d44b4-7582-11e8-89f6-cf4d02665c24.png)

### SVG Result (Shown as PNG since GitHub doesn't support SVG image):
![demo](https://user-images.githubusercontent.com/20147971/41714524-3019cb62-7583-11e8-8824-68eda09a8b15.png)

**Comment by kaicianflone** [comment]
I'll take a look into it, but this could be an issue with [CodeMirror].(https://github.com/codemirror/CodeMirror) Or maybe the config @mfix22?

**Comment by kaicianflone** [comment]
Console Error: 

[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M68, around July 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

**Comment by mfix22** [comment]
This is actually a bug in `dom-to-image`. Our custom fork of `dom-to-image` updates the behavior with this line of code: 
```js
string.replace(/#/g, '%23').replace(/\n/g, '%0A')
```

@briandennis do you think this is something we should contribute back into `dom-to-image` itself? Or just update in our `Editor` component?

**Comment by mfix22** [comment]
I'm going to close this since this is a `dom-to-image` issue. Please help us update it in their project though! 🙂
