### ISSUE TITLE
Adjust line height

### ISSUE THREAD

**Issue by jakearchibald** [dawnlabs/carbon#406]
It'd be great to be able to adjust the line height. I fine code a lot easier to read with a little more line spacing.

**Comment by jakearchibald** [comment]
Fwiw, you can adjust the line height with devtools & Carbon keeps it for the screenshot.

Here's `line-height: 1.6`:

![Example](https://user-images.githubusercontent.com/93594/41770303-aa5eed04-7609-11e8-951b-cd0b482736ed.png)

**Comment by mfix22** [comment]
@jakearchibald my initial thought is that this is an advanced use case that most people won't use, and could potentially lead to a "feature-spiral" where we have to add one setting for every CSS property. 

I am going to consult with the rest of the core team before closing, though.

**Comment by jakearchibald** [comment]
That's fair. I guess I could apply it as a custom stylesheet.

If you do want the feature, I'd be happy to create a PR.

**Comment by mfix22** [comment]
@jakearchibald talked with the team today, and we would be happy to support `line-height`, as I found out that is a common property to adjust in a lot of web tools 😄 

Would _love_ to accept a PR 👍
