### ISSUE TITLE
Adding original code to image metadata

### ISSUE THREAD

**Issue by idkjs** [dawnlabs/carbon#408]
Right now, converting the default example to png gets you this:

![carbon 2](https://user-images.githubusercontent.com/2370391/41818019-c0087f50-77a6-11e8-9609-13008f97af20.png)

If you run it through https://www.get-metadata.com/

You get this:

![screenshot-2018-6-24 online exif data viewer](https://user-images.githubusercontent.com/2370391/41818024-d6d85246-77a6-11e8-8fc1-74c3215854c1.png)

It would be cool to be able to add the original code snippet to the metadata, maybe on the content attribute.
How would we add the original code to the image metadata so that we could do something like.
```js
var carbon-image = document.getElementById("carbon-image");
            EXIF.getData(carbon-image, function () {
                var allMetaData = EXIF.getAllTags(this);
                var allMetaDataSpan = document.getElementById("allMetaDataSpan");
                allMetaDataSpan.innerHTML = JSON.stringify(allMetaData, null, "\t");
            });
```

Using the example code from [exif-js](https://github.com/exif-js/exif-js)
It might look something like this. Note the metadata showing under some of the images:
![screenshot_2018-06-24 exif example with inline exif info](https://user-images.githubusercontent.com/2370391/41818080-094561e6-77a8-11e8-9502-734dae117d80.jpg)

Thank you.

**Comment by mfix22** [comment]
@idkjs if you are familiar with this sort of thing, we would love to accept a PR. I am completely foreign to image metadata, especially editing it in the browser.

**Comment by idkjs** [comment]
@mfix22 i tried messing with it before i posted the comment. The code text comes back on `state.code` in `pages/index.js`
https://github.com/dawnlabs/carbon/blob/7b9c31101e2abf743bc1fe68038cf1f4157e3e15/pages/index.js#L41-L48

If you comment out   `delete s.code` you are not longer deleting the code info and so you get it back:
<img width="496" alt="statecode" src="https://user-images.githubusercontent.com/2370391/41848318-56faa538-787d-11e8-9224-66128723b731.png">

After that I can't find it, mostly because I cant seem to log anything to console anywhere in the program after index(tell me how, and i will get at it). But if I could, I would try to append the code info to some property. The `photographer` key below seem to provide for that, but i guess we aren't using that.

https://github.com/dawnlabs/carbon/blob/7b9c31101e2abf743bc1fe68038cf1f4157e3e15/components/Editor.js#L185-L194

Setting this up makes it a lot more useful for using this in blogs. In fact, unsplash is already integrated into medium.com so maybe not to far away.

Thoughts?

**Comment by mfix22** [comment]
Accessing the code text is super doable. I am just wondering if you know how to encode anything as metadata into a PNG being saved using JavaScript (: 

Also I'm a little confused about your log comment. `console.log` should log to the DevTools if you are using Chrome or FireFox.

**Comment by sabhiram** [comment]
Cool project. A while back I wrote a utility in `golang` to embed `tEXt` chunks in png images. Have a look at the relevant bits here: https://github.com/sabhiram/png-embed/blob/master/embed.go

**Comment by mfix22** [comment]
I don't believe it is possible to _write_ the metadata into the PNG in the browse, which is our primary method for generation. 

Closing this as wont-fix, but if someone is aware of an alternative, I will reopen 🙂
