### ISSUE TITLE
Bugs in creating PNG

### ISSUE THREAD

**Issue by spacerwoman** [dawnlabs/carbon#409]
## Expected Behavior
I expect to get the code displayed right in the PNG.
## Actual Behavior
The code is always shown wrong in the PNG.

**Comment by briandennis** [comment]
Hey @spacerwoman, could you please provide more information as to the problem your experiencing? It's hard to diagnose the problem when the description is so vague.

Thanks!

**Comment by KelaKing** [comment]
```swift
override func updateConstraints() {
  NSLayoutConstraint.deactivate(myConstraints)
  myConstraints.removeAll()
  let views = ["text1": label1, "text2": label2]
  myConstraints += NSLayoutConstraint.constraints(withVisualFormat: "H:|-[text1]-[text2]",
                                                  options: [.alignAllFirstBaseline],
                                                  metrics: nil,
                                                  views: views as [String : Any])
  myConstraints += NSLayoutConstraint.constraints(withVisualFormat: "V:|-[text1]-|",
                                                  options: [],
                                                  metrics: nil,
                                                  views: views as [String : Any])
  NSLayoutConstraint.activate(myConstraints)
  super.updateConstraints()
}
```
It should be

<img width="941" alt="2018-07-08 4 57 29" src="https://user-images.githubusercontent.com/13584044/42418325-05bd9e7a-82d0-11e8-8730-9e96743cd1d9.png">

But the png is

![carbon](https://user-images.githubusercontent.com/13584044/42418328-21b3003e-82d0-11e8-84a0-79b03ed68289.png)

**Comment by mfix22** [comment]
@spacerwoman I tried it locally and it is working for me in Chrome. Which browser did you experience this bug in? This could be a duplicate of #331 and #365

**Comment by KelaKing** [comment]
Safari `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15`

**Comment by mfix22** [comment]
Closing as duplicate of #331 @briandennis
