### ISSUE TITLE
Up/Down keyboard

### ISSUE THREAD

**Issue by Tegos** [dawnlabs/carbon#420]
Hello.

![image](https://user-images.githubusercontent.com/7047662/42279565-d6a210a2-7fa6-11e8-8dbe-d6cc07b8c07d.png)

It's happened when selected style or language and press up/down keyboard buttons.

**Comment by kbleabres** [comment]
It doesn't happen to me. What were you on? Chrome? Safari? Mind giving more details?

**Comment by Tegos** [comment]
Ok, sure.

![image](https://user-images.githubusercontent.com/7047662/42321338-3ecd0b72-8061-11e8-8f84-16feda610b56.png)



![2018-07-05_14-31-36](https://user-images.githubusercontent.com/7047662/42321434-997927cc-8061-11e8-8683-2cb0d058382d.gif)

**Comment by samiskin** [comment]
This happens to me consistently when using Chrome on my Macbook Pro.  It occurs when selecting an item, then pressing up or down directly after that without clicking anywhere else first.
