### ISSUE TITLE
 PROPOSAL for updating and improving the CARBON LOGO

### ISSUE THREAD

**Issue by orlant** [dawnlabs/carbon#421]
Hello, my name is orlando velasquez I am a graphic designer, making contributions to projects with his is my focus, now if you allow me I can create something new for your CARBON project.

**Comment by mfix22** [comment]
We are very happy with where our logo is at right now, thanks for the offer though! We will keep you in mind for the future 🙂

**Comment by orlant** [comment]
thank you very much excuse me
