### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by rodrigobdz** [dawnlabs/carbon#422]
Link to tweet in README description is broken.
```
[code](https://twitter.com/thejameskyle/status/884986927954497536)
```
## Expected Behavior
It shows tweet.
## Actual Behavior

![broken twitter link](https://user-images.githubusercontent.com/14152377/42379701-e0749600-812b-11e8-93d6-caaaf969ce48.png)

**Comment by briandennis** [comment]
Thanks for catching that @rodrigobdz!
