### ISSUE TITLE
support to vscode with UI.

### ISSUE THREAD

**Issue by janryWang** [dawnlabs/carbon#425]
Carbon is an exciting production that makes our code very beautiful, but currently carbon carbon is only have a browser version. If carbon provides a vscode plugin, can it make everything easier?

**Comment by mfix22** [comment]
Hey @janryWang there actually is a VSCode extension created by @ericadamski: https://marketplace.visualstudio.com/items?itemName=ericadamski.carbon-now-sh 👍
