### ISSUE TITLE
Add support to Solidity language

### ISSUE THREAD

**Issue by aferreira44** [dawnlabs/carbon#427]
I would be really nice if we could support [Solidity](https://solidity.readthedocs.io) syntax.

**Comment by mfix22** [comment]
Hey, thanks for the suggestion!. As of Carbon `3.0.0`, the core Carbon team is no longer implementing new themes or languages ourselves (although we are adding the ability to create your own soon!), but we are happy to accept PRs to add new ones.

Please see https://github.com/dawnlabs/carbon#a-note-on-adding-themeslanguages for notes on how to do so 😄, and feel free to implement this!
