### ISSUE TITLE
Feature request: Highlight lines 

### ISSUE THREAD

**Issue by jalvarado91** [dawnlabs/carbon#428]
It would be cool to be able to select lines to highlight similar to how you can do it in the [github viewer](https://github.com/dawnlabs/carbon/blob/master/components/Editor.js#L235-L245). 

The interaction would probably be similar. Click to the left of a line to highlight it, and if we're holding the Shift key down we can click another line to select a range of lines. 

Codemirror supports this via the [Active Line option](https://codemirror.net/demo/activeline.html), so it should be feasible. 

I would also be down to work on a PR for this. Should be fun.

**Comment by mfix22** [comment]
Unless I am mistaken, you can already highlight the lines of the Carbon editor, and those highlights even remain in the image after saving as well  . . . Is this what you mean? 🙂

**Comment by jalvarado91** [comment]
Oh haha. I guess it kinda does. It's a bit finicky if you want to highlight the entire line, and it looks like it the highlight color renders funky once the editor is not in focus so it makes it a bit hard to read (for the record I haven't tested if using the Active Line option in code mirror is more readable). This also doesn't really let me select more than one selected range. 

![carbon 1](https://user-images.githubusercontent.com/1750392/42764742-5e024a94-88e4-11e8-9c2f-6e55227aae26.png)

I think if using the Active Line option makes it look better this feature would be worth it. I'll experiment and post and update here to see if it's better.

**Comment by mfix22** [comment]
@jalvarado91 please do! Thanks 🙂

**Comment by mfix22** [comment]
After looking into this more, you are already able to highlight the lines, and then click away and the highlighting remains. You can also click save and the highlights will be in the PNG. Closing . . .
