### ISSUE TITLE
Not able to set Background image

### ISSUE THREAD

**Issue by mittalyashu** [dawnlabs/carbon#431]
## Expected Behavior
Not able to set a Background image

## Actual Behavior
![image](https://user-images.githubusercontent.com/29014463/42690589-695f7598-86c2-11e8-9595-eb8945e8ab37.png)

**Comment by farskid** [comment]
@mittalyashu Setting custom background images from local device works fine while I was testing on production. Is it still broken? Is it local image or choosing from unsplash?

**Comment by mittalyashu** [comment]
Hmm... I have tried it now and it working perfectly.

Thanks

**Comment by mfix22** [comment]
Closing, open again if you see an issue!

**Comment by mittalyashu** [comment]
Sure.
