### ISSUE TITLE
How to remove shadow

### ISSUE THREAD

**Issue by CoXier** [dawnlabs/carbon#436]
## Expected Behavior
Thanks very much for this nice tool.

I want to know if I can remove shadow around the window.

## Actual Behavior

Now from online site, I can not or I do nor find how to remove shadow.

**Comment by CoXier** [comment]
I save code in png format.

**Comment by mfix22** [comment]
<img width="699" alt="screenshot 2018-07-19 10 55 30" src="https://user-images.githubusercontent.com/8397708/42960977-47d242aa-8b42-11e8-8d43-83d57c447d2c.png">

Click the setting that says "Drop shadow" in the "Advanced Settings" dropdown 👍

**Comment by CoXier** [comment]
Thanks a lot.
