### ISSUE TITLE
Contributor dead links

### ISSUE THREAD

**Issue by vitorgalvao** [dawnlabs/carbon#437]
On the [README’s contributors section](https://github.com/dawnlabs/carbon/blob/master/README.md#contributors), a few contributos have dead links:

* [Brad Davies](https://bradlab.co.uk/)
* [Hugo Torzuoli](https://torzuolih.github.io/)
* [Bruno C. Couto](https://github.com/bruno02221)

**Comment by mfix22** [comment]
@hugomd @varbrad @imbrn can you all submit PRs to update these links if you would like? Otherwise I will close (:

**Comment by hugomd** [comment]
@mfix22 I think you meant to tag @HZooly 😉

**Comment by HZooly** [comment]
Hey guys, indeed, this is me 😄 

https://github.com/dawnlabs/carbon/pull/442
