### ISSUE TITLE
Emojis and Chinese characters are not rendered in the output

### ISSUE THREAD

**Issue by dmcrodrigues** [dawnlabs/carbon#439]
## Expected Behavior

<img width="338" alt="screen shot 2018-07-21 at 16 51 42" src="https://user-images.githubusercontent.com/1098602/43037569-6e0a2b84-8d06-11e8-899f-d11d5d3ba78a.png">

## Actual Behavior

![carbon-12](https://user-images.githubusercontent.com/1098602/43037574-74ed2532-8d06-11e8-9f78-408b59738a69.png)

**Comment by mfix22** [comment]
Hey thanks for filing this. What browser were you using?

**Comment by dmcrodrigues** [comment]
Hey @mfix22, I'm using Safari 11.1.2 (13605.3.8).

**Comment by mittalyashu** [comment]
It works for me, I am using Chrome: 68.0.3440.84

![carbon 1](https://user-images.githubusercontent.com/29014463/43673124-b4cfea3e-97da-11e8-87dc-3462f7a11711.png)

**Comment by mfix22** [comment]
@mittalyashu the failure case is for Safari

**Comment by mfix22** [comment]
I believe this is fixed in `puppeteer@1.6.*`, however, we need to wait for #451 to be fixed before we can upgrade our puppeteer version.

**Comment by ajarouih** [comment]
It works for me with the same configs as yours try this emoji as copy/paste  👌

**Comment by mfix22** [comment]
@ajarouih it works in all browsers except Safari

**Comment by sdabhi23** [comment]
@mfix22 as #451 has been fixed, can I help fix this one?

**Comment by mfix22** [comment]
@sdabhi23 Absolutely! we would appreciate your help on this one

**Comment by mfix22** [comment]
Just pushed an update the adds the correct fonts for emojis and simplified Chinese!
