### ISSUE TITLE
C code not highlighted as expected

### ISSUE THREAD

**Issue by darahak** [dawnlabs/carbon#44]
C or C++ code is not highlighted as I would expect.
I saw that you were using CodeMirror, so I went to see the documentation.

It should at least highlight type names, as seen on this [page](https://codemirror.net/mode/clike/index.html).
See what I got on Carbon below, with Monokai theme.

I only looked at `lib/constants.js` and `components/Carbon.js` and didn't see anything wrong, so I'm not sure what's happening. Maybe a style conflict?

<details>
  <summary>Sample</summary>

  ![carbon](https://user-images.githubusercontent.com/11488612/30909985-6143acd0-a383-11e7-82c8-18d4c0506346.png)

</details>

**Comment by jakedex** [comment]
Thanks for reporting this, @darahak! I'll have a fix for this once we add MIME support with #58
