### ISSUE TITLE
Weird export to png issue

### ISSUE THREAD

**Issue by aspittel** [dawnlabs/carbon#445]
## Expected Behavior

When I click export to PNG it is adding a 255 to my string and not png exporting it!

<img width="491" alt="screen shot 2018-07-30 at 10 06 51 am" src="https://user-images.githubusercontent.com/12969662/43402620-243b5e10-93e1-11e8-908a-e4079b053f96.png">

## Actual Behavior
<img width="421" alt="screen shot 2018-07-30 at 10 10 59 am" src="https://user-images.githubusercontent.com/12969662/43402621-2449f2f4-93e1-11e8-990c-b082eaba12a1.png">

**Comment by mfix22** [comment]
Certain unicode patterns fail in `dom-to-image`. We intentionally change those patterns
