### ISSUE TITLE
Cannot export PNG for code with %c in it

### ISSUE THREAD

**Issue by nwalters512** [dawnlabs/carbon#446]
I have the following block of code:

```
git log -1 --format=%cd | grep 2018 --silent
```

However, when I try to save as a PNG, I get an uncaught promise exception in the console. It looks like the `%c` is the problem: removing the `%` or changing it to something like `%y` allows it to save as expected.

**Comment by mfix22** [comment]
Can you post your full text snippet here? I tried locally and it is working just fine for me from what you have described 🙂

**Comment by nwalters512** [comment]
That's the full snippet! In fact, the smallest reproducible case I could get is `%cd`.

* Chrome version: 68.0.3440.84
* macOS version: 10.13.6

It also fails in Safari 11.1.2 (13605.3.8). I see the following error in the console:

```
Failed to load resource: the server responded with a status of 500 ()        https://carbon.now.sh/image
```

**Comment by mfix22** [comment]
Whoops! Yeah of course that's the snippet 😅 

fd9de34410235221b4ab168ccd3e67f3aae294b6 should fix it. Release coming soon.

**Comment by nwalters512** [comment]
Thanks so much for the quick fix!
