### ISSUE TITLE
Create multiple beautiful default themes to choose from

### ISSUE THREAD

**Issue by mittalyashu** [dawnlabs/carbon#450]
### Expected Behavior
While playing around with the settings, it is possible that we might end up creating something like this, which looks horrible.

![carbon](https://user-images.githubusercontent.com/29014463/43673067-f4a232ee-97d9-11e8-8a30-c2f022fd0ee8.png)

That's why we need help.

### Actual Behavior

Generate a beautiful random settings.

**Comment by mfix22** [comment]
We do want to support more beautiful default options, but definitely not random 😝 
Maybe close this issue, and create a new one? Or just update the titles and such.

**Comment by mittalyashu** [comment]
I hope you have understood what I mean to say.

**Comment by mittalyashu** [comment]
https://www.useloom.com/share/9a9d27aceb584264bd9b9866f74aca76

**Comment by mfix22** [comment]
@mittalyashu totally understood! We do want to create a bunch of beautiful default themes that set the font, background, and color-theme, padding etc so users can quickly choose one that works best for them. But we don't want it to be "random" per se (:

**Comment by mittalyashu** [comment]
> We do want to create a bunch of beautiful default themes, but we don't want it to be "random".

Got it.

**Comment by Jaredk3nt** [comment]
I'm interest in taking on this issue,
Just to make it clear is the scope adding a 'templates' drop down menu as well as creating default themes to add to the menu?
Also I'm assuming there will some approval process on the default themes?
Thanks!

**Comment by mittalyashu** [comment]
> Just to make it clear is the scope adding a 'templates' drop down menu as well as creating default themes to add to the menu?

Yes, a predefined theme should include all the settings which carbon currently provide and we should be able to override the theme with custom setting if we want.

**Comment by Jaredk3nt** [comment]
Awesome, I would love to be assigned to this!

**Comment by mfix22** [comment]
@Jaredk3nt feel free to open a WIP PR and I can give you feedback as you go. I figured posting screenshots of the theme would be a good way to verify which themes we like before finalizing on the selection UI.

@jakedex and I can help out the theme menu

**Comment by Jaredk3nt** [comment]
Making a bunch of examples here are a couple that I think are good starts. Feedback is appreciated! I looked through a bunch that people have posted places to get a feel for the kinds of themes people are already using and are doing well.

![carbon](https://user-images.githubusercontent.com/6362515/45859021-ca48ac00-bd25-11e8-8839-305d115bac56.png)
![carbon 6](https://user-images.githubusercontent.com/6362515/45859026-d7fe3180-bd25-11e8-90e0-c1eb190e531b.png)
![carbon 8](https://user-images.githubusercontent.com/6362515/45860340-42b26b80-bd2c-11e8-97b7-d0670e5a6406.png)

About how many defaults is a good number to start with, maybe 5? or more?

**Comment by mittalyashu** [comment]
@Jaredk3nt Yeah 5 theme is a good start.

Maybe try adding the settings along with the image, so that we can try it and give feedback.

**Comment by Jaredk3nt** [comment]
1. https://carbon.now.sh/?bg=rgba(222%2C171%2C99%2C1)&t=duotone-dark&wt=none&l=auto&ds=true&dsyoff=12px&dsblur=31px&wc=true&wa=true&pv=27px&ph=36px&ln=false&fm=Hack&fs=13.5px&lh=128%25&si=false&es=2x&wm=false&ts=false

2. https://carbon.now.sh/?bg=rgba(205%2C219%2C237%2C1)&t=verminal&wt=none&l=auto&ds=false&dsyoff=12px&dsblur=27px&wc=false&wa=true&pv=35px&ph=52px&ln=true&fm=Fira%20Code&fs=14.5px&lh=120%25&si=false&es=2x&wm=false&ts=false

3. https://carbon.now.sh/?bg=rgba(229%2C229%2C229%2C1)&t=seti&wt=sharp&l=auto&ds=true&dsyoff=12px&dsblur=27px&wc=true&wa=true&pv=50px&ph=47px&ln=false&fm=Hack&fs=13.5px&lh=128%25&si=false&es=2x&wm=false&ts=false (which I now realize looks pretty similar to the default theme when you first get to the site, so it would probably just be a good idea to include the default as the first theme in the list)

**Comment by kalwaniyash** [comment]
@Jaredk3nt these seem lovely are there any more i can look at?
