### ISSUE TITLE
Adjust font style

### ISSUE THREAD

**Issue by Kikobeats** [dawnlabs/carbon#46]
- font family
- font weight
- font size
- line height
- letter spacing

**Comment by selrond** [comment]
Would be totally awesome!
Google (probably monospaced only) fonts option would be a killer feature!

I'd add __line heght__ option to the suggestions list

**Comment by Kikobeats** [comment]
@selrond added!

Also `letter-spacing`

**Comment by selrond** [comment]
@Kikobeats any way I can help this?

**Comment by Kikobeats** [comment]
@selrond probably talking with jakedex yes, I don't know the current codebase 😄

**Comment by lili21** [comment]
any updates ?

**Comment by mfix22** [comment]
No updates from the @dawnlabs team. We are not actively working on this feature, although it is on our radar given the support!

Anyone is welcome to help us out with this one! 😄

**Comment by jakedex** [comment]
I've actually been sitting on some progress on a local branch here, just pushed it up [here](https://github.com/dawnlabs/carbon/tree/font-settings).
