### ISSUE TITLE
Light themes support

### ISSUE THREAD

**Issue by sobolevn** [dawnlabs/carbon#47]
Right now there are not light terminal themes. Some users may want to use white (or similar) terminal background.

I am big fan of light terminal themes like [`sobole`](https://github.com/sobolevn/sobole-zsh-theme).

Any chance to get a tool to import a custom theme? 
Or maybe include some popular light options?

**Comment by mfix22** [comment]
@sobolevn there are actually a couple light themes located [here](https://github.com/dawnlabs/carbon/blob/master/lib/constants.js#L53-L64) (marked by the field `light`). 

If have specific themes in mind, you can make a PR to add other themes you like from here: http://codemirror.net/3/demo/theme.html#

We are thinking about adding support for custom themes, so I am not going to close this issue yet.

**Comment by mfix22** [comment]
@sobolevn please make a pull request to add any light themes that you like to work with! Closing this issue.
