### ISSUE TITLE
Color theme not applying on Firefox

### ISSUE THREAD

**Issue by tw0517tw** [dawnlabs/carbon#483]
### Expected Behavior

Code has color

### Actual Behavior

No color for code. But I can change other settings like window control, background, etc.

![default](https://user-images.githubusercontent.com/1003146/44348465-13120880-a4cd-11e8-8158-2b2f16eac04b.png)

<details>
  <summary>Browser: </summary>
  Firefox 62.0b18 (64 bit) in private browsing mode
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment]
Sorry about this! I just fixed it with b19bbf26aeb352426a9393f9d039418e541fe3c2. I will get it redeployed now.

**Comment by mfix22** [comment]
If you still see the issue, try reloading your browser with CMD + Shift + R

**Comment by mfix22** [comment]
If the issue is still presented, you can fix the issue by running:
```js
"allow pasting"
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.getRegistrations().then(function (registrations) {
    //returns installed service workers
    if (registrations.length) {
      for(let registration of registrations) {
        registration.unregister();
      }
    }
  });
}
```
