### ISSUE TITLE
Feature request: Copy Image to clipboard

### ISSUE THREAD

**Issue by abhimanyu003** [dawnlabs/carbon#49]
It will be really great if there is copy to clipboard option.
Quite helpful when you have to share the image to slack - discord or any other chatting application which supports direct upload.

**Comment by briandennis** [comment]
yesssss! @jakedex do you think this should be a separate button or can we integrate this to the existing UI somehow?

**Comment by jakedex** [comment]
We could change the 'Save Image' -> 'Copy Image' when the user holds `shift`?

**Comment by abhimanyu003** [comment]
I don't think updating 'Save Image' -> 'Copy Image', when the user holds shift, is a good idea.

The other thing we can do is open image in base64 output in the new tab?
After which user only have to right click and click copy image in the browser.

**Comment by rehatkathuria** [comment]
I think this could be a nice solution? #179

**Comment by martinfrancois** [comment]
Maybe we could turn the current buttons into (font awesome) icons? We could then use a Twitter icon for the tweet button, a clipboard icon for saving to clipboard and a save icon for saving? Would be much more compact that way and would not look crowded.

**Comment by VinSpee** [comment]
Copying image data to the clipboard is [still not supported in browsers](https://bugs.chromium.org/p/chromium/issues/detail?id=150835). Maybe the best solution would be [what @abhimanyu003 suggested](https://github.com/dawnlabs/carbon/issues/49#issuecomment-334441288). Any opposition?
