### ISSUE TITLE
Allow image url for background

### ISSUE THREAD

**Issue by newyork-anthonyng** [dawnlabs/carbon#490]
### Expected Behavior
Thank you for this amazing tool 🔥 

I wanted to add a new feature to allow using URL's for background image. From what I can see, you can only use random images from `Unsplash` or upload your own images. But then I miss out the goodness of using [fillmurray](https://www.fillmurray.com) on my code snippets.

![screen shot 2018-08-27 at 5 04 54 pm](https://user-images.githubusercontent.com/14035529/44686541-97f4a900-aa1c-11e8-9df9-6e736f468f63.png)

**Comment by mfix22** [comment]
Cool. @newyork-anthonyng in the meantime are you able to download the images and then upload them to Carbon manually? Just FYI you can drag and drop an image onto the editor to upload it to Carbon.

**Comment by newyork-anthonyng** [comment]
@mfix22 Cool, that sounds like a good workaround.

I would also like to work on this feature if you think it's a valid one. Lemme know 👍
