### ISSUE TITLE
How to open the project on localhost to try and implement new stuff on my own machine? Do we have to use NPM run?

### ISSUE THREAD

**Issue by namanxtreme** [dawnlabs/carbon#492]
### Actual Behavior

<details>
  <summary>Browser: </summary>
  
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment]
You can run the app by running `npm run dev` from the top level directory 👍 This will run it on port `3000`, so if you want to run it on a different port, use `npm run dev -- -p <PORT>`
