### ISSUE TITLE
Upload files to a live server

### ISSUE THREAD

**Issue by namanxtreme** [dawnlabs/carbon#494]
### Actual Behavior

<details>
  <summary>Browser: </summary>
  
</details>
If I wish to upload this project with some of my changes done from localhost to my live server. How can this be performed? Server side has no framework installed. Please provide a detailed step-by-step instruction as I am a newbie. Thanks :)
<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment]
You can deploy this project yourself by running `npm install && npm run deploy`.
