### ISSUE TITLE
Line number has a weird shade. It wasn't like that before

### ISSUE THREAD

**Issue by amejiarosario** [dawnlabs/carbon#495]
### Expected Behavior
![image](https://user-images.githubusercontent.com/418605/45002663-4bbee100-afa7-11e8-809a-96428fbaa9d9.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/418605/45002665-54171c00-afa7-11e8-8e8c-f4350bd9c589.png)

**Comment by mfix22** [comment]
@amejiarosario is this just for solarized light? I just tried it now and got:

![carbon 1](https://user-images.githubusercontent.com/8397708/45004762-1ebcff00-afa4-11e8-84d0-cd740b2a10e5.png)

What browser are you using?

**Comment by mfix22** [comment]
@amejiarosario thank you for posting !!
