### ISSUE TITLE
'Backend error' and loading spinner but no code editor component

### ISSUE THREAD

**Issue by philwolstenholme** [dawnlabs/carbon#497]
I'm seeing a console error and the code editor component is not loading.

The issue persists between Chrome and Safari, and the error message suggests it's a server side issue.

<img width="1677" alt="screen shot 2018-09-04 at 18 13 53" src="https://user-images.githubusercontent.com/6339853/45046520-4e383e00-b06e-11e8-9593-0e4cd05e4d3d.png">

**Comment by philwolstenholme** [comment]
Hi @mfix22 , it was just https://carbon.now.sh – I didn't get redirected to a URL like https://carbon.now.sh/?bg=rgba(171%2C184%2C195%2C0)&t=material&wt=none&l=application%2Fx-sh&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=false&pv=48px&ph=32px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&ts=false

The issue seems to be resolved now, the editor component is loading correctly for me now.

**Comment by mfix22** [comment]
That is _weird_ . . .  I wonder if there was an error that was temporary in our backend server provider? If you think the issue is resolved, please close, and reopen if you notice how to recreate it (:

**Comment by philwolstenholme** [comment]
Happy to close as I can't reproduce it now. Thank you for a brilliant tool, by the way! 👍

**Comment by mfix22** [comment]
Thanks @philwolstenholme 🙏
