### ISSUE TITLE
Add C# language support

### ISSUE THREAD

**Issue by Worldbeater** [dawnlabs/carbon#50]
It would be really great if this service could support syntax highlighting for C# programming language.

Thanks!

**Comment by otobrglez** [comment]
Hey @Worldbeater! I'm not a contributor or anything. But I found this [configuration][configuration] file inside cardbon; perhaps you can add it yourself? 😃 You can also find exact modules in [codemirror configuration][codemirror] that provides styling/rendering of code.

[configuration]: https://github.com/dawnlabs/carbon/blob/master/lib/constants.js#L74-L271
[codemirror]: https://github.com/codemirror/CodeMirror/blob/282cf36664d05f776eba88a1f8ace03c1f085cd0/mode/meta.js#L23

**Comment by mfix22** [comment]
Thanks @otobrglez! The mode `clike` might work for `C#`

**Comment by jchannon** [comment]
Looking forward to this! 👍

**Comment by jchannon** [comment]
When will this make it onto the website?
