### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by ucdstudent95618** [dawnlabs/carbon#514]
Hi Carbon team,

I want to translate the GitHub page to Spanish, is that something you would like to do?

Thanks,

Miguel

**Comment by mfix22** [comment]
@ucdstudent95618 absolutely! I have actually been hoping someone would offer to translate the `README`! I would really really appreciate that 🙏😄 

You can create a new file and I can reorganize it before merging 🙂 Let me know if you need any help.

**Comment by ucdstudent95618** [comment]
Awesome! 🙂 I will send you a PR once I am done. I will create a file called README.es.md.
