### ISSUE TITLE
Carbon CLI

### ISSUE THREAD

**Issue by jakedex** [dawnlabs/carbon#52]
If there's enough support, we could create a CLI interface for Carbon.

**Comment by andrewda** [comment]
I'm super interested in working on a CLI. How would it work, though? The only way I can see it working at the moment is using an API from Carbon to fetch the image. The downside to this is that the user would need an internet connection. An alternative would be for the user to self-host Carbon, but that would result in high startup times.

It'd be great if we could think of a way to do this without a server.

**Comment by jakedex** [comment]
https://github.com/dawnlabs/carbon/pull/88#issuecomment-333429240

**Comment by briandennis** [comment]
@andrewda the functionality I'm working on now to get the app working in Safari should be pretty similar to what's needed for the CLI locally. Once I finish that, let's chat

**Comment by itaditya** [comment]
Hey guys I have made a simple CLI here https://github.com/itaditya/carbon-cli . Take a look https://www.npmjs.com/package/carbon-cli

**Comment by monouser7dig** [comment]
> If there's enough support, we could create a CLI interface for Carbon.

as a bash script or alike without npm? would be very welcome and sleek 

like `carbon --syntax=c --theme=material input.c output_c.png`

**Comment by zmwangx** [comment]
Maybe it's possible to build an entirely local CLI with puppeteer?

**Comment by mfix22** [comment]
Hey all, issues marked "Integrations" are being closed and theirs discussions moved to https://github.com/dawnlabs/carbon/issues/358. With many requests for new features, this allows the Carbon team to prioritize which to support first 👍
