### ISSUE TITLE
Drunk bash parser ?

### ISSUE THREAD

**Issue by TheLaluka** [dawnlabs/carbon#557]
### Description
Hi there, it seems that the bash parser behaves in a quite weird way, not detecting the difference between commands, arguments and options... No clue on what's going on, just giving you the feedback ! :)

### Screenshot
![image](https://user-images.githubusercontent.com/7013722/47370848-e2c23280-d6e6-11e8-8ddd-a222981d9891.png)

### Reproduce using this input : 
```
# Activer les loopbacks
modprobe loop
# Créer le fichier et l'appairer en tant que device
dd if=/dev/zero of=clair.img bs=1M count=10
losetup /dev/loop0 clair.img

# Créer le filesystem, le mountpoint, monter, ...
mkfs -t ext3 /dev/loop0
mkdir /mnt/clair
mount -t ext3 /dev/loop0 /mnt/clair
umount /mnt/clair 
losetup -d /dev/loop0

# En automatisant s’il vous plaît ? 
mount -o loop -t ext3 clair.img /mnt/clair
echo "PouetPouetPouet" > /mnt/clair/pouet.txt
umount /mnt/clair
hexdump -C clair.img | grep -i pouet
```

### Random
Thank you a lot for this tool, I use it on a daily basis, you rock ! ;)

**Comment by mfix22** [comment]
Hey @TheLaluka! Thanks for the kind words. Unfortunately we don't actually do any of the parsing ourselves. That is probably a code-mirror issue. Potentially this would be fixed in the latest version of CodeMirror. Would you be willing to upgrade CodeMirror (including the version here: https://github.com/dawnlabs/carbon/blob/master/components/Meta.js#L29-L37) and try it?

**Comment by mfix22** [comment]
@TheLaluka I'm going to close this as out of scope for this repo, but please open up an issue with CodeMirror or try and push a PR there yourself 🙂

**Comment by TheLaluka** [comment]
Hi @mfix22 , 
Sorry but I won't have time to find the issue and fix it :/
And yes, this is more than probably only related to the parser, maybe we could just put CodeMirror in the loop ?
