### ISSUE TITLE
Feature Suggestion: Ability to name file downloads 

### ISSUE THREAD

**Issue by dgading** [dawnlabs/carbon#561]
### Expected Behavior
The ability to set a new filename before clicking the export PNG button and downloading a file with that name. 

### Actual Behavior
All downloaded images are labelled carbon.png.

I wasn't sure what the right order was, but I have a version of this enhancement I am using locally for a presentation. Most of my file names are <section>-<description>.png. I loved the customization with Carbon over Polacode but the workflow using the VS Code extension was very slow since as I had to download and then rename each file. 

I currently have it in the Settings drop down, but it might be better to have a toggle there that then shows the text input with the export dropdown. If the value is null, it just returns the currently hardcoded `carbon${timestamp}`

**Comment by mixn** [comment]
[`carbon-now-cli`](https://github.com/mixn/carbon-now-cli) supports this via the `--target` and `--location` flags, if that helps you right now. :)
