### ISSUE TITLE
characters (such as ", #, %, ...) changing on export

### ISSUE THREAD

**Issue by jaywonchung** [dawnlabs/carbon#564]
### Expected Behavior

I expect the code I pasted into carbon.now.sh to stay the same after I export it.

### Actual Behavior

<details>
  <summary>Browser</summary>
Naver Whale, Version 1.3.53.4 (64-bit) (a chrome-based browser)
  
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>

    #include <iostream>
    #include <cstring>
    using namespace std;
    
    int d[5000][5000];
    
    int main()
    {
        int T = 10;
        while (T--) {
            int n; scanf("%d", &n);    // this line changes to "int n; scanf(%22%25d%22, &n);"
            string s; cin>>s;
            
            memset(d, 0, sizeof(d));
            
            for (int i=0; i<n; ++i) {
                d[i][i] = 1;
            }
           for (int i=0; i<n-1; ++i) {
                d[i][i+1] = (s[i]==s[i+1]?2:1);
            }
            for (int l=2; l<n; ++l) {
                for (int i=0; i+l<n; ++i) {
                    int j = i+l;
                    if (s[i]==s[j]) d[i][j] = d[i+1][j-1] + 2;
                    else d[i][j] = max(d[i+1][j], d[i][j-1]);
                }
            }
        
            printf("#%d %d\n", 10-T, d[0][n-1]);    // this line changes to "printf(%22%23%25d%20%25d%5Cn%22, 10-T, d[0][n-1]);
        }
        
        return 0;
    }

I do recognize that these are URL encoded special characters. On the first export, even if the characters change, the png file is generated correctly without URL encoded characters. However, when I export again after the change, every '%' changes again to '%25', making the code longer every export. This time the change is also applied to the exported png file. 

First export:
![first export](https://user-images.githubusercontent.com/29395896/47539074-6e1b0e00-d909-11e8-9be2-1390e7cf33f6.png)

Second Export:
![second export](https://user-images.githubusercontent.com/29395896/47539093-812dde00-d909-11e8-9b16-52d9434aacdd.png)

  
</details>

**Comment by mfix22** [comment]
These lines (https://github.com/dawnlabs/carbon/blob/master/components/Editor.js#L142-L146) should be moved into the `filter` function, but the trouble is we don't know the width of the element ahead of time then. 

We just need to come up with a way to calculate the width to pass in with the appropriate `filter`

**Comment by mfix22** [comment]
@jaywonchung can you paste the snippet you are seeing the failure on below

**Comment by mfix22** [comment]
Closed with 3b67c0a846dbfdb6509906d893fc1ecf55ed25c3 (🤞hopefully this is the final time)

**Comment by hexrcs** [comment]
@mfix22 There's still problems with special characters. :( When pasting in the following code, exporting doesn't work and an error is thrown in the console. :disappointed: Works when I remove the `%` in the code though.

The trouble making code:

```javascript
console.log('%cconsole.log can be fancy too', 'color: green; font-size: 25px;');
console.log(
  '%cor... %ceven%cfancier', 
  'color: cornsilk; background: #5C323E; font-weight: bold; font-size: 20px;',
  'color: floralwhite; background: lawngreen; font-size: 25px; margin: 4px;', 
  'border-style: dashed; border-radius: 10px; background: tomato; font-size: 30px; font-style: italic;'
);

```

Error is like:

![image](https://user-images.githubusercontent.com/26751752/49442862-076ff680-f7cb-11e8-8be6-9273b5da8d12.png)

And the carbon editor:

![image](https://user-images.githubusercontent.com/26751752/49442904-279fb580-f7cb-11e8-990d-39c3cd1338f6.png)

**Comment by mfix22** [comment]
@CapitanFindusFI can you share the text here? 🙂I'll look into fixing it immediately once you do

**Comment by CapitanFindusFI** [comment]
@mfix22 there you are 😄 

```
// print matrix, normal rows > columns iteration
void print_matrice(int m[RIGHE][COLONNE]){
    printf("printing matrix\n");
    for(int i = 0; i < RIGHE; i++){
        for(int k = 0; k < COLONNE; k++){
            printf("%d ", m[i][k]);
        }
        printf("\n");
    }
    printf("\n");
}

// insert matrix values, normal rows > columns iterations
void insert_matrix(int m[RIGHE][COLONNE]){
    for(int i = 0; i < RIGHE; i++){
        for(int k = 0; k < COLONNE; k++){
            int value;
            printf("insert row: %d, column: %d - ", i, k);
            scanf("%d", &value);
            
            m[i][k] = value;
        }
    }
}
```

**Comment by kkew3** [comment]
I failed into the same issue today. Here's my snippet:

```perl
my %hash;
LINE:
while (<>) {
	chomp;
	scalar(split(" ", $_, 2)) > 1 or goto LINE;
	m/^man / and goto LINE;
	exists($hash{$_}) or print($_ . "\n");
	$hash{$_} = ();
}
```

where the first line `my %hash` changes to `my %25hash` during exporting; in the result image, `my %hash` is not colored.
