### ISSUE TITLE
Doesn't work on mobile at all…

### ISSUE THREAD

**Issue by NSExceptional** [dawnlabs/carbon#573]
Did you guys even test it there?

- Cannot select or otherwise manipulate text other than typing
- Cannot insert spaces

**Comment by photonstorm** [comment]
![image](https://user-images.githubusercontent.com/164476/48340401-70e46580-e662-11e8-9672-0c2b987979c5.png)

**Comment by mfix22** [comment]
Duplicate of #506

This is a priority of ours. However there are many mobile limitations caused by `CodeMirror` 

If you have suggestions, please raise them on #506

**Comment by NSExceptional** [comment]
Thanks!
