### ISSUE TITLE
Sqaure off image now removed

### ISSUE THREAD

**Issue by Benwebdev** [dawnlabs/carbon#591]
**Describe the bug**
I was using this great tool to make code snippets for instagram, I was using the square off image feature and was working great. 

With the new option layout I am either being stupid and missing it or I can't seem to find this feature anymore. Has it been removed? 

All in all, very well done with Carbon! very good tool.

**Comment by mfix22** [comment]
Hey @Benwebdev. You are correct, it is currently missing. We were not sure if we should continue to support it as it didn't fit well with the rest of the settings, but seems people still use it 🙂 

I will add it back to the new menu. In the meantime just use https://carbon.now.sh/?si=true to enable the feature yourself!

**Comment by Benwebdev** [comment]
Thanks man!
