### ISSUE TITLE
Cropped image bug

### ISSUE THREAD

**Issue by sandervanhooft** [dawnlabs/carbon#596]
**Describe the bug**
Images are getting cropped, rendering it unusable.

**To Reproduce**
1. Go to carbon.now.sh
2. Paste this snippet:
```php
/*
 * Laravel Blade directive for short human readable
 * numbers (i.e. 3K+, 4M+).
 * 
 * sandervanhooft/laravel-blade-readable-numbers
 */

@readable_int(123456) // outputs 123K+
@readable_int(123456789) // outputs 123M+
@readable_int(123456789012) // outputs 123B+
@readable_int(123456789012345) // outputs 123T+
```
3. Export using "1x", "png".

**Expected behavior**
Nice full image, similar to this screenshot of the editor/preview:
<img width="810" alt="screenshot 2018-12-05 at 19 00 23" src="https://user-images.githubusercontent.com/7265703/49537166-2ef4bb00-f8c0-11e8-8817-f3f8eb52b315.png">

**Screenshots**
![carbon](https://user-images.githubusercontent.com/7265703/49537081-e2a97b00-f8bf-11e8-85e0-5ada86e1dd9e.png)

**Info (please complete the following information):**
 - OS [e.g. macOS, Linux, Windows, iOS]: MacOSX 10.14.1 (18B75)
 - Browser [e.g. chrome, safari]: Safari 12.0.1 (14606.2.104.1.1)
<details>
  <summary>Code Snippet (If Applicable)</summary>
/*
 * Laravel Blade directive for short human readable
 * numbers (i.e. 3K+, 4M+).
 * 
 * sandervanhooft/laravel-blade-readable-numbers
 */

@readable_int(123456) // outputs 123K+
@readable_int(123456789) // outputs 123M+
@readable_int(123456789012) // outputs 123B+
@readable_int(123456789012345) // outputs 123T+
</details>

**Comment by mfix22** [comment]
Closed with https://github.com/dawnlabs/carbon/releases/tag/3.6.3
