### ISSUE TITLE
A Darcula theme would be nice

### ISSUE THREAD

**Issue by ZakTaccardi** [dawnlabs/carbon#597]
A Darcula theme based on Android Studio/IntelliJ's IDES would be 👍

**Comment by mfix22** [comment]
<img width="289" alt="screenshot 2018-12-10 12 03 26" src="https://user-images.githubusercontent.com/8397708/49758371-9cfc0200-fc73-11e8-887c-c851922d9f16.png">

We already have a Darcula (Dracula) theme 👍

**Comment by alessandro-calo** [comment]
Hi @mfix22, quick follow-up on this issue: 
I don't see `Dracula` anymore, only `Dracula Pro`. But `Dracula Pro` is different from IntelliJ's `Darcula`:

![carbon](https://user-images.githubusercontent.com/55374095/97895027-87929400-1d33-11eb-8a43-f24b507e1087.png)
![Screen Shot 2020-11-02 at 17 46 33](https://user-images.githubusercontent.com/55374095/97895033-895c5780-1d33-11eb-80be-51f6d8596230.png)

So I'm thinking it would make sense to add a Darcula theme, to look like what IntelliJ developers are expecting to get from a screenshot. What do you think?
