### ISSUE TITLE
Potential Security Issue?

### ISSUE THREAD

**Issue by pmacMaps** [dawnlabs/carbon#612]
A friend shared a link to https :// carbon.now.sh /.  Because he did not tell me anything about this library, I decided to check if it was legit.  According to Norton (https://safeweb.norton.com/report/show?url=https%3A%2F%2Fcarbon.now.sh%2F), drive-by downloads are a potential threat.  Below are Norton's listing.

I am creating an issue so that the maintainer of this project is aware of this potential issue, and can explain why Norton is incorrect in black-listing their site.  Also, to warn users of this library of potential security concerns.

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https: // mxcdn1.now. sh

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https: // mxcdn2.now. sh

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https: // npcdn1.now. sh

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https: // sxcdn02.now. sh

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https :// sxcdn3.now. sh

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https: // sxcdn4.now .sh

- Threat Name: Web Attack: Fake TechSupport Website
- Location: https: // sxcdn6.now .sh

**Comment by mfix22** [comment]
This is related to `now.sh` in general, not specifically https://carbon.now.sh. @timothyis do you know anything about this?

**Comment by jamo** [comment]
Thank you for bringing these to our attention; our security team is on it.

**Comment by jamo** [comment]
Just got word that it's all taken care of, thank you again for bringing it to our attention!

For any additional security concerns, the fastest way to get our security teams attention is to reach out to security@zeit.co but all means for pinging us will do.

**Comment by mfix22** [comment]
Thanks @jamo! 🎉
