### ISSUE TITLE
Option to remove the Window Size / Minimize buttons

### ISSUE THREAD

**Issue by NullVoxPopuli** [dawnlabs/carbon#619]
These 3 buttons in the top left have no meaning in the context of a code snippet, and are very macOS inspired, so, an option to remove them would be fantastic :)

**Comment by mfix22** [comment]
<img width="454" alt="screenshot 2019-01-07 10 58 49" src="https://user-images.githubusercontent.com/8397708/50787430-3b778500-126b-11e9-89de-42fe39881fb9.png">

You can disable them by clicking the "Window controls" toggle in the settings 👍

**Comment by NullVoxPopuli** [comment]
ah! Window Controls! thanks!

![image](https://user-images.githubusercontent.com/199018/50787654-037d3b80-1285-11e9-96be-57bd7c4c6c09.png)
