### ISSUE TITLE
Solarized theme has inaccurate colors

### ISSUE THREAD

**Issue by roryokane** [dawnlabs/carbon#62]
This is what code looks like on https://carbon.now.sh/ when I choose the Solarized theme:

![lib/constants.js code displayed in Carbon's Solarized theme](https://user-images.githubusercontent.com/79168/30978315-35805cae-a448-11e7-83ab-7dc6218096db.png)

But the background color is different from that of the light variant of the official [Solarized theme](http://ethanschoonover.com/solarized):

![official Solarized theme, light version](https://user-images.githubusercontent.com/79168/30978395-6f28768a-a448-11e7-8bac-bb46e684b0f9.png)

The background looks white in Carbon, but it should be light yellow. I'm not sure, but the shade of orange used for `export const` might also not be in Solarized's palette.

Note that Solarized also has a dark theme with the same text colors but a dark blue background. Don't get them confused. Maybe you want to support both as "Solarized (light)" and "Solarized (dark)"?

**Comment by salmanulfarzy** [comment]
@roryokane Looks like theme styles are imported from [codemirror](https://codemirror.net/demo/theme.html#solarized%20light). 

https://github.com/dawnlabs/carbon/blob/6b1e0aedaa01dc41eeba2d7e0db89962c8a07f81/components/Meta.js#L22-L26

**Comment by jakedex** [comment]
Good catch, @roryokane! This is fixed with #63 and will be included in our next release.
