### ISSUE TITLE
Safari always creates squared images

### ISSUE THREAD

**Issue by boyvanamstel** [dawnlabs/carbon#631]
**Describe the bug**
Images generated with Safari are always squared, regardless of what `si` is set to.

**To Reproduce**
1. Open a new incognito window with Safari (shift + cmd + N).
2. Visit https://carbon.now.sh/?si=false.
3. Export image.

**Result**
![carbon](https://user-images.githubusercontent.com/225410/50973765-f4e38e00-14e9-11e9-9fac-6cdf940b6b2a.png)

**Expected behavior**
![carbon 1](https://user-images.githubusercontent.com/225410/50973696-ca91d080-14e9-11e9-9e41-5577ef1d30d7.png)
(^ Image created with Chrome)

**Info (please complete the following information):**
 - OS: macOS, iOS
 - Browser: Safari (both desktop and mobile)

**Comment by mfix22** [comment]
Just pushed an update for Safari — should be good to go now! 👍

**Comment by boyvanamstel** [comment]
Yep, works. Thanks! 👍
