### ISSUE TITLE
New cypress integrations tests

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/carbon#635]
Verify:
- Single instance of `#export-container` and `.export-container'`
- Single instance of`#export-menu`
After export menu has been clicked:
- Single instance of `#export-png`
- Single instance of `#export-svg`

**Comment by mixn** [comment]
@mfix22 Thanks a ton for filing this! :) I’d really be great to have this indeed. I’m super packed atm with work stuff, but will integrate this once I find some free time.

**Comment by mfix22** [comment]
No worries @mixn took ~5 minutes! (:
