### ISSUE TITLE
Safari: cannot load https://carbon-api.now.sh/image due to access control checks

### ISSUE THREAD

**Issue by boyvanamstel** [dawnlabs/carbon#636]
**Describe the bug**
When trying to export to PNG, the Carbon API is unreachable and the export fails. Affects the Tweet button as well.

**To Reproduce**
1. Click export.
2. Choose PNG.
3. Nothing happens.

**Expected behavior**
A PNG should be generated and downloaded.

**Screenshots**
<img width="842" alt="screenshot 2019-01-14 at 19 11 44" src="https://user-images.githubusercontent.com/225410/51166688-a268ef80-18a4-11e9-8643-31b12fd2778d.png">

**Info (please complete the following information):**
 - macOS
 - Safari

**Comment by mfix22** [comment]
This should be good to go! Sorry about that, we are upgrading some the support for Safari and there has been some bugs in the production environment. My apologies!

**Comment by boyvanamstel** [comment]
Great! Thanks for issuing a fix so quickly. 👍

**Comment by boyvanamstel** [comment]
@mfix22 Sorry for reopening this (and not verifying the fix before), but it seems the issue isn't fixed (anymore).

**Comment by boyvanamstel** [comment]
@mfix22 Nevermind, caching I guess.
