### ISSUE TITLE
Setting a background image throws an "unexpected error"

### ISSUE THREAD

**Issue by boyvanamstel** [dawnlabs/carbon#637]
**Describe the bug**
Setting a background image (either by uploading, or picking the suggested image from Unsplash) clears the window and shows the following error message:

"An unexpected error has occurred."

**To Reproduce**
1. Click the background color/image picker.
2. Select 'Image'.
3. Click 'Use Image' to pick the suggested image.

**Expected behavior**
The background image should be set.

**Screenshots**
<img width="581" alt="screenshot 2019-01-15 at 16 21 39" src="https://user-images.githubusercontent.com/225410/51190116-c72f8800-18e1-11e9-9163-cfd894e65656.png">
<img width="945" alt="screenshot 2019-01-15 at 16 22 24" src="https://user-images.githubusercontent.com/225410/51190121-cac30f00-18e1-11e9-9be0-c04102789d41.png">

**Info (please complete the following information):**
 - macOS
 - Tested with both Chrome and Safari

**Comment by mfix22** [comment]
This should be good to go! Sorry about that, we are upgrading some the support for Unsplash and there has been some bugs in the production environment. My apologies!
