### ISSUE TITLE
Feature request: Proxy data from github gist

### ISSUE THREAD

**Issue by aocenas** [dawnlabs/carbon#646]
At the moment when using gist id feature, it just loads the data from the gist and embeds it into the url. This creates a problem first when the the gist or any other snippet is too big due to max url length limits, second when you keep your snippets in github it can be tedious to update gist -> create carbon url -> update in the blog post on every change.

Would it be possible for carbon to act as a proxy so that for example url `carbon.now.sh/GIST_ID_HERE` would actually serve the gist content just enhanced with the carbon styling so it is directly embeddable and updated in case the gist is updated?

**Comment by mfix22** [comment]
@aocenas that is actually how it currently works 👍 

Example: https://carbon.now.sh/mfix22/82d742f4efad9757cc826d20f2a5e5af

**Comment by aocenas** [comment]
@mfix22 Not really, or I do not understand how it is supposed to work. If I go that link it loads the content of the and changes the url encoding the content there. So it results in
```
https://carbon.now.sh/?bg=rgba(245%2C166%2C35%2C1)&t=seti&wt=sharp&l=javascript&ds=false&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=0px&ph=0px&ln=true&fm=Hack&fs=14px&lh=133%25&si=false&code=export%2520function%2520replaceWithComponent(regex%252C%2520mapping%252C%2520s)%2520%257B%250A%2520%2520%2520%2520const%2520parts%2520%253D%2520s.split(regex)%253B%250A%2520%2520%2520%2520for%2520(let%2520i%2520%253D%25201%253B%2520i%2520%253C%2520parts.length%253B%2520i%2520%252B%253D%25202)%2520%257B%250A%2520%2520%2520%2520%2520%2520parts%255Bi%255D%2520%253D%2520mapping(parts%255Bi%255D)%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520return%2520%253CFragment%253E%257Bparts%257D%253C%252FFragment%253E%250A%257D%250A&es=1x&wm=false
```
And the same url is there when you try to embed it. I do not think this url will reflect any later change to the `mfix22/82d742f4efad9757cc826d20f2a5e5af` gist or does it?

**Comment by mfix22** [comment]
Ohhhhh i see what you mean!

**Comment by aocenas** [comment]
@mfix22 Close but not quite :). Sorry I should have explained it in more detail from the start. What I do right now when writing a post on Medium is:
1. I write the story
2. A create the gists in github
3. Embed the gists to the story
4. If there is an issue with the gists I just update them in github and thats it. The embeds on Medium always point to the latest version.

This is the best workflow I found so far for the lack of better code snippet support on medium.

Right now with carbon the workflow would be:
1. 2. 3. are the same just carbon instead of github
4. Here though if I want to update the embeds, I need to go to carbon, update it there, get a new url and update the embed in Medium (because the content of the snippet is encoded in the url). And also the issue with max url length makes this problematic for long snippets of code.

I mean it is not that big of a deal but to me it seems it would be easier if I could just use url like
```
 https://carbon.now.sh/<some_predefined_style_name>/<gist_id>
```
and embed that directly in Medium. On the backend carbon would have to get the content from Github gist (probably not through API but some public raw gist url I would assume), wrap it into the proper styling HTML and send it as response. Thats why I am thinking about it as styling proxy service.

Not sure if this is easy to do, mainly regarding what additional load that would create on the service, additional latency and a more problematic caching as you would need to wait for github response first to know whether the contents of the gist changed.

**Comment by mfix22** [comment]
I think we want to just support saving Carbon screenshots similar to how PasteBin handles it, giving you back a unique global id that you can not only share for editing, but also for updating Carbon embeds how you mentioned.

I think this feature would not be explicitly tied to Gists, however. With this feature, you would no longer need Gists.

**Comment by aocenas** [comment]
Yeah in that case, this proposal would be a step in different direction. Feel free to close this.

**Comment by mfix22** [comment]
@aocenas this is WIP/beta functionality, but you can now create a file called `~carbon.json` in any gist, and within that file, include the style for that Carbon screenshot as a JSON object. 

Here is an example: 
Gist: https://gist.github.com/mfix22/82d742f4efad9757cc826d20f2a5e5af
Carbon: https://carbon.now.sh/mfix22/82d742f4efad9757cc826d20f2a5e5af

Is that what you were thinking? If so, please close the issue 🙂

**Comment by aocenas** [comment]
@mfix22 That is pretty handy. Sorry for dragging this so long, but I am not sure this makes the feature request go away :).

Can I at this moment embed https://carbon.now.sh/mfix22/82d742f4efad9757cc826d20f2a5e5af directly in the Medium (or other place)? Because that would be great, I could update the gist without needing to regenerate the embedded urls in my articles. What I see though is that I need to load the carbon website let it load the gist data and then generate embed url which has the content of the gist copied in the url query param. That would mean I have to repeat that process of loading the carbon web end generate embed url every time I change something in the gist. So this is kinda the crux of my issue.

On the other hand I get it that such a workflow would make carbon probably invisible (or at least much less visible) to the user and so maybe isn't the direction you want to go. If so you can probably close this with "not going to do".

**Comment by mfix22** [comment]
@aocenas we actually merged a PR that implements exactly what you are describing, we just haven't deployed it yet. I am going to deploy it tomorrow though 👍

**Comment by aocenas** [comment]
@mfix22 That is great, let me know when I can try it.

**Comment by mfix22** [comment]
@aocenas our Embed.ly provider was just updated! Everything is working end to end now. 

To see an example, check out this URL:
https://embed.ly/code?url=https%3A%2F%2Fcarbon.now.sh%2Fmfix22%2Ff08d913cf4a0792ed00332e876f5efd4

which shows Carbon proxying the Gist from https://gist.github.com/mfix22/f08d913cf4a0792ed00332e876f5efd4

Really excited so see how people use this functionality!

**Comment by aocenas** [comment]
@mfix22 Thats great, exactly what I had in mind. Thanks for the work :)
