### ISSUE TITLE
Option to download/copy code from image

### ISSUE THREAD

**Issue by lmeijdam** [dawnlabs/carbon#65]
Hey guys!

I really love the idea of the code sharing by image and how it get presented. I only found a limitation whenever I want to share my code to be copied by a reader. You guys think this is possible in a future stage?

**Wished feature;**
Possibility to copy the code shown on the image to an editor.

**Comment by jakedex** [comment]
I'm not sure I follow. Are you hoping to have the text embedded in the saved image (i.e. PDF)?

**Comment by yeskunall** [comment]
I think he means he wants to be able to copy the image onto the clipboard and paste it into the editor as it is, i.e., as an image.

**Comment by jakedex** [comment]
Okay, in that case closing for #49

**Comment by lmeijdam** [comment]
Sorry for my late response!

More to have the code on an image available to 'self-use' in your project. To copy it like a snippet into your own code.

**Comment by yeskunall** [comment]
We have no control over the image once it's exported by Carbon. If you're using Carbon to export a snippet of your code, then you already have the code. That's the only way you could get the code, AFAIK.
