### ISSUE TITLE
Code is not syntax highlighted when page initially loads for some languages

### ISSUE THREAD

**Issue by davidrleonard** [dawnlabs/carbon#653]
**Describe the bug**

Some languages are not correctly syntax highlighted when the page initially loads. CSS does not work but JavaScript does.

**To Reproduce**

Visit https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=seti&wt=none&l=css&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&code=.body%2520%257B%2520color%253A%2520red%2520%257D%2520&es=2x&wm=false

**Expected behavior**

When the page loads the code should be syntax highlighted

**Actual behavior**

The code is not syntax highlighted even though CSS is the selected language from the query param

**Additional notes**

* Initial syntax highlighting works as expected if the mode is JavaScript (see https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=seti&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%25&si=false&code=var%2520color%2520%253D%2520%27red%27%253B&es=2x&wm=false)
* Syntax highlighting works in reproduction if, after loading the page, you pick another language and then pick the original language again
* I didn't have time to clone/debug/bisect, but I'm guessing that the issue might have cropped up in or around 80122adea607929bcec24fece9cac18d152c8ca1 which introduced dynamic imports of codemirror modes

**Screenshots**

Broken initial syntax highlighting for CSS snippet linked in To Reproduce section:

![image](https://user-images.githubusercontent.com/6456757/51804905-3bf9af00-225e-11e9-860e-e97c900db298.png)

**Info (please complete the following information):**

 - OS [e.g. macOS, Linux, Windows, iOS]: macOS High Sierra 10.13.2 / Macbook Pro 15in i7 (latest)

Verified bug is present in all the following browsers for the CSS snippet linked in To Reproduce section:

- Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Firefox 64.0.2 (64-bit)
- Safari 11.0.2 (13604.4.7.1.3)

**Comment by loop0day** [comment]
Same here.

**Comment by mfix22** [comment]
@davidrleonard thanks for submitting this issue! You are right, https://github.com/dawnlabs/carbon/commit/80122adea607929bcec24fece9cac18d152c8ca1 was the commit that caused this issue. I have reverted to an older version until we resolve this issue on master.
