### ISSUE TITLE
Force `Save As` dialog when trying to save the image

### ISSUE THREAD

**Issue by yeskunall** [dawnlabs/carbon#66]
Hey guys 👋 great work on Carbon!

Right now, all images are saved as `carbon.png` by default. This means that if I were to save multiple screenshots in succession, they would all be saved under the same name, with just a number appended to the file name (on Windows as `carbon (1).png`) and so on.

Maybe we could make it so that the site forces a Save As dialog asking the user to name the file by themselves? Just a suggestion, but I would love to see this implemented. ❤️

**Comment by briandennis** [comment]
Great idea! We should definitely add support for this

**Comment by yeskunall** [comment]
I'm glad I'm not the only one who thinks this is worth the effort. 😄

A few things that I would like to add to this:

* Chrome allows you to turn on an option in settings that prompts the user each time they download a file, so for users who have already turned this option on, this "feature" is already implemented. I'm not so sure about the other browsers, however. In any case, if we are to implement this feature, we shouldn't be depending on the user to have this option enabled
* From [caniuse.com](http://caniuse.com/#search=download), the HTML5 `download` attribute is largely supported on all recent builds of modern browsers, so that's a good thing for us (but there are certain mobile builds that don't have support for it. However, I can't imagine a use case where someone would use this app through their phones, but hey, who knows? 🤷‍♀️)

So here's my suggestion: how about we add a field where the user can enter the file name for their screenshot? Thoughts? Comments? Feedback? I'm all ears 👂

**Comment by bombellos** [comment]
Hey guys! I've just noticed your repo while searching for some Open Source project to contribute to. Anyway, how about adding a time stamp with date to the file so it looks like this for example: `carbon_17-10-03_16:54` or similar format? It will also work while sorting files on disk by name.

**Comment by mfix22** [comment]
Hey @bombellos thanks for finding us, and we would love for you to contribute! 

 @yeskunall thanks for the discussion. After further consideration, we have decided that the saving behavior is good enough for the use case. Chrome currently does the "Save As" dialog, and for other browsers a `(#)` gets appended which is good for different versions.

Plus there are other more fun issues to work on 🤗

**Comment by yeskunall** [comment]
Sure thing! But I just want to point out that the "Save As" dialog (in Chrome) isn't on for most users by default.

![capture](https://user-images.githubusercontent.com/14703164/31231264-5a150bac-a9b4-11e7-8c65-8506128e46b4.PNG)

I can't say the same about other browsers, tho 🤔 (just thought you guys should know)
