### ISSUE TITLE
(bug) Switching to specific language, then back to `Auto` breaks render

### ISSUE THREAD

**Issue by yeskunall** [dawnlabs/carbon#67]
See screenshots for clarification. ⬇️

Set to auto:

![carbon](https://user-images.githubusercontent.com/14703164/31023724-c1fd2af0-a50a-11e7-903d-914046613a74.png)

Change to HTML:

![carbon](https://user-images.githubusercontent.com/14703164/31023755-e08eb81c-a50a-11e7-8eb9-75499476ef86.png)

Now back to auto:

![carbon](https://user-images.githubusercontent.com/14703164/31023755-e08eb81c-a50a-11e7-8eb9-75499476ef86.png)

IMO, the editor should have gone back to the state it was in the first image. LMK if this needs more clarification.

**Comment by briandennis** [comment]
Think this was fixed with https://github.com/dawnlabs/carbon/issues/37? cc @mfix22

**Comment by mfix22** [comment]
Yes. Just hasn't been deployed yet. Coming soon.

**Comment by yeskunall** [comment]
Ah, whoopsie. I'm sorry about the duplicate issue. 🙈 I'm gonna close this one. You guys are free to reopen if necessary. Thanks for the quick response!  ❤️

**Comment by briandennis** [comment]
No worries, thanks for taking the time to file the issue! I'll be sure to let you know when this ships
