### ISSUE TITLE
Custom themes don't work with Safari

### ISSUE THREAD

**Issue by boyvanamstel** [dawnlabs/carbon#671]
Setting a custom theme and exporting an image with Safari does not honor the custom theme settings.

**To Reproduce**
1. Launch Safari.
2. Create a custom theme.
3. Export the image.
4. The image will have the last selected (built-in) theme.

**Expected behavior**
The image should have the customized theme applied.

**Screenshots**
Browser:
![screenshot 2019-02-13 at 11 58 40](https://user-images.githubusercontent.com/225410/52706904-bc225300-2f86-11e9-977b-6f26cc045e63.png)

Output:
![carbon](https://user-images.githubusercontent.com/225410/52706914-c3496100-2f86-11e9-8cdf-96c578af2099.png)

**Info (please complete the following information):**
 - OS [e.g. macOS, Linux, Windows, iOS]: macOS
 - Browser [e.g. chrome, safari]: Safari

---

Am I correct when I think the feature has not been implemented in the API that the Safari-side of things uses?

Is there any way to contribute to that? I'd love to make Safari a first class citizen for Carbon. Especially since Carbonize relies on it now.😅

**Comment by shaddu** [comment]
Might be related to the similar issue, when I add an image in the background and try exporting in safari. It doesn't work and in console logs, I found this

![screenshot 2019-02-23 at 07 36 06](https://user-images.githubusercontent.com/16138402/53283412-09988000-373e-11e9-8662-fa01ac7f4f80.png)

**Comment by mfix22** [comment]
@shaddu that is a separate issue actually. Since Carbon needs to use a URL to create the screenshot in Safari, using an external background image typically fails for either a URL length limit or else the lambda payload limit (~6MB)

**Comment by mfix22** [comment]
Closed with https://github.com/dawnlabs/carbon/pull/727 🎉
