### ISSUE TITLE
Exported svg is too large 1.3MB, while 2x png is just 70+KB

### ISSUE THREAD

**Issue by LanderlYoung** [dawnlabs/carbon#672]
### Expected Behavior

svg should be reasonabely small than png, jpgs.

### Actual Behavior

<details>
  <summary>Browser: </summary>
  
 Google Chrome Version 72.0.3626.96 (Official Build) (64-bit)
 
OS: macOS 10.14.2

</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  

[code here](https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=material&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=false&wa=true&pv=0px&ph=0px&ln=false&fm=Source%20Code%20Pro&fs=14px&lh=133%25&si=false&code=%252F%252F%2520%25E9%2587%258A%25E6%2594%25BE%25E6%258E%2589%25E4%25B8%258D%25E5%258F%25AF%25E8%25A7%2581activity%25E5%25AE%259E%25E4%25BE%258B%25EF%25BC%258C%25E4%25BB%25A5%25E8%25BE%25BE%25E5%2588%25B0%25E8%258A%2582%25E7%259C%2581%25E5%2586%2585%25E5%25AD%2598%25E7%259A%2584%25E7%259B%25AE%25E7%259A%2584%250Afun%2520releaseSomeActivity()%2520%257B%250A%2520%2520%2520%2520if%2520(Build.VERSION.SDK_INT%2520%253E%253D%252021)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520for%2520(activityRef%2520in%2520mRunningActivities)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520activityRef.get()%253F.releaseInstance()%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%257D&es=2x&wm=false)

</details>

**Comment by Joel-hanson** [comment]
Shall I take up this issue? @mfix22

**Comment by mfix22** [comment]
@Joel-hanson go for it! 👍 

I just don't know how much there is to do here. We use `dom-to-image` to create PNGs and SVGs, but curious as to what you come up with.

**Comment by Joel-hanson** [comment]
#683

**Comment by mfix22** [comment]
Closed with #683
