### ISSUE TITLE
All contributors bot support

### ISSUE THREAD

**Issue by jakebolam** [dawnlabs/carbon#687]
Great project, didn't know this tool you existed, I'm going to use this all the time! 

Thanks for using @all-contributors. I noticed you hit a snag using the bot @mfix22 https://github.com/dawnlabs/carbon/pull/686#issuecomment-468747073. We put a hard limit in place to prevent more than [5 contributor file updates](https://github.com/dawnlabs/carbon/blob/master/.all-contributorsrc#L5) at a time.

This was an agressive limit to avoid abuse, you're project is the first use case we've seen needing this.

If you're interested in using the bot, we can totally raise this. Let us know 😀

**Comment by mfix22** [comment]
@jakebolam instead of raising the limit, could you not just make the bot add the contributor, without rerunning the generate script when the limit is reached? 

Either way, I would love to use the bot, yes 🙂

**Comment by mfix22** [comment]
Also, thanks for the kind words 🙏

**Comment by mralwin** [comment]
@mfix22 just letting you know we have raised the file limit to 15, let us know if you run into anymore issues

**Comment by mfix22** [comment]
@jakebolam we are running into this issue again: https://github.com/carbon-app/carbon/pull/1131#issuecomment-731848121

The comment says "5 files", but I'm assuming that is just a bug and that we are running into the new limit.
