### ISSUE TITLE
Support for Adobe ColdFusion

### ISSUE THREAD

**Issue by mayuranchalia** [dawnlabs/carbon#702]
### Actual Behavior

<details>
  <summary>Browser: </summary>
  
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  
</details>

**Comment by mfix22** [comment]
I am confused what you mean by "Support" in this case. Are you just referring to the ColdFusion syntax?

**Comment by mayuranchalia** [comment]
Yes
