### ISSUE TITLE
After adjusting line-height, code selection no longer lines up.

### ISSUE THREAD

**Issue by JosephWeaver** [dawnlabs/carbon#708]
Thanks for looking at this issue / thanks in advance for fixing it! I love this little project! :D

### Expected Behavior
After adjusting line-height, code selection should line up with the apparent location of the code. This would let users adjust line-height, and then continue to use the web app to create screenshots.

### Actual Behavior
After adjusting line-height, code selection no longer lines up with the apparent location of the code. This makes for an unusable experience, after line-height is set. The more the line-height is changed, the worse the problem.

In the below screenshot, I have selected ALL the text (that little bump you can see at the bottom of the selection, is the closing curly brace (` } `) being selected.

![carbon-selection-misaligned](https://user-images.githubusercontent.com/7841164/54728806-3709fb00-4b3d-11e9-94b1-1506613ecefd.png)

<details>
  <summary>Browser:</summary>
  Chrome, Brave
</details>

**Comment by ignatiusmb** [comment]
It seems to fix itself when you try to inspect its element

**Comment by JosephWeaver** [comment]
Not for me! =\

Cheers,

Joe Weaver
[JoeWeaver.me](http://www.joeweaver.me)

**Comment by mfix22** [comment]
As a work around until this is fixed, you could re-highlight the lines after adjusting the line height 👍

**Comment by mfix22** [comment]
@JosephWeaver this problem doesn't seem large enough to manually keep track of the selection in code and then reapply it after the line height's change. Can you not just reselect the lines after you update the line heights? 

Line heights on there own are already a rarely used feature 🙂

**Comment by JosephWeaver** [comment]
Haha, well of course I can do that, but I just thought you might want to fix the site to be more user friendly :P I’m happy with the site as it is and I use it all the time, but you have a place to submit issues, so I submitted one.

Cheers,

Joe Weaver
[JoeWeaver.me](http://www.joeweaver.me)
