### ISSUE TITLE
Repository website URL isn't working

### ISSUE THREAD

**Issue by ahtee** [dawnlabs/carbon#714]
**Describe the bug**
https://dawnlabs.io/carbon is not working or not reachable.

**To Reproduce**
1. Go to https://dawnlabs.io/carbon
2. See error

Fix the dawnlabs site or use the working URL: https://carbon.now.sh used in the [readme.md](https://github.com/dawnlabs/carbon/blob/master/README.md)

**Comment by mfix22** [comment]
```shell
curl --include https://dawnlabs.io/carbon
HTTP/2 302
date: Fri, 29 Mar 2019 18:54:26 GMT
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
location: https://carbon.now.sh
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4bf40d64edd3289a-SJC
```
It works for me? Even the link in your comment above is working. Which browser are you using?

**Comment by ahtee** [comment]
Chrome 73.0.3683.86

**Comment by mfix22** [comment]
Yeah what does `curl --include https://dawnlabs.io/carbon` return?

**Comment by ahtee** [comment]
```
➜  ~ curl --include https://dawnlabs.io/carbon
HTTP/2 302
date: Fri, 29 Mar 2019 20:28:07 GMT
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
location: https://carbon.now.sh
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4bf496a0cf1da62d-IND
```

**Comment by ahtee** [comment]
if i make the URL `http://dawnlabs.io/carbon` it works (`http` instead of `https`)

**Comment by mfix22** [comment]
I have opened an issue on our site repository (which is private) to investigate further, but I am going to close this one since these issues are specifically for Carbon 👍

**Comment by ahtee** [comment]
thanks it could be ssl or something too who knows lol have a good weekend
