### ISSUE TITLE
Syntax highlighting isn't coloring all the time

### ISSUE THREAD

**Issue by VinGarcia** [dawnlabs/carbon#722]
I use Carbon frequently to make slides to my programming class.

Today for some reason the syntax highlighting stopped working depending on what I wrote (maybe a language detection problem).

When I finished my first code snipped the syntax highlighting did not work but I was able to tweak my code until it started working again. On my second code snippet, I wasn't able to fix it:

https://drive.google.com/file/d/1J-f7GVS1JN2uHQYBthWvxaOXl_qfCvMU/view?usp=sharing

### Expected Behavior

I expected the syntax highlighting to work.

### Actual Behavior

<details>
  <summary>Browser: Google Chrome on Linux</summary>
  Version 73.0.3683.86 (Official Build) (64-bit)
</details>

<details>
  <summary>Code Snippet</summary>

```javascript
var people = [];

people.push("José");
people.push("Luana");

console.log(people);
```
</details>

**Comment by mfix22** [comment]
@VinGarcia can you paste the snippet here so I can make sure to fix this? Also I am assuming you were using "Auto" language mode.

**Comment by mfix22** [comment]
@VinGarcia just so you know, when issues like this crop up feel free to just manually set the Language, like to "JavaScript", for example.

**Comment by mfix22** [comment]
In the snippet above, `less` is being detected by Highlight.js (might be worth taking up an issue with them, if it makes sense).

**Comment by VinGarcia** [comment]
@mfix22 yes you are correct, and I totally forgot about that option :sweat_smile:.

Thanks for the quick reply, if you agree I think we can close this issue.

**Comment by mfix22** [comment]
No worries at all! This issues are also to answer questions and help you all out! 🙂 Thanks for asking 👍
