### ISSUE TITLE
Random file name

### ISSUE THREAD

**Issue by mittalyashu** [dawnlabs/carbon#742]
## Description

An option which automatically generates a random string (`Fdw65we3`) of character and will be further used as a file name.

Whenever we download images from carbon instead of getting like this,

* `carbon.png`
* `carbon (1).png`
* `carbon (2).png`

We can get file names like this, and I think this version of file names looks much better.

* `carbon-2x-Fdw65we3.png`
* `carbon-4x-r45CC350.png`
* `carbon-2vErtb756.png`

## Why?

*NOTE: The vision of this feature request is for a long term goal.*

Once Carbon releases the API, we can think of the endless possibility of using the Carbon app with APIs.

Passing the data...

1. getting the image back and storing in AWS bucket.
2. creating an embed
3. getting the image and send to slack/discord
4. getting the image and print it. *(I don't know why would you print the code but it would look nice)*

When it comes to handling the image and storing it somewhere that time we need a proper filename which doesn't have an empty space in between or certain unwanted characters.

Sure, a random string generator feature can also be built by the person who is handling the image on the server side, once getting the image we can rename the file, but having that feature per-build inside the Carbon application, will be more helpful.

## Inspiration
When we upload an image to Imgur we get a unique URL for every image.

**Comment by mfix22** [comment]
The API wouldn't return a file directly, it would return the data that the user could then store anywhere: in a file, S3 bucket, in the browser, wherever. The API would not have any concern for the name of the Carbon file, especially because the user might not even be writing it to a file. 

As for the Carbon App, we already allow users to fully customize the filename in app, or in the download dialog window. 

If users still want a custom format to create unique filenames, I could consider adding back the option to prepend a timestamp to the filename.

**Comment by mittalyashu** [comment]
>The API wouldn't return a file directly, it would return the data that the user could then store anywhere: in a file, S3 bucket, in the browser, wherever. 

What do mean by not returning a file directly? Since that's the workflow inside the carbon app data input, few configurations and download the image.

Or maybe you must have thought of different approach for creating the APIs 🤔

> If users still want a custom format to create unique filenames, I could consider adding back the option to prepend a timestamp to the filename.

Yeah, I think that would be a better idea than a random string 😅

**Comment by mfix22** [comment]
@mittalyashu I have been thinking about this a lot, and I think that this format:
`carbon.png`
`carbon (1).png`
`carbon (2).png`

is actually the most useful format. When we support an API, we are going to return the image data directly, so you will be able to name the file you save it as however you please.

**Comment by mittalyashu** [comment]
> we are going to return the image data directly
I still don't understand what do you meant by return image data directly.

**Comment by mfix22** [comment]
The API will return a data url representing the snippet (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)

**Comment by mfix22** [comment]
Going to close this because we want to keep one consistent format for the default user.
