### ISSUE TITLE
Constant variable is not highlighted or editable

### ISSUE THREAD

**Issue by mittalyashu** [dawnlabs/carbon#749]
**Describe the bug**
Carbon is not highlighting this line of code `const params = [hash, "--format=%an %n %ae %n %ad"];`, also when I click on this line the cursor is also not showing up.

**Screencast**
https://youtu.be/OcnKf_OpBmI

**Screenshot**
![carbon](https://user-images.githubusercontent.com/29014463/57070383-d43b8000-6cf4-11e9-84a3-cc9a3f40b29f.png)

**Info (please complete the following information):**
 - OS [e.g. macOS, Linux, Windows, iOS]: Windows 10
 - Browser [e.g. chrome, safari]: Microsoft Edge _(chromium)_
 - Mode: PWA

**Comment by mfix22** [comment]
Please include the code snippet as part of issue filing so we can debug appropriately. Feel free to contribute a fix for this issue as well.

**Comment by mittalyashu** [comment]
Here's the code snippet

```js
getAuthorDetail(hash) {
			const params = [hash, "--format=%an %n %ae %n %ad"];
			showMixin(this.currentRepository, params).then(result => {
				let output = result.split("\n");
				this.$store.dispatch({
					type: "history/updateCommitInformationAuthor",
					author_name: output[0].trim(),
					author_email: output[1].trim(),
					author_date: output[2].trim()
				});
			});
		}
```

Sure, will try to fix the issue too.
