### ISSUE TITLE
Speed of making picture is too slow!

### ISSUE THREAD

**Issue by boxter007** [dawnlabs/carbon#752]
### Expected Behavior
I want to make a code picture with 20 lines code, but it will be waiting about 1-2minutes. whatever I use carbon.now.sh or my localhost.
### Actual Behavior
Waiting for 1-2 seconds

**Comment by mfix22** [comment]
@boxter007 please provide the browser information that was requested in the PR template. _Also_, are you saving as an SVG or PNG.

**Comment by boxter007** [comment]
The browser is chrome 74.0.3729.131,64bit.
And I saved the picture as PNG

**Comment by mfix22** [comment]
Do you have a code snippet to test on?

**Comment by boxter007** [comment]
a simple code snippet.
`No = 1
def show(n, f, t):
    global No 
    result = 'No：{1}，From {2} To {3} '.format(No, n, f, t)
    print(result)
    No += 1


def move(n, a, b, c): 
    if n == 1:
        show(n, a, c)
    else:
        move(n-1, a, c, b)
        show(n, a, c)
        move(n-1, b, a, c)

x = 10
move(x, 'a', 'b', 'c')`

This code snippet spent more than 1 minutes.
![zzzz](https://user-images.githubusercontent.com/9445146/57417278-7ea42d80-7236-11e9-8a44-5b4759332dc2.png)

**Comment by mfix22** [comment]
Interesting, when I tried it with that code snippet, it ran almost instantly. Do you have any Chrome extensions enabled that may be interfering with the download?

**Comment by boxter007** [comment]
I tried to disable all extensions, but the issue was still . And I tried safari ,it was the same.
I guess that my setting is wrong, but when I use carbon.now.sh to make picture ,sometime it runs quickly and mostly it likes the localhost.

**Comment by boxter007** [comment]
Aha, I know what is the trouble!
Facebook is blocked in China , maybe some url can not be got , and I need waiting for timeout.
