### ISSUE TITLE
Add an option to blur lines

### ISSUE THREAD

**Issue by vvscode** [dawnlabs/carbon#756]
Proposal: add an option which allows blurring lines. On interface, it might be just checkboxes near every line of code - if checked it looks as is, otherwise, it is blurred.

This might be really helpfull for preparation code-explanations - when you need focus on a certain line, but don't want to remove all surrounding context. Or want to follow across a code line-by-line with explanation

To get something like this:
<img width="1012" alt="Screen Shot 2019-05-09 at 10 30 16" src="https://user-images.githubusercontent.com/6904368/57431962-7d2e3180-7245-11e9-9877-70e891ae87c3.png">

**Comment by mfix22** [comment]
We are already working on making it such that you can _highlight_ certain lines. Would this work instead of blurring for you? 🙂

**Comment by vvscode** [comment]
Yes )
