### ISSUE TITLE
Maintaining indentation when wrapped to new line

### ISSUE THREAD

**Issue by msrshahrukh100** [dawnlabs/carbon#761]
Is there any way to implement indent wrapping as mentioned in the [Code mirror docs](https://codemirror.net/demo/indentwrap.html) ?

Because now if the code is long enough to get wrapped to the new line then the text is indented to the left, without maintaining the indentation of the previous line.

![image](https://user-images.githubusercontent.com/13628270/57825849-5d0aef00-77be-11e9-8ad5-95ef0a92c002.png)

Refer to the screen shot above. Consider the return statement in the screenshot.

**Comment by mfix22** [comment]
Before we get started down any path, can you please post the snippet above here so I can reproduce your issue? Thanks!

**Comment by msrshahrukh100** [comment]
This is from the homepage of carbon.sh. I just entered a long line, the text got wrapped but lost its indentation. 
To reproduce it, just enter a long line. Hope it makes sense. I am attaching the full screen shot here ->

![image](https://user-images.githubusercontent.com/13628270/57903260-dec84e80-788a-11e9-974d-4844a9433865.png)

**Comment by mfix22** [comment]
Closing in favor of #781
