### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by turibbio** [dawnlabs/carbon#770]
Please provide markdown support.

**Comment by mfix22** [comment]
There is a "Markdown" setting in the language dropdown, shown in the image below: 

<img width="912" alt="Screenshot 2019-05-23 09 42 33" src="https://user-images.githubusercontent.com/8397708/58270623-19286480-7d3f-11e9-9158-cd70a2867d99.png">

**Comment by turibbio** [comment]
Fantastic! I totally missed that!
