### ISSUE TITLE
URL share option - doesn't produce expected image

### ISSUE THREAD

**Issue by Saif-Shines** [dawnlabs/carbon#773]
### Expected Behavior

- Copy and Paste the Code that I want to download as a image on carbon
- In 'Export' > URL get the url of the image
- Use it on web  to reproduce the same image that I expected

### Actual Behavior

- The URL gives image with a string adding %s and other characters in place of spaces.

#### Browser:
Please see my complete Browser information [here](https://whatsmybrowser.org/b/JK7JHVQ).

#### Screen Recording

Please find screen recording of the issue [here](https://imgur.com/a/AcTMj9L).

#### Code Snippet (If Applicable):

Here is the [URL]( https://carbon.now.sh/?bg=rgba(171%25252C%252520184%25252C%252520195%25252C%2525201)&t=one-light&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fm=Hack&fs=14px&lh=133%252525&si=false&es=1x&wm=false&code=function%252520job()%252520%25257B%25250A%252520%252520%252520%252520return%252520new%252520Promise(function(resolve%25252C%252520reject)%252520%25257B%25250A%252520%252520%252520%252520%252520%252520%252520%252520reject()%25253B%25250A%252520%252520%252520%252520%25257D)%25253B%25250A%25257D%25250A%25250Alet%252520promise%252520%25253D%252520job()%25253B%25250A%25250Apromise%25250A.then(function()%252520%25257B%25250A%252520%252520%252520%252520console.log('Success%2525201')%25253B%25250A%25257D)%25250A%25250A.then(function()%252520%25257B%25250A%252520%252520%252520%252520console.log('Success%2525202')%25253B%25250A%25257D)%25250A%25250A.then(function()%252520%25257B%25250A%252520%252520%252520%252520console.log('Success%2525203')%25253B%25250A%25257D)%25250A%25250A.catch(function()%252520%25257B%25250A%252520%252520%252520%252520console.log('Error%2525201')%25253B%25250A%25257D)%25250A%25250A.then(function()%252520%25257B%25250A%252520%252520%252520%252520console.log('Success%2525204')%25253B%25250A%25257D)%25253B%25250A)

**Comment by mfix22** [comment]
Hi @Saif-Shines this is actually intended. Blog sites like Medium.com actually require you to encode the URL since they decode it before using it to create an iFrame. 

Therefore, if you want to use the URL on Medium, use the `Export > URL` button. If you just want to share it, copy it from the Browser URL input 👍

**Comment by Saif-Shines** [comment]
I want to add it Google Docs: Add Image by URL option

Google docs don't recognize this as an Image URL. Is there any way to overcome this?

**Comment by mfix22** [comment]
Neither of this are image URLs! I would recommend just saving the image and then pasting it directly to Google Docs.
