### ISSUE TITLE
Shortcut for carbon doesn't work on Atom on Mac

### ISSUE THREAD

**Issue by RohitMidha23** [dawnlabs/carbon#778]
**Describe the bug**
I'm not sure if this problem persists only for me but when I try `cmd + shift + A` nothing happens. However when I go to `Packages -> carbon.now.sh -> Toggle` , it works perfectly.

**To Reproduce**

To reproduce the error try `cmd + shift + A` in atom, on a mac.

**Expected behavior**
I thought the GUI with the picture would pop up. 

**Info (please complete the following information):**

- OS : macOS Mojave 10.14.3
- Browser: Chrome

**Comment by mfix22** [comment]
@ericadamski yo Eric do you know the issue here? Did we do anything to break the Atom plugin?

**Comment by ericadamski** [comment]
@mfix22 I highly doubt it, seems like an Atom plugin issue.

@RohitMidha23 Can you post this issue in https://github.com/ericadamski/atom-carbon-now-sh and I will help you look into why this isn't working for you 😄

**Comment by mfix22** [comment]
@RohitMidha23 maybe some other app you have installed is intercepting `cmd + shift + A` and preventing the action 🤷‍♂

**Comment by ericadamski** [comment]
That would be my guess as well. I would love to help you figure it out!

**Comment by RohitMidha23** [comment]
I'll look into it, Thanks @mfix22 and @ericadamski
