### ISSUE TITLE
Exported PNG has transparent space on top and bottom

### ISSUE THREAD

**Issue by kiernann** [dawnlabs/carbon#796]
**Describe the bug**
When exporting an image as PNG 4x size, the file has a small line of transparent space on the top and bottom of the image. This can be a problem when sharing on some sites.

**Screenshots**

Obviously, hard to see in the raw image, so here's a screenshot with black around the image:
![image](https://user-images.githubusercontent.com/18021678/60037606-fcee4f00-967f-11e9-8708-ef018fcdcf9d.png)

**Info**

- OS Ubuntu 19.04
- Chrome 75.0.3770.100

**Comment by mfix22** [comment]
@kiernann it is on the top of your image? This line of transparent pixels should be at the bottom of the image ([Source](https://github.com/dawnlabs/carbon/blob/master/components/Carbon.js#L276), see issue #86)

Just want to clear this up first. I will make it so that the row of pixels is only included when saving to Twitter.

**Comment by kiernann** [comment]
@mfix22 Yes, the transparent pixels are on the top and bottom of the exported image. I didn't know it was an intended feature. Ironically, I had saved the image for the purpose of tweeting and didn't love the way the top and bottom looked on twitter. I can always crop it manually, just thought it might be a bug!

Here's the raw export for reference:

![negate_in](https://user-images.githubusercontent.com/18021678/60038678-fd3c1980-9682-11e9-9af2-3f6c493bb5b8.png)

**Comment by mfix22** [comment]
@kiernann with the update I am making, by default the transparent row won't be included, unless you click the "Tweet" button directly 👍That way we cover both use cases.
