### ISSUE TITLE
Font issue with 3 asterisks

### ISSUE THREAD

**Issue by jcubic** [dawnlabs/carbon#800]
`***` is broken with correct font.

### Expected Behavior

`***` is rendered correctly

### Actual Behavior

![carbon (4)](https://user-images.githubusercontent.com/280241/60251684-4c738b80-98c9-11e9-8f27-519c8434173c.png)

<details>
  <summary>Browser: </summary>
  Chrome Windows
</details>

<details>
  <summary>Code Snippet (If Applicable)</summary>
  (define (*** **) (* ** **))
</details>

**Comment by jcubic** [comment]
Not sure if this is an issue because just found that you can change the font. (this one was default Fira Code).

**Comment by mfix22** [comment]
@jcubic the symbol you are noticing is a Fira Code "[ligature](https://en.wikipedia.org/wiki/Typographic_ligature)". You can see it in their docs here: https://github.com/tonsky/FiraCode 🙂
