### ISSUE TITLE
Folder tree preview

### ISSUE THREAD

**Issue by moniuch** [dawnlabs/carbon#803]
Not sure how it would fit into the interface as it is not just syntax highlighting, but I will leave it to you to decide.

I often need to share an idea of a folder/file structure. I would expect to be able to type in an indentation-based structure and appreciate a nice PNG/SVG output with generic folder and file icons in front of the names

A `+` would be rendered as a folder icon, `-` would stand for a file.

```
+ Folder 1
  + Folder 1.1 (has no children)
  - File 1.2
  - File 1.3
  + Folder 1.4 (has children)
    - Folder 1.4.1
  - File 1.5
+ Folder 2
- File 3
```

**Comment by mfix22** [comment]
@moniuch are you using a linux based operating system? The [`tree` command](https://linux.die.net/man/1/tree) creates a really nice structure, and you can paste that right into Carbon.

**Comment by moniuch** [comment]
I am on Mac. I have seen recommendations for tree and for mddir, but from what I understood they just translate contents of an **existing** directory into md/ASCII text. This is not what I am after. My use case is when I need to quickly illustrate an example tree view off the top of my head (without first creating a dir). So the input would be my free text and the desired output would be an SVG/PNG file, just like the current code images.

**Comment by mfix22** [comment]
If that is the case, can you just type it directly into Carbon? Some of the existing language highlights look good already: 


<p align="center">
<img alt="SQL" width="48%" src="https://user-images.githubusercontent.com/8397708/60548202-88ef1f00-9cef-11e9-9bf2-df70a398c7e1.png" />
<img alt="Apache" width="48%" src="https://user-images.githubusercontent.com/8397708/60548207-8bea0f80-9cef-11e9-8a91-c56b0c6e73f9.png" />
</p>

**Comment by mittalyashu** [comment]
Or something like this?

```
.
├── _config.yml
├── _drafts
 |   ├── begin-with-the-crazy-ideas.textile
 |   └── on-simplicity-in-technology.markdown
├── _includes
 |   ├── footer.html
 |   └── header.html
├── _layouts
 |   ├── default.html
 |   └── post.html
├── _posts
 |   ├── 2007-10-29-why-every-programmer-should-play-nethack.textile
 |   └── 2009-04-26-barcamp-boston-4-roundup.textile
├── _data
 |   └── members.yml
├── _site
└── index.html
```

**Comment by mfix22** [comment]
@moniuch does this work for you?

**Comment by moniuch** [comment]
I can live with it. Thanks for the hint.
