### ISSUE TITLE
Medium snippets not working since 1 week - empty iframe

### ISSUE THREAD

**Issue by jterrazz** [dawnlabs/carbon#815]
**Describe the bug**
Hello, I posted this [article](https://medium.com/a-42-journey/how-to-create-your-own-malloc-library-b86fedd39b96) on medium. It was working fine for the last month, but now it just shows an empty space (the iframe load an empty body).

**To Reproduce**

1. Create an article on medium
2. Paste the url of a code snippet
https://carbon.now.sh/embed?bg=rgba(178%2C169%2C253%2C1)&code=%2523%2520We%2520will%2520implement%2520this%2520functions%250A%250Avoid%2520malloc(size_t%2520size)%253B%250Avoid%2520free(void%2520ptr)%253B%250Avoid%2520realloc(void%2520ptr%252C%2520size_t%2520size)%253B%250Avoid%2520calloc(size_t%2520count%252C%2520size_t%2520size)%253B%250A%250A%2523%2520Allowed%2520calls%253A%2520allocating%2520memory%250A%250A%2523include%2520%253Csys%252Fmman.h%253E%250Avoid%2520mmap(void%2520addr%252C%2520size_t%2520len%252C%2520int%2520prot%252C%2520int%2520flags%252C%2520int%2520fd%252C%2520off_t%2520offset)%253B%250Aint%2520munmap(void%2520addr%252C%2520size_t%2520len)%253B%250A%250A%2523%2520Allowed%2520calls%253A%2520limiting%2520our%2520memory%2520calls%250A%250A%2523include%2520%253Csys%252Fresource.h%253E%250Aint%2520getrlimit(int%2520resource%252C%2520struct%2520rlimit%2520rlp)%253B%250Aint%2520setrlimit(int%2520resource%252C%2520const%2520struct%2520rlimit%2520rlp)%253B%250A%250A%2523include%2520%253Cunistd.h%253E%250Aint%2520getpagesize(void)%253B&ds=true&dsblur=68px&dsyoff=20px&es=4x&fm=Hack&fs=14px&l=auto&lh=133%25&ln=false&ph=56px&pv=56px&referrer=https%3A%2F%2Fmedium.com%2Fa-42-journey%2Fhow-to-create-your-own-malloc-library-b86fedd39b96&si=false&t=seti&wa=true&wc=true&wm=false&wt=none

Tested on latest safari/chrome desktop + safari mobile

**Comment by mfix22** [comment]
Thanks for bringing this to my attention! I reverted a recent commit and the issue has been resolved. 

The root issue is fixed here: c5f45eb398f5debad054216ccf318e5e22d60f4e. Deploying the fix now.
