### ISSUE TITLE
carbon.now.sh refused to connect.

### ISSUE THREAD

**Issue by esimov** [dawnlabs/carbon#816]
It worked until now, but from 3 days on I was getting the the following message, when pasted the carbon source code as an iframe: carbon.now.sh refused to connect.

Checking the console log I was getting the following messages:

![image](https://user-images.githubusercontent.com/883386/61199292-12d2bb00-a6e6-11e9-991e-732af88cdf43.png)

What has been changed and how this can be overcome?

**Comment by mfix22** [comment]
Thanks for bringing this to my attention! I reverted a recent commit and the issue has been resolved. Will fix the root issue immediately.

**Comment by mfix22** [comment]
The root issue is fixed here: c5f45eb398f5debad054216ccf318e5e22d60f4e. Deploying the fix now :+1:

**Comment by esimov** [comment]
Thanks, it works.
