### ISSUE TITLE
Medium iframe dynamic height issue

### ISSUE THREAD

**Issue by jterrazz** [dawnlabs/carbon#817]
**Describe the bug**
Hello,

Thanks for resolving the issue #815, however a bug came back, which was resolved 2 weeks ago I believe.
You can see it on this links for example 
- https://medium.com/a-42-journey/implementing-the-sha256-and-md5-hash-functions-in-c-78c17e657794 
- https://medium.com/a-42-journey/how-to-create-your-own-malloc-library-b86fedd39b96

The first Carbon iframe seems to not calculate the correct height, and the following ones add bottom margin after the code snippets.

**Expected behavior**
Correct height calculation and no margin for Medium iframes.

**Info (please complete the following information):**
- OS: MacOS
- Browser: Safari, chrome

**Comment by mfix22** [comment]
@jterrazz do you have a link to the original issue? I have never seen height issues like this before.

**Comment by jterrazz** [comment]
I'm not sure there is an issue, but I had this problem until 2 or 3 weeks ago. I didn't change anything in my article and it was resolved, so it was probably an update coming from you or Medium.

**Comment by mfix22** [comment]
I haven't touched anything related to Embed's recently. I will investigate this issue though — potentially Medium has changed how they listen to height changes.

**Comment by jterrazz** [comment]
One more thing, there is no issue when I'm editing the story, but as soon as I publish the story, the height is bad. 

It seems the height is badly calculated by the Embedly iframe (it wraps before the Carbon iframe): 
<img width="1920" alt="Screen Shot 2019-07-16 at 4 00 48 PM" src="https://user-images.githubusercontent.com/18480834/61301111-932b1600-a7e3-11e9-96ac-043b0ea00d56.png">

**Comment by mfix22** [comment]
Thanks for confirming this — I noticed this too! Potentially it is an issue sending the `postMessage` to the wrong frame (since it is nested deeper when published). 

I will look into this 👍

**Comment by mfix22** [comment]
@jterrazz can you try prepublishing the post? I just tried embedding your exact snippet in a new Medium article and everything is rendering appropriately: https://medium.com/@fixitup2/test-carbon-embeds-80580a24891

The `iframe` has a height of 558, and if you go to the [original snippet](https://carbon.now.sh/embed?bg=rgba(178%2C169%2C253%2C1)&code=%2523%2520We%2520will%2520implement%2520this%2520functions%250A%250Avoid%2520malloc(size_t%2520size)%253B%250Avoid%2520free(void%2520ptr)%253B%250Avoid%2520realloc(void%2520ptr%252C%2520size_t%2520size)%253B%250Avoid%2520calloc(size_t%2520count%252C%2520size_t%2520size)%253B%250A%250A%2523%2520Allowed%2520calls%253A%2520allocating%2520memory%250A%250A%2523include%2520%253Csys%252Fmman.h%253E%250Avoid%2520mmap(void%2520addr%252C%2520size_t%2520len%252C%2520int%2520prot%252C%2520int%2520flags%252C%2520int%2520fd%252C%2520off_t%2520offset)%253B%250Aint%2520munmap(void%2520addr%252C%2520size_t%2520len)%253B%250A%250A%2523%2520Allowed%2520calls%253A%2520limiting%2520our%2520memory%2520calls%250A%250A%2523include%2520%253Csys%252Fresource.h%253E%250Aint%2520getrlimit(int%2520resource%252C%2520struct%2520rlimit%2520rlp)%253B%250Aint%2520setrlimit(int%2520resource%252C%2520const%2520struct%2520rlimit%2520rlp)%253B%250A%250A%2523include%2520%253Cunistd.h%253E%250Aint%2520getpagesize(void)%253B&ds=true&dsblur=68px&dsyoff=20px&es=4x&fm=Hack&fs=14px&l=auto&lh=133%25&ln=false&ph=56px&pv=56px&referrer=https%3A%2F%2Fmedium.com%2Fa-42-journey%2Fhow-to-create-your-own-malloc-library-b86fedd39b96&si=false&t=seti&wa=true&wc=true&wm=false&wt=none), so too does the export container.

**Comment by jterrazz** [comment]
I tried republishing the post with the exact same content, and its rendering properly. Should I delete my bugged article or do you want it for debugging ?

**Comment by mfix22** [comment]
Feel free to do what you please with it! 🙂
