### ISSUE TITLE
Carbon fails to load URL that is too long due to code query parameter length

### ISSUE THREAD

**Issue by LGTMXD** [dawnlabs/carbon#829]
i wanna make code lines pretty on my website using iFrame，code sourece is blew
https://raw.githubusercontent.com/233boy/v2ray/master/install.sh
when i do it on Carbon，website crash down 
maybe   Chinese code comments in the bash cause it

**Comment by mfix22** [comment]
Hi @LGTMXD when does the crash occur? When you embed that code in an IFrame, or when you save the image? Also which browser were you using when the crash occurred?

**Comment by LGTMXD** [comment]
Problem recurrence video：
https://youtu.be/zOooeBsFQnY

each time i do plenty line codes the crash occurred

**Comment by mfix22** [comment]
I see the error: it actually has nothing to do with any of the buttons, it is just the fact that the URL length surpassed the browsers limit. I will add some logic to limit the amount of code characters written to the URL, however we cannot overcome these underlying limits for sharing as a query param /:

**Comment by LGTMXD** [comment]
thank u

**Comment by Looskie** [comment]
Just in case anyone happens to fall on this issue,

if you're trying to use this service with chromedp (go's "alternative" to puppeteer) and need the `code` parameter to be longer, you can pass it in `CARBON_STATE` in `localStorage`. But make sure `CARBON_STATE` is valid, otherwise it will be ignored.

I do the following in golang (but dont be scared to replicate in puppeteer/other languages)

```go
var carbonState = `{"code":"here it is!", "paddingVertical":"25px","paddingHorizontal":"25px","backgroundImage":null,"backgroundImageSelection":null,"backgroundMode":"color","backgroundColor":"linear-gradient(144.12deg, #1F1E1E 20.99%, #353535 100.33%);","dropShadow":true,"dropShadowOffsetY":"20px","dropShadowBlurRadius":"68px","theme":"theme:837ta3fl5eq","windowTheme":"none","language":"auto","fontFamily":"JetBrains Mono","fontSize":"15px","lineHeight":"133%","windowControls":true,"widthAdjustment":false,"lineNumbers":false,"firstLineNumber":1,"exportSize":"2x","watermark":false,"squaredImage":false,"hiddenCharacters":false,"name":"","width":"700"}`

chromedp.Tasks{
  chromedp.Navigate(url),
  chromedp.Evaluate(fmt.Sprintf("localStorage.setItem('CARBON_STATE', '%s')", carbonState), res),
  // we need to reload because theres no check for localstorage change after init (as expected)
  chromedp.Reload(),
  chromedp.Screenshot("#export-container", res),
}
```

hopes this helps someone
