### ISSUE TITLE
Safari 11: Save Image

### ISSUE THREAD

**Issue by tillkruss** [dawnlabs/carbon#85]
Saving as image doesn't work.

```
[Error] TypeError: e.replace is not a function. (In 'e.replace(/&/g,"&amp;")', 'e.replace' is undefined)
	t (app.js:21:977311)
	p (app.js:21:982629)
	value (app.js:21:616414)
	value
	value (app.js:21:616248)
	value
	(anonymous function) (app.js:21:1529383)
	bt (app.js:2:23963)
	vt (app.js:2:24238)
	ar (app.js:2:50646)
	pr (app.js:2:53169)
	Za (app.js:2:98526)
	(anonymous function) (app.js:2:147167)
[Error] Unhandled Promise Rejection: [object Event]
	(anonymous function)
	promiseReactionJob
```

**Comment by zcei** [comment]
This is a known limitation in the [underlaying library](https://github.com/tsayen/dom-to-image#browsers).

Safari is stricter with a specific tag that is used to render the DOM to an image. A potential workaround would be rendering it as an SVG and use a server endpoint to render it to an SVG.

I'm currently building a server endpoint that takes the settings & code and returns a PNG directly - this could eventually be used for Safari users as well, I guess.

**Comment by mfix22** [comment]
Thanks @zcei. We will track this issue at #28. Closing.
