### ISSUE TITLE
Twitter saves images as JPEG

### ISSUE THREAD

**Issue by iamale** [dawnlabs/carbon#86]
This can be easily avoided though by making some part of an image semi- or fully transparent (e. g. the whole background or just the top left pixel). You can look at https://github.com/iamale/screentweet and https://github.com/Francesco149/gweet/issues/2 for some exploration.

And thanks for a great service, by the way!

**Comment by jakedex** [comment]
Great catch, @iamale! It looks like it's only happening on a few of the images, but we'll want to fix this regardless.
