### ISSUE TITLE
Adjust width

### ISSUE THREAD

**Issue by mxstbr** [dawnlabs/carbon#91]
I just generated this image:

![carbon-1](https://user-images.githubusercontent.com/7525670/31087551-bb0bee3a-a79d-11e7-8f04-88e2eaa3e5b4.png)

It'd be great if:

- I could make the font size bigger (ref #46)
- but also if I could shrink the width of the code block manually (or it adjust automatically based on longest line)

**Comment by pa7ryk** [comment]
Hi, I think I can give it a try.

**Comment by mfix22** [comment]
See #33 and #1 for discussion reference as well. I also believe @jakedex is working on font-size fix

**Comment by pa7ryk** [comment]
I can create new setting next to _Window controlls_ which will enables automatic width adjust based on longest line. IMHO manual width adjustment is not a bare necessary thing. What do you think?

**Comment by mxstbr** [comment]
Agreed, automatic would be optimal.

**Comment by jakedex** [comment]
I'm totally fine with that. Automatic is a great start and we can leave #1 open in case someone wants to take a shot at manual.
